### ISSUE TITLE
duplicated CSS

### ISSUE THREAD

**Issue by cometta** [addyosmani/critical#104]
After critical CSS is generated and inlined in index.html, the existing external source styles.css have duplicated css that already existed inside inlinded index.html. I believe this is a default behavior. Any plan to do enhancement to remove those css from source styles.css?

**Comment by bezoerb** [comment]
you could try the `extract` option. See https://github.com/addyosmani/critical#options

**Comment by cometta** [comment]
i tested, the inline css still exist in style.<random>.css. 

gulp.task('critical', function () {
    return gulp.src('dist/*.html')
        .pipe(critical({base: 'dist/', inline: true, extract:true, css: ['style.css']}))
        .pipe(gulp.dest('dist'));
});

**Comment by cometta** [comment]
it is working. thank you.

**Comment by KingScooty** [comment]
Is this only working when using the inline option? When inline is disabled, extract doesn't seem to work as i'm still getting duplicate CSS.

**Comment by gisu** [comment]
And only on a `index.html` other Files like `article.html` have no doubled Inline CSS.
