### ISSUE TITLE
Missing support for onLoad

### ISSUE THREAD

**Issue by drcmda** [addyosmani/critical#110]
Hello Addy,

my site uses Javascript to calculate height for certain elements (section waypoints). Usually this is safe to do when the document has loaded. With critical though my css is async. JS calculates wrong and sometime later the css comes in. Fillament has an event for it luckily.

This is what critical generates for me:

    <script>
    (function(u){function loadCSS(e,t,n){"use strict";function r(){for(var t,i=0;i<d.length;i++)d[i].href&&d[i].href.indexOf(e)>-1&&(t=!0);t?o.media=n||"all":setTimeout(r)}var o=window.document.createElement("link"),i=t||window.document.getElementsByTagName("script")[0],d=window.document.styleSheets;return o.rel="stylesheet",o.href=e,o.media="only x",i.parentNode.insertBefore(o,i),r(),o}for(var i in u){loadCSS(u[i]);}}(['http://fonts.googleapis.com/css?family=Open+Sans:400|Special+Elite','fonts/exchange.f9715081.css','default.dd83315a.css']));
    </script>

loadCSS would, in theory return 3 links, together with the polyfill they offer i could make it work if there would be a way to expose them.

Thanks! (-:

**Comment by bezoerb** [comment]
@drcmda this issue could not be solved here as the inlining is handled by `inline-critical`. I made an issue over there

**Comment by bezoerb** [comment]
closed in favor of https://github.com/bezoerb/inline-critical/issues/47
