### ISSUE TITLE
Add or inline critical CSS file ? 

### ISSUE THREAD

**Issue by ethyde** [addyosmani/critical#112]
Hi,

I have read #89 and #109 but i don't find any solution with ```inline``` option to just add or append critical CSS file to any other file (i.g : a template, or any kind of include) instead of generate a complete, static html file, it's possible ?

Thanks.

**Comment by bezoerb** [comment]
No, the `inline` option can only produce a complete static html file. When you want to include critical in a partial you'll need to generate the critical css and do the inlining yourself.

**Comment by ethyde** [comment]
Ok, thanks.

**Comment by TonyTran0209** [comment]
Hi Bezoerb,

Can I export to individual critical CSS file, not in a static HTML file?
If yes, how to do that?

Thanks.
