### ISSUE TITLE
Media print 

### ISSUE THREAD

**Issue by luckyraul** [addyosmani/critical#113]
When I used critical via url I got media="print" css used as normal css and created critical with it's contents

**Comment by bezoerb** [comment]
Good catch. Looks like we need to patch `oust` for this one.
https://github.com/addyosmani/oust/pull/17

When this PR is accepted we can filter extracted stylesheets. 
/cc @addyosmani

**Comment by luckyraul** [comment]
any updates ?

**Comment by Inalkar** [comment]
@bezoerb I have encountered with the same issue. Can you look into into? FYI [https://github.com/addyosmani/oust/pull/17](addyosmani/oust#17) has been already implemented.

**Comment by bezoerb** [comment]
fixed in 07be40bab23eb518bb689062b43f0db507c9a1f9
