### ISSUE TITLE
Extract not removing some rules

### ISSUE THREAD

**Issue by bakaat** [addyosmani/critical#115]
Hi,

We've got a problem where some css rules are not properly extracted from the source file. In rule

    .spinner {
      position:relative;
      width:1em;
      height:1em;
      font-size:32px;
      border-bottom:2px solid;
      overflow:hidden;
      text-indent:100%;
      -webkit-animation:.5s spinner linear infinite;
      animation:.5s spinner linear infinite}

The same rule inlined

    .spinner {
      position: relative;
      width: 1em;
      height: 1em;
      font-size: 32px;
      border-bottom-width: 2px;
      border-bottom-style: solid;
      border-bottom-color: initial;
      overflow-x: hidden;
      overflow-y: hidden;
      text-indent: 100%;
      -webkit-animation-name: spinner;
      -webkit-animation-duration: 0.5s;
      -webkit-animation-timing-function: linear;
      -webkit-animation-delay: initial;
      -webkit-animation-iteration-count: infinite;
      -webkit-animation-direction: initial;
      -webkit-animation-fill-mode: initial;
}

we're using `critical 0.6` and `inline-critical 0.4.0` but we have the same issue after upgrading to `critical 0.7` and `inline-critical 1.0`

any help or suggestions please ?

**Comment by pocketjoso** [comment]
This is due to how [Penthouse](https://github.com/pocketjoso/penthouse) deals with invalid css. Could you please raise the issue there and I'll respond to it?

Cheers,
Jonas

**Comment by bakaat** [comment]
Closed in favour of https://github.com/pocketjoso/penthouse/issues/102
