### ISSUE TITLE
Difficulty using stream method with Gulp and a glob pattern.

### ISSUE THREAD

**Issue by Tempurturtul** [addyosmani/critical#119]
As demonstrated [here](https://github.com/addyosmani/critical#gulp), I'm attempting to use the stream method to inline critical CSS for all .html files matched by a glob pattern.  My usage differs in that I'm also matching .html files in subdirectories (`dist/*.html` vs `dist/**/*.html`).

The problem I'm having is that critical's base option needs to be redefined for each subdirectory in order for relative paths to CSS files to work.

Example folder structure:

```
dist/
  style.css
  index.html
  views/
    foo.html
```

Problematic html:

``` html
<!-- views/foo.html -->
<link rel="stylesheet" href="../style.css">
```

My gulp task:

``` javascript
gulp.task('critical', function() {
  gulp.src('dist/**/*.html')
    .pipe(critical({
      inline: true,
      base: 'dist/'
    }))
    .pipe(gulp.dest('dist'));
});
```

The above returns "Fatal undefined" because `../style.css` cannot be found in foo.html with the base being `dist/`.  In order to get this working base needs to be `dist/` for index.html and `dist/views/` for foo.html (and so on for additional files).  I'm not sure how to achieve this.  Excluding base doesn't work at all (I'd hoped the default would be the value I'm looking for since this method seems to be included primarily for usage with Gulp).

**Comment by bezoerb** [comment]
@Tempurturtul i've provided a fix in the vinyl branch. Could you check if this fixes your issue?
```
npm install --save-dev git://github.com/addyosmani/critical#vinyl
```

**Comment by Tempurturtul** [comment]
Thanks bezoerb. Here's the error I'm now receiving in all cases (without Plumber, output is "Fatal undefined"):

```shell
[07:35:29] Starting 'critical'...
[07:35:29] Finished 'critical' after 30 ms
[07:35:29] Plumber found unhandled error:
 Error in plugin 'critical'
Message:
    Path must be a string. Received <File "index.html" <Buffer 3c 21 44 4f ... >>
[07:35:29] Plumber found unhandled error:
 Error in plugin 'critical'
Message:
    Path must be a string. Received <File "views/foo.html" <Buffer 3c 21 44 4f ... >>
```

**Comment by bezoerb** [comment]
@Tempurturtul there was an incompatibility to vinyl < v0.5.3. This should be fixed now by 846c233e1bf26b129b002ea7fc8d1fa3429ee2d0

**Comment by Tempurturtul** [comment]
Confirmed; thank you!

**Comment by bezoerb** [comment]
Closed as this seems to be fixed. Feel free to reopen if the error still exists
