### ISSUE TITLE
CSHTML file instead of HTML

### ISSUE THREAD

**Issue by frankwaalkens** [addyosmani/critical#122]
Hi There,

The critical plugin doesn't seem to work with .cshtml files. Is it a known problem?,  and more important, is there a fix for my problem?

Screenshot gulp task error:

![image](https://cloud.githubusercontent.com/assets/11975073/12844140/ee3385c0-cbfd-11e5-95e5-cb8d490aebd7.png)

With kind regards,

Frank

**Comment by bezoerb** [comment]
@frankwaalkens critical doesn't support server-side languages like ASP or PHP as parsing these files is a bit out of scope for this project.
You can alternatively use the corresponding url to your server as `src` to process the files.

**Comment by frankwaalkens** [comment]
Src with multiple files on the server won't work for me since you guys implemented multiple src files with: src: [*.html].

**Comment by bezoerb** [comment]
You'll need to use some module like [`gulp-remote-src`](https://www.npmjs.com/package/gulp-remote-src) or process every url manually. Maybe 
```javascript
var critical = require('./');

['https://www.npmjs.com/package/package', 'https://www.npmjs.com/package/browserify'].forEach(function(url) {
    critical.generate({
        src: url,
        dest: url.replace('https://www.npmjs.com/package/','') + '.css'
    });
});
```
