### ISSUE TITLE
Making Critical CSS an online capability?

### ISSUE THREAD

**Issue by AllThingsSmitty** [addyosmani/critical#128]
Any thought on making this very cool capability an online service?

**Comment by pocketjoso** [comment]
What about:
https://jonassebastianohlsson.com/criticalpathcssgenerator/
https://criticalcss.com

? :)

**Comment by AllThingsSmitty** [comment]
Wow, I wasn't aware of those resources. Thanks, @pocketjoso. 👍🏼
