### ISSUE TITLE
Slow (high latency) internet connections

### ISSUE THREAD

**Issue by dimbslmh** [addyosmani/critical#131]
Scenario:
- Mobile internet (low speed/high latency)
- Page with bootstrap.css and main.css with custom styling

On slow mobile connections, the loadCss is very noticeable.
Initially the inline critical CSS is shown, but when it loads the remaining CSS files, you can see bootstrap.css override the inline CSS and afterwards it gets overridden by the main.css.

What's the best way to solve this? Or is it inevitable to keep the render-blocking CSS in this situation?

**Comment by pocketjoso** [comment]
If you never want to display the result of only having loaded one of these two stylesheets, my suggestion would be to concatenate them.

**Comment by dimbslmh** [comment]
Yes, that's what I need. Thanks for the fast response.
