### ISSUE TITLE
referencing mod_pagespeed's prioritize_critical_css filter

### ISSUE THREAD

**Issue by jmarantz** [addyosmani/critical#132]
Hey Addy, would you consider referencing mod_pagespeed's prioritize_critical_css filter, in your 'alternatives' section here:

https://github.com/addyosmani/critical/blob/master/README.md#what-other-alternatives-to-critical-are-available

We will also reference this one from PageSpeed doc.

**Comment by jmarantz** [comment]
The reference from PageSpeed Insights is live, in the second note below the example: https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery#example

**Comment by bezoerb** [comment]
Maybe a bit late but i added the reference you asked for ;)
