### ISSUE TITLE
overriding image paths

### ISSUE THREAD

**Issue by vlrprbttst** [addyosmani/critical#136]
hello all! :)
this is my folder structure:

![](http://img.prntscr.com/img?url=http://i.imgur.com/ICy8VIh.png)

and here's my configuration:

```
                base: './',
                css: '_dev/css/main.css',
                width: 1200,
                height: 500
            },
            src: '_dev/index.html',
            dest: '_dev/critical-css/index.css'
```

in the source folder, the path of an image would be `url("../images/pizza.jpg");`, critical transforms it in `url("/_dev/images/pizza.jpg");` 

is there a way of **not** having that `/_dev/` prefix but just a `/`, as of my folder structure that doesn't work for me.

I've tried messing around with some critical options, but I can't get it to work.

thanks you!

**Comment by bezoerb** [comment]
@vlrprbttst have you tried setting `base` fo `./_dev` ?

**Comment by vlrprbttst** [comment]
ah! thanks :)

**Comment by vlrprbttst** [comment]
i've been trying everything with no success :sob:

**Comment by bezoerb** [comment]
We published a new prerelease version. You can now use the `rebase` option to specify/overwrite image paths. You even can define a transform function which will be called for every asset reference found in the stylesheet

You can install the new version with `npm i critical@next`

Thanks

**Comment by bezoerb** [comment]
Closing this for now but feel free to re-open if anything doesn't fit
