### ISSUE TITLE
Type error when running Critical in Gulp: critical is not a function

### ISSUE THREAD

**Issue by caraya** [addyosmani/critical#137]
I downloaded version 0.7.2 and stream support doesn't seem to be working. I get the following error:`TypeError: critical is not a function`

Installing from Git works.  

This may be related to #87 but, since we are on a later version, I opened it as a new issue.

**Comment by bezoerb** [comment]
It looks like you missed the `stream` function. See https://github.com/addyosmani/critical#gulp

**Comment by caraya** [comment]
When I used `var critical = require('critical').stream`before moving to using the master Github branch I got a different error after the task starts: `Fatal undefined`. 

I will test it again to make sure stream is not the issue but I'm pretty confident it is not.

**Comment by caraya** [comment]
I reinstalled critical from NPM and now it works. Can't figure out what caused the error. Sorry for the noise
