### ISSUE TITLE
Problem serving background-images from CDN in inline css

### ISSUE THREAD

**Issue by rd4704** [addyosmani/critical#143]
Is there a way we can serve the background-images via a CDN. Currently the path in our styles are set to relative to the CDN which once comes to inline style doesn't work. If we can specify the full path to the images for the generated inline css would be great.
current : `background:url(/img/banner/image.png)`
expected which would work: `background:url(https:/mycdn.com/img/banner/image.png)`
Any suggestions please?

**Comment by addyosmani** [comment]
Thanks for filing a bug. Hmm. I'm trying to think about the best layer to tackle this at. We could potentially do it in https://github.com/bezoerb/inline-critical (cc @bezoerb) allowing you to readjust paths accordingly.

**Comment by bezoerb** [comment]
@addyosmani, @rd4704 sorry for the late response. I think this issue could be resolved by https://github.com/addyosmani/critical/pull/127

**Comment by bezoerb** [comment]
We published a new prerelease version. You can now use the rebase option to specify/overwrite image paths. You even can define a transform function which will be called for every asset reference found in the stylesheet

You can install the new version with `npm i critical@next`

Thanks

Closing this for now but feel free to re-open if anything doesn't fit
