### ISSUE TITLE
Issues with Gulp, Critical and Run-Sequence

### ISSUE THREAD

**Issue by RichardsonWTR** [addyosmani/critical#144]
I'm using this code, and I have one deploy task that is running with [run-sequence](https://www.npmjs.com/package/run-sequence). But the next task is catching some temporary files generated by critical plugin. Am I doing something wrong?

```
var critical = require('critical').stream;

// Generate & Inline Critical-path CSS
gulp.task('critical', function () {
    return gulp.src('dist/index.html')
        .pipe(critical({
         // some parameters
         }))
        .pipe(gulp.dest('dist'));
});
```

In deploy the next task (ghPages) is catching the temp files. 

```
gulp.task('deploy',function(callback){
    runSequence('build','critical','ghPages',callback);
});
```

**Comment by ChaseGiunta** [comment]
Also experiencing this... Related to #60 possibly? Not placing temp files in any directory, instead placing them in project root.

**Comment by bezoerb** [comment]
Sorry but there's currently no other way than running the `ghPages` task after critical is done. (See #60)
