### ISSUE TITLE
Fails on Windows due to tmp directory

### ISSUE THREAD

**Issue by XhmikosR** [addyosmani/critical#149]
```
C:\Users\xmr\Desktop\grunt-critical>node -v && npm -v
v4.4.7
2.15.8

C:\Users\xmr\Desktop\grunt-critical>npm test

> grunt-critical@0.2.1 test C:\Users\xmr\Desktop\grunt-critical
> grunt ci

Running "jshint:all" (jshint) task
>> 3 files lint free.

Running "startServer" task

Running "critical:test-css" (critical) task
>> File "test/generated/critical.css" failed. ENOENT: no such file or directory, open 'C:\tmp\tmp-2852vK07mFgK4V6T.tmp'
Warning: File "test/generated/critical.css" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.

```

The Windows temp directory isn't in that path.

```
C:\Users\xmr\Desktop>echo %temp%
C:\Users\xmr\AppData\Local\Temp
C:\Users\xmr\Desktop>echo %tmp%
C:\Users\xmr\AppData\Local\Temp
```

**Comment by XhmikosR** [comment]
@sindresorhus: any idea about this? You can see the live failure here https://ci.appveyor.com/project/addyosmani/critical/build/189/job/q87tb7eta4nmhh3x#L286

All the environment variables are there, defined and pointing to the right directory.

**Comment by XhmikosR** [comment]
Also CC @bezoerb just in case you have any idea

**Comment by XhmikosR** [comment]
`tempfile` seems to work properly:

```
>> csspath C:\Users\xmr\AppData\Local\Temp\3ad24bf2-aaa4-48cf-9418-66b6beea4249.css
```

So, the issue must be in the rest of `tmp` handling.

**Comment by XhmikosR** [comment]
I give up for now.

It's like `tmp` has its options messed up somewhere in file-helper.js.

**Comment by bezoerb** [comment]
Spotted the error in `penthose`
PR submitted. When this is merged we should get our windows tests green again
/cc @XhmikosR

**Comment by XhmikosR** [comment]
Thanks! I couldn't spot it for the life of me :/ Was it an issue due to ^
in penthouse dependency?

**Comment by bezoerb** [comment]
The last patch version bump of penthouse broke windows compatibility:
https://github.com/pocketjoso/penthouse/blob/0.9.11/lib/index.js#L56

**Comment by pocketjoso** [comment]
Fixed in [0.9.12](https://github.com/pocketjoso/penthouse/releases/tag/v0.9.12) - thanks @bezoerb !

**Comment by XhmikosR** [comment]
@pocketjoso: you should add AppVeyor to prevent Windows issues in the future.

**Comment by pocketjoso** [comment]
Will have a look at it, thanks @XhmikosR.
