### ISSUE TITLE
Fatal undefined

### ISSUE THREAD

**Issue by Milance1992** [addyosmani/critical#158]
I have some problems with critical, constantly throws errors "Fatal undefined".

![fatal](https://cloud.githubusercontent.com/assets/20242810/17360032/bf553e84-5969-11e6-9397-5039e88178f3.PNG)

My folder structure looks like this:
- critical
  - dist
    - done
    - index.html
    - main.css
  - node_modules
  - gulpfile.js
  - package.json

And my gulp task looks like this:

![capture](https://cloud.githubusercontent.com/assets/20242810/17360189/af66cfbe-596a-11e6-810d-a4226c60a819.PNG)

Can someone tell me what's the problem here?

**Comment by bikubi** [comment]
In a similar situation, I had the same error message; in my case `dist/main.css` was missing, resp. wasn't there yet.

**Comment by joshmoyers** [comment]
I have been getting the same issue as well. I have learned that I can do individual html files, but only if I reference that file directly (example: dist/index.html instead of dist/*.html or dist/**/*.html)

**Comment by ValentinBrclz** [comment]
I am getting the same error now... it would be great if this issue serves to improve the error reporting of the script.

**Comment by herrkessler** [comment]
same here

**Comment by bezoerb** [comment]
Thanks for the report and sorry for the late response ;)
I'll take a look

**Comment by bezoerb** [comment]
Did some debugging and it seems like one of the files are missing (for me it was the css).
```bash
[00:03:22] Starting 'critical'...
ENOENT: no such file or directory, open '.tmp/styles/main.css'
Fatal undefined
```
I'll add some error reporting tomorrow

**Comment by bezoerb** [comment]
```js
const critical = require('critical').stream;
const {log, colors} = require('gulp-util');

// Generate & Inline Critical-path CSS
gulp.task('critical', () =>
    gulp.src('dist/*.html')
        .pipe(critical({...}))
        .on('error', err => log(colors.red(err.message)) )
        .pipe(gulp.dest('dist'));
);
```

=>

```bash
[06:27:16] Starting 'critical'...
[06:27:16] ENOENT: no such file or directory, open '.tmp/styles/main.css'
```

**Comment by herrkessler** [comment]
```javascript
gulp.task('critical', function () {
    return gulp.src('dist/*.html')
        .pipe(critical({
            base: 'dist/', 
            inline: true, 
            minify: true, 
            pathPrefix: '/', 
            css: ['dist/css/app.css']
            }))
        .on('error', err => log(colors.red(err.message)) )
        .pipe(gulp.dest('dist'));
});
```
leads to:
```
[10:04:45] Penthouse timed out after 30s. 
```

**Comment by bezoerb** [comment]
Can you post your error messages? 
/cc @herrkessler @ValentinBrclz @Milance1992

**Comment by pocketjoso** [comment]
@herrkessler this is indeed an phantomjs issue, via [penthouse](https://github.com/pocketjoso/penthouse). If you post an issue there and find a way to share the css you're using with me (either link from PR), or send it in private message to me, then I can debug further.

**Comment by herrkessler** [comment]
@pocketjoso Thanks for you effort, I made it myself, changed some paths here and there, now it works.

**Comment by micahblu** [comment]
One of the biggest issues here is the silent fail. I use critical.stream and have also gotten the dreaded `fatal undefined`. I am able to retrieve the actual error by adding `console.log(err)` in `index.js` @ line `195` inside the if(err) condition. I woudl think the line above: `return cb(new PluginError('critical', err.message));` would console out the error but it does not. I think this may be an error with gulp itself. Regardless critical should fall back on `console.log` to ensure errors are properly displayed.

**Comment by bezoerb** [comment]
Closing this as nothing happened in the last 2 years. 

Feel free to reopen if the issue still exists.
