### ISSUE TITLE
Fatal undefined when dimensions is given

### ISSUE THREAD

**Issue by thany** [addyosmani/critical#165]
I get this error `Fatal undefined` when I supply it with any set of two dimensions.

```
gulp.task("critical", function() {
  return gulp.src("html-templates/homepage.html")
    .pipe(critical({
      css: [ "css/main.css" ],
      dimensions: [
        { width: 1900, height: 1200 },
        { width: 400, height: 750 }
      ]
    }))
    .pipe(gulp.dest("css/"));
});
```

If I comment out the dimensions property, it works like a charm.

So:
1) Can you fix this bug please?
2) Can you make it output errors that are "a little bit" more descriptive?

**Comment by bezoerb** [comment]
@thany you can log the errors using [`gulp-util`](https://github.com/gulpjs/gulp-util)
```js
const critical = require('critical').stream;
const {log, colors} = require('gulp-util');

// Generate & Inline Critical-path CSS
gulp.task('critical', () =>
    gulp.src('dist/*.html')
        .pipe(critical({...}))
        .on('error', err => log(colors.red(err.message)) )
        .pipe(gulp.dest('dist'));
);
```

=>

```bash
[06:27:16] Starting 'critical'...
[06:27:16] ENOENT: <errormessage>
```

Can you share the error message?

**Comment by thany** [comment]
Currently on a holiday, so I will when I return and have some time to get the project running again. Sorry for the delay.

**Comment by bezoerb** [comment]
@thany any updates? Does the error still exist?

**Comment by thany** [comment]
Sorry, the project this was for, had been discontinued. So I don't know if this issue is still on.
