### ISSUE TITLE
Writing the css rules in an area in a django template

### ISSUE THREAD

**Issue by bambamboole** [addyosmani/critical#167]
I'm building a django based project and using a base.html template file.

The main function of critical works like a charm. It extracts all used css rules out of the localhost:8000 dev server. Thumbs up for this!

But is it possible to write the extracted css rules into an extisting file for example in an placeholder or maybe inside an predefined `<style data-id="critical"></style>` tag, so that I don't have to copy the content in there by myself?

In my opinion, this would be a very useful enhancement of this nice tool.

cheers
bambamboole

**Comment by bezoerb** [comment]
@bambamboole have you tried the `inline: true` option?

[`inline-critical`](https://github.com/bezoerb/inline-critical#inlinehtml-styles-options) has a `target` option to specify a selector where the critical css gets prepended. So if the default inine settings in critical doesn't work out, you could use `inline-critical` yourself to do the inlining for you as long as your template is parsable by [`cheerio`](https://github.com/cheeriojs/cheerio)

**Comment by bezoerb** [comment]
Closing this as nothing happened in the last 2 years.
