### ISSUE TITLE
Critical and self-signed certificates

### ISSUE THREAD

**Issue by khalwat** [addyosmani/critical#171]
First, many thanks for critical -- I've been using it for years, and love it.

I've run into an issue recently where I have SSL enabled on local dev, which is also where I build the critical css using `gulp` and `critical`.  It took me a bit to figure out what was going on, because I'd run `critical` and no output at all would appear (no errors, no critical css written out).

It turns out that because the https certificate is self-signed, it's failing to render the page in PhantomJS.  I google'd a bit, and found that something such as this needs to be added:

     'phantomjs.cli.args': ['--ignore-ssl-errors=true',  '--web-security=false']

But is there a way to pass this down to phantomjs via critical?

**Comment by khalwat** [comment]
I found this in `penthouse/lib/index.js`:

```
// for phantomjs
var configString = '--config=' + path.join(__dirname, 'phantomjs', 'config.json')

```

But putting this `config.json` file in `penthouse/lib/phantomjs` didn't seem to work:

```
{
  "ignoreSslErrors": true,
  "webSecurity": false
}
```

**Comment by gmhenderson** [comment]
Here's the error I'm seeing (not sure if it's the same as you):

```
[10:30:31] Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
```

This is actually an error from [request](https://github.com/request/request). A quick and dirty hack is to replace line `85` of `file-helper.js` with:

```
request({url: uri, strictSSL: false}, function (err, resp) {
```

The `strictSSL` option needs to be set to false.

**Comment by khalwat** [comment]
I didn't see any errors output at all.  What I did for a temporary fix is to allow the website to run both http and https in local dev.

I'd ideally like to be able to pass params down to Penthouse/PhantomJS via Critical.  I can see it being useful for this, as well as other issues.

**Comment by spAnser** [comment]
I managed to fix this by putting this at the top of my javascript.

```javascript
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"
```

**Comment by bezoerb** [comment]
Thanks for reporting and sorry for the late response. We'll adding a fix for this in the next release.

**Comment by bezoerb** [comment]
[v1.0.0](https://github.com/addyosmani/critical/releases/tag/v1.0.0) Released.
