### ISSUE TITLE
When installing critical, it is trying to access port 9418

### ISSUE THREAD

**Issue by arminnaimi** [addyosmani/critical#176]
Hi there,

I have been running into issues with installing Critical. I have been able to install it successfully on my home broadband and I also noticed that the install is trying to access port 9418. On my work broadband, I don't have access to port 9418; but even after opening that port, the install failed with the following error: 

```
npm ERR! Command failed: git -c core.longpaths=true fetch -a origin
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=No error
npm ERR! github.com[1: 192.30.253.113]: errno=No error
```

I am trying to install it with node v6.9.1 and npm v3.10.8 on Windows 7.

Thanks.

**Comment by bezoerb** [comment]
Closing this as nothing happened in here for the last 2 years ;)

Feel free to reopen if the issue still exists.
