### ISSUE TITLE
dest option not working

### ISSUE THREAD

**Issue by Pustelto** [addyosmani/critical#177]
Hi,

I have an issue with critical plugin (I'm using it in gulp). I have this folder structure:
```
- app/
|_ dist/
|_ src/
gulpfile.babel.js
```

and this is my gulp task:

```
gulp.task('critical', () => (
  critical.generate({
    inline: true,
    base: 'dist/',
    src: 'index.html',
    dest: 'ic.html',
    minify: true,
    ignore: ['@font-face', 'font-family', /.*font-feature-settings/],
    dimensions: [
      {
        width: 1280,
        height: 1024,
      },
    ]
  })
));
```

According to doc, I would expect that it will take index.html from `dist/` folder and create `ic.html` in dist folder. However every time I run this task the `ic.html` is created in root `app/` folder. 

Am I doing something wrong?

Thanks for help.

**Comment by bezoerb** [comment]
@Pustelto: this is some misleading behavior. `src` is relative to base directory and `dest` is relative to current working dir. This should be unified in the master branch. For now you can either use `dest: 'dist/ic.html'` or use the `streams` method:
```js
gulp.task('critical', () => 
  gulp.src('dist/*.html')
    .pipe(critical({base: 'dist/', inline: true, ...]}))
    .pipe(gulp.dest('dist'));
);
```

**Comment by Pustelto** [comment]
Ok, thanks. I just wasn't sure if this is desired behavior or not, it wasn't clear from docsumentation.

**Comment by addyosmani** [comment]
Per @bezoerb this should be better handled in master today. 

(btw, @bezoerb just fixed tests and pushed a patch release. Going to try going through the PR backlog shortly)
