### ISSUE TITLE
pathPrefix get partially lost

### ISSUE THREAD

**Issue by emix7** [addyosmani/critical#179]
Hi,
It seems that path prefix get partially lost

pathPrefix: 'http://localhost/site.com/public/',

output in inline css:
url(http:/localhost/assets/fonts/Raleway.ttf) 

Any advice?
thanks

**Comment by bezoerb** [comment]
@emix7 can you share your configuration?

**Comment by emix7** [comment]
Hi Bezoerb,
thank you for replying and sorry my late reply

my config is:

// https://github.com/addyosmani/critical
gulp.task('critical', function(cb) {
    critical.generate({
        base: 'public/tmpl/common',
        src: 'http://localhost/site.com/public/',
       // css: ['public/css/main.css'],
     css: ['src/css/newstyle.css'],
        dimensions: [{
            width: 320,
            height: 480
        }, {
            width: 768,
            height: 1024
        }, {
            width: 1280,
            height: 960
        }],
       // dest: '_templates/critical_css_home.css',
       dest: 'critical_css_home.html',
        extract: false,
       inline:true,
          minify: false,
        pathPrefix: 'http://localhost/site.com/public/',
       // include: ['.c-slideshow, .c-more-to-see, .c-slideshow-gallery__container, .c-loader, .c-slideshow--hero'],
       // exclude: ['@font-face']
    });
});

and in the source .css I have things like:
@font-face {
  font-family: 'Jura';
  src: url(../assets/fonts/Jura.eot); /* IE9 Compat Modes */
  src: url('../assets/fonts/Jura.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('../assets/fonts/Jura.woff2') format('woff2'), /* Super Modern Browsers */
       url('../assets/fonts/Jura.woff') format('woff'), /* Pretty Modern Browsers */
       url('../assets/fonts/Jura.ttf')  format('truetype'), /* Safari, Android, iOS */
       url('../assets/fonts/Jura.svg#svgFontName') format('svg'); /* Legacy iOS */
}

thank you!

**Comment by HugoHeneault** [comment]
I have the same issue. :(

**Comment by bezoerb** [comment]
Closing this as nothing happened in the last 2 years. 

I think this should be way better with the next version. The prerelease can be installed with `npm i critical@next`. Asset paths can be configured with the `rebase` option 

Feel free to reopen if the issue still exists.
