### ISSUE TITLE
Parser doesn't work properly with Go templates

### ISSUE THREAD

**Issue by mkhazov** [addyosmani/critical#180]
After piping stream with html (which is actually a Go template) through `critical`

```html
<script src="{{ getPath "js/app.js" }} async"></script>
```
turns into
```html
<script src="{{ getPath " js="" app.js"="" }}"="" async></script>
```

Any idea how to avoid this?
I suppose, it's actually a cheerio-related issue, am I right?

**Comment by bezoerb** [comment]
@mkhazov I think you're right with the cheerio assumption. I think the only way to avoid this issue is to use critical to only generate the critical-path css and then do the inlining yourself.

**Comment by bezoerb** [comment]
I'm closing this issue for now. Feel free to open an issue in [`inline-critical`](https://github.com/bezoerb/inline-critical). Maybe we'll find another HTML parser which can handle this.
