### ISSUE TITLE
Add an option for penthouse renderWaitTime

### ISSUE THREAD

**Issue by micahblu** [addyosmani/critical#183]
The minimal wait time of 100ms is causing pages to fail by not allowing enough rendering time for pages with moderate to heavy resources, mostly being images.

**Comment by pocketjoso** [comment]
How do you know these resources have not loaded?

The page should already be fully loaded without any wait timing at all. I
meant to remove that timing value from Penthouse, but someone had a
specific use case for it.

**Comment by bezoerb** [comment]
Closing this as nothing happened in the last 2 years. 

I think this should be way better with the next version. The prerelease can be installed with `npm i critical@next`
All penthouse options can be passed through with the `penthouse` option
