### ISSUE TITLE
Fall back to console.log or equivalent to prevent silent fails

### ISSUE THREAD

**Issue by micahblu** [addyosmani/critical#184]
Mostly borrowed from a comment I made for: https://github.com/addyosmani/critical/issues/158

One of the biggest issues here is the silent fail. I use critical.stream and often get `fatal undefined`. I am able to retrieve the actual error by adding `console.log(err)` in index.js @ line 195 inside the if(err) condition. I would think the line above: `return cb(new PluginError('critical', err.message));` would console out the error but it does not. I think this may be an error with gulp itself. Regardless critical should fall back on console.log to ensure errors are properly displayed.

**Comment by bezoerb** [comment]
You can catch the errors in gulp itself by defining an error listener to the stream.
I've added the following to the Readme
```javascript
// Generate & Inline Critical-path CSS
gulp.task('critical', function () {
    return gulp.src('dist/*.html')
        .pipe(critical({base: 'dist/', inline: true, css: ['dist/styles/components.css','dist/styles/main.css']}))
        .on('error', function(err) { gutil.log(gutil.colors.red(err.message)); })
        .pipe(gulp.dest('dist'));
});
```

**Comment by micahblu** [comment]
Thanks @bezoerb
