### ISSUE TITLE
Issues when inline svg with no height is present

### ISSUE THREAD

**Issue by naps62** [addyosmani/critical#186]
Running `critical`, I noticed that only a subset of my CSS was being loaded. I tried to drill down the problem, and eventually noticed that the fault lied with an inline SVG I had on the page.
Anything in the markup that was **after** the svg would not be considered for the critical css (even though the SVG itself only occupies 40px of height)

Adding an explicity `height="40px"` attribute to the svg fixes the problem.

What's going on here, and is there anyway for me to fix it without having to add heights to my SVG's?

Here's a reproduceable version:

index.html:

```
<!DOCTYPE html>
<html>
<head>
	<noscript>
		<link href="/style.css" rel="stylesheet" type="text/css">
	</noscript>
</head>
<body>
	<div class="Before"></div>
	<svg></svg>
	<div class="After"></div>
</body>
</html>
```

style.css:

```
.Before,
.After{
  color: red;
}
```

Here's my output, while force a viewport size of 1920x1080:

```
$ node_modules/.bin/critical index.html --base . --width 1920 --height 1080
.Before {
  color: red;
}
```

And, after adding `height="10px" to the svg, the output is now fixed:

```
$ node_modules/.bin/critical index.html --base . --width 1920 --height 1080
.Before,
.After {
  color: red;
}
```

To double check, I changed the svg to have `height="1080px"`, which would have to force the `.After` class to be out of the viewport. And indeed, in that case, I go back to the first output, which is to be expected. It also proves that the svg with no height is indeed pushing the rest of the content down

**Comment by bezoerb** [comment]
According to the spec, an inline SVG is expanded to the full size of the viewport:
https://www.w3.org/TR/SVG/single-page.html#struct-SVGElementHeightAttribute

So even if some browsers will by default use 300x150 as the default size for an SVG, you can't rely on having this default. It seems phantomjs uses 100% height and is therefore pushing the `.After` element out of the way unless the size of the svg is limited somehow
