### ISSUE TITLE
Access html via http?

### ISSUE THREAD

**Issue by TJkrusinski** [addyosmani/critical#19]
Love this module, however a lot of sites are sourced from templates. This means an additional step of curl-ing the rendered html to disk and then using that as the source for the module. This creates some added complexity that would prevent a lot of folks from using it. Since `fs.readFile` is async anyhow, would you be open to allowing sourcing the html from the network as opposed to the disk? I can send in a PR if so.

**Comment by marcobiedermann** [comment]
I want to integrate critical on a node server which does not have any rendered html files. So +1 from my site for url / http access

**Comment by vdclouis** [comment]
+1

**Comment by relhtml** [comment]
+1 For this feature. 

From my understanding, in order to determine the Critical CSS from a series of partials, you would need some sort of headless browser (PhantomJS?) to render the page as a whole, then determine the "above-the-fold" content from there?

**Comment by danimalweb** [comment]
This is a great idea +1.

**Comment by marcustisater** [comment]
+1 would love to use this in a WordPress project.

**Comment by bezoerb** [comment]
Remote access is available in `master`.
See #94 for details.
Anyone else willing to test this?

**Comment by bezoerb** [comment]
Closing this as the requested feature is released in (v0.7.0)[https://github.com/addyosmani/critical/releases/tag/v0.7.0]
