### ISSUE TITLE
using regex in the "include" options behaves differently in stream mode

### ISSUE THREAD

**Issue by fBosch** [addyosmani/critical#192]
I tried using the recommended way of integrating `critical` in my gulpfile. 

However i noticed that the css generated, using the `stream()` method, was different than when using the `generate()` method with the same options passed. 

To me it looks like the regex's passed are not respected in the stream method; since the generated css file only contains the style definitions of the classes themselves, and not the child-elements (using BEM) that the given regex suggests.

Example:
``` javascript
/// Custom fix
gulp.task('critical', () => {
    return streamFromPromise(critical.generate({
            base: '.tmp/',
            src: `views/default/index.html`,
            css: [`.tmp/styles/default.css`],
            dimensions: [{
                width: 320,
                height: 480
            }, {
                width: 768,
                height: 1024
            }, {
                width: 1280,
                height: 960
            }, {
                width: 1920,
                height: 1080
            }],
            dest: `styles/default.critical.css`,
            minify: true,
            extract: false,
            ignore: ['@font-face',/url\(/],
            include: [
                /^\.main-navigation.*$/,
                /^\.hero-deck.*$/,
                /^\.deck.*$/,
                /^\.search-box.*$/
            ]
        })
    )}
)
```
which generates a 62KB `default.critical.css` 

and 
``` javascript 
// Suggested implementation
gulp.task('critical', () => {
    return gulp.src('.tmp/views/default/index.html')
        .pipe(critical.stream({
            base: '.tmp/',
            css: [`.tmp/styles/default.css`],
            dimensions: [{
                width: 320,
                height: 480
            }, {
                width: 768,
                height: 1024
            }, {
                width: 1280,
                height: 960
            }, {
                width: 1920,
                height: 1080
            }],
            minify: true,
            extract: false,
            ignore: ['@font-face',/url\(/],
            include: [
                /^\.main-navigation.*$/,
                /^\.hero-deck.*$/,
                /^\.deck.*$/,
                /^\.search-box.*$/
            ]
        }))
        .pipe($.rename(`default.critical.css`))
        .pipe(gulp.dest(`.tmp/styles`))
})
```
which in turn; generates a 6KB `default.critical.css`

**Comment by bezoerb** [comment]
@fBosch: Thanks for reporting this. After adding test cases for [`generate`](https://github.com/addyosmani/critical/commit/cc12aeb57100cee0c074899cfb9726c56be54bba#diff-ef333539a2bb6bc510efb240e0aad8b0) and [`stream`](https://github.com/addyosmani/critical/commit/cc12aeb57100cee0c074899cfb9726c56be54bba#diff-ec31ed5a6f4343f9d9ca3e30d94dfee6) i found an issue caused by a configuration change introduced in `clean-css@v4.0.0`.

Would you mind checking your setup again with the critical [v0.8.3](https://github.com/addyosmani/critical/releases/tag/v0.8.3)?

**Comment by fBosch** [comment]
I'm still having issues with inconsistent file sizes.

I don't, however, think it has anything to do with differences between stream and generate method any longer.

I've noticed that if i'm doing something computationally intensive, while generating the styles; I tend to get a larger file size. Could some timeout have anything to do with it?

**Comment by fBosch** [comment]
I think I've found out why now... I deferred loading of styles while generating the critical path css, don't do that.
