### ISSUE TITLE
The include option does not work for me

### ISSUE THREAD

**Issue by libertarismus** [addyosmani/critical#193]
I am trying to include the following css in the critical path that is removed by critical from the main css file:
`.articles` `article:nth-of-type(4n){margin-right:0}`

I have attached the following files:
main.css This is the css file with all rules
critical.css This is the css file critical writes
[css.zip](https://github.com/addyosmani/critical/files/784764/css.zip)

I use the following grunt configuration:
``
critical: {
      options: {
      base: '<%= app.dist %>',
        extract: true,
        minify: true,
        width: 1920,
        height: 1080,
      },
      mytest:{
        base: './dist/',
        src:'./dist/index.html',
        dest: './dist/critical.css',
        minify: false,
        inline: false,
        include: [/\.articles.*/,'.articles article:nth-of-type(4n)','.articles article:nth-of-type(4n){margin-right:0}',/.articles.*/,/articles.*/,'articles','.articles'],}}
``
As you can see I have just added aditional rules to include in the hopes that one would work 
but alas the css rule never makes it into the critical path.

**Comment by pocketjoso** [comment]
@libertarismus One potential reasons for these issues could be if your css contains errors. This can throw off the CSS parser (of [Penthouse](https://github.com/pocketjoso/penthouse), which is responsible for generating the critical css). Are you linting your CSS at all?

**Comment by libertarismus** [comment]
@pocketjoso  I have linted my sass files now and only got warnings using scss-lint and afterwards linted my css files using csslint and got one error.

The error was removed when i switched the outputstyle of sass from compressed to expanded so I have only warnings now and mostly unimportant stuff about the alphabetical order of attributes.

The problem with critical persists though.

**Comment by bezoerb** [comment]
Closing this as nothing happened in the last 2 years. 
Feel free to reopen if the issue still exists.
