### ISSUE TITLE
Unable to generate for local rails page

### ISSUE THREAD

**Issue by richhollis** [addyosmani/critical#194]
Hi team!

I'm trying to use the CLI to generate the critical CSS path, for some (local) rails dev server pages.

e.g.

node cli.js http://localhost:3000/somepage -H test.html

But it's erroring on the stylesheet link tags:

Error: ENOENT: no such file or directory, open 'assets/bootstrap.self-c1f14ba6ea9628826b54b8954dbad7ce4df47e14cac7298fb42c9a081300cfd5.css'

Here is the link tag from the source html:

    <link rel="stylesheet" media="all" href="/assets/bootstrap.self-c1f14ba6ea9628826b54b8954dbad7ce4df47e14cac7298fb42c9a081300cfd5.css?body=1" />

If I manually edit the file and add the host part (e.g. http://localhost:3000) to all link tags and run critical then then works. 

How can I get critical to use the correct host path in this instance? I've tried some of the options but nothing seems to work.

Many thanks
Rich

**Comment by richhollis** [comment]
Later raised #195 is the same problem I have. I will close this issue as #195 has been assigned bug status.

**Comment by bezoerb** [comment]
@richhollis: would you mind testing the `development` branch?
See: https://github.com/addyosmani/critical/pull/198

**Comment by richhollis** [comment]
@bezoerb Sure. Just tested it here - looks good. Generating now for location urls. Thanks!
