### ISSUE TITLE
Using a remote url doesn't seem to work

### ISSUE THREAD

**Issue by pajtai** [addyosmani/critical#195]
`Critical v0.8.3`

From this issue: https://github.com/addyosmani/critical/issues/94 it is my understanding that the `src` option can be a remote url, and critical will crawl the assets to produce the optimized end result.

It seems like absolute links are not fetched remotely but looked for locally. Is this a configuration issues on my end or a bug?

**Example:**

```javascript
'use strict';

const critical = require('critical');

critical.generate({
    minify: true,
    src: 'https://jekyllrb.com/',
    dest: '.tmp/index-critical.html'
});
```

**Generates the following error:**

```
Unhandled rejection Error: ENOENT: no such file or directory, open 'css/screen.css'
    at Error (native)
```

**Due to this line in the `head` of jekyllrb.com:**
```html
<link rel="stylesheet" href="/css/screen.css">
```

**Comment by pajtai** [comment]
Maybe the absolute link's are not being flagged as external due to the [`isExternal` method](https://github.com/addyosmani/critical/blob/master/lib/file-helper.js#L103).

**Comment by pajtai** [comment]
I solved it with a test modification of my node_modules with a pretty ugly hack. If src is external than I passed a flag from [`core.appendStylesheets`](https://github.com/addyosmani/critical/blob/master/lib/core.js#L93) to [`file.resourcePath`](https://github.com/addyosmani/critical/blob/master/lib/file-helper.js#L205) indicating that `file.resourcePath` should return the "base url" concated with the absolute url.

Maybe including an `opts.baseUrl` could force all stylesheet links to be pulled in remotely, or there could be some other config to help indicate that you want all resources pulled in remotely? Assuming there might be some other places this affects things like absolute img urls, etc.

**Comment by pajtai** [comment]
@bezoerb Gave solving this a go with this PR:
https://github.com/addyosmani/critical/pull/196

It prepends the base url - calculated from `opts.src` to any absolute urls in the styles.

**Comment by pajtai** [comment]
Sent a pr https://github.com/addyosmani/critical/pull/197 that simply checks if `opts.src` is remote, and if it is, it assumes all stylesheets should be remote.

**Comment by pajtai** [comment]
Confirmed fixed on `Critical v0.8.4`

**Comment by nealoke** [comment]
@pajtai any documentation on how to actually use this for `localhost`? I tried lots of configs but still can't get it to work. Thanks!

**Comment by pajtai** [comment]
What are you using for `opt.src`? I'm assuming you can just use something that starts with `http://`.

**Comment by nealoke** [comment]
Below is my current config which doesn't throw any error however does not get the critical css. Thanks for looking into it!

Note that my gulpfile is in a sibling folder of the application, hence the `../app/styles/...`

```
{
	inline: false,
	pathPrefix: 'http://localhost/nest',
	base: 'app/',
	css: '../app/styles/global.css',
	dimensions: [
		{
	        width: 320,
	        height: 650
	    },
	    {
	        width: 1200,
	        height: 900
	    }
	],
	ignore: [/url\(/, '@font-face'],
	include: ['.popup']
}
```
