### ISSUE TITLE
Using Critical + Express + Pug (and Gulp) ?

### ISSUE THREAD

**Issue by valeriosillari** [addyosmani/critical#199]
Not sure if I am out of topic, but I have new to Critical and I have a question ...

I have a small web application set with Express + Pug + gulp.
Everything looks fine, but now I want to add Critical.

The documentation of the plugin it is very simple.
I have already set a dummy page with static html as in the examples.
But they are always talking about plain HMTL files/page, NOT about markup files created by dynamically with express or with languages as Pug.

So my question is:

How can try to use Critical with Pug (or any other markup language as .ejs) in Express ?
I mean: I need to take a page created in pug, parse the "final" html and css, using critical to set new inline code and then inject again into pug file.

Anyone have already face/solve this problem?

or am I going on a wrong way?

Please if anyone has tips let me know

**Comment by bezoerb** [comment]
@valeriosillari critical doesn't support template-engines. This would be way ahead of scope for this plugin. You'll have to do it just like you explained ;)

> I need to take a page created in pug, parse the "final" html and css, using critical to set new inline code and then inject again into pug file.

See https://github.com/addyosmani/critical/issues/94 for further information.
