### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by JakeHenshall** [addyosmani/critical#202]
Hi,

I've used this plugin with gulp before, it is possible to use with web pack 2?

Thanks Jake.

**Comment by laurenskling** [comment]
I get `Error: Cannot find module "."` importing `critical` in a webpack2 build. :(

**Comment by Jacfem** [comment]
Not sure if you're still curious about it, but I'm currently trying to integrate with this plugin that's a webpack wrapper around critical: https://github.com/nrwl/webpack-plugin-critical

**Comment by neoswf** [comment]
we are using it in our project, together with a `on-build-webpack` plugin. After build has finished, inside the callback we call `CriticalCSS.generate(...)`

**Comment by NikolaySolodukhin** [comment]
neoswf, could show example of you config please?
