### ISSUE TITLE
Config for multiple pages?

### ISSUE THREAD

**Issue by strarsis** [addyosmani/critical#205]
Is there an example for how to use critical with multiple pages / srcs?
Do I have to duplicate the whole config for each page? Can I simplify this when using gulp?
The srcs are all **remote URLs** to dynamically generated pages (CMS on dev server).

**Comment by computapars** [comment]
I've been using a recursive function to go through an array of pages on my local development environemnt. Not sure if this helps.
`
var config = {
    url_base: 'http://' + host + ':' + port,
    critical_path: "/path/to/output_css_file/",
    root_path : path.join(__dirname, '/../')
}

/* Add Critical Points to this Array for CriticalCSS creation */
var critical_points = [
	{
		url: config.url_base,
		name: 'homepage'
	},
	{
		url: config.url_base + "/otherpage",
		name: 'other-page'
	},
	{
		url: config.url_base + "/otherotherpage",
		name: 'other-other-page'
	},
]

/* For each critical point:
 * - create a critical css file in the
 * - output a success message
 * - give plenty of time for local servers to run through each of the items.
 */

function callCriticalRecursive(entries){
	var entry_point = entries.shift();

	critical.generate({
    	base: config.root_path,
    	src: entry_point.url,
    	dest: path.join(config.root_path, config.critical_path, entry_point.name + '.css'),
    	minify: false,
    	timeout: 60000,
    	ignore: ['@font-face', /url\(/]
	}, function (err, output) {
		if (err){
			console.log("Error with the following critical file " + entry_point.name);
			console.log(err.cause)
		}
		else {
			console.log("Finished critical detection of " + entry_point.name);
		}
		// continue to go through array of points
		if (entries.length > 0){
			callCriticalRecursive(entries);
		}
	});
}

callCriticalRecursive(critical_points)

`

**Comment by rowbot-weisguy** [comment]
Hi @strarsis I've been trying to figure out the same thing this week.

Here's what I've got in my `gulpfile.babel.js`. 

```
gulp.task('critical', () => {
  gulp.src(['./build/**/*.html'])
    .pipe(critical({
      base: config.html.dest,
      inline: true,
      width: 320,
      height: 480,
      minify: true,
      timeout: 60000
    }))
    .on('error', (err) => { gutil.log(gutil.colors.red(err.message)); })
    .pipe(gulp.dest(config.html.dest));
});
```

It's not working as I'd like it. It always times out under this configuration. In the site I'm working on, I'm looping through ~100 pages, and I have to set the timeout to an incredibly high number to make it work. I'm considering doing something like @computapars shared now, where I manually specify critical paths from which to generate the CSS, and then inline that into every page. 

Let me know if you learn anything... 🤔

**Comment by bezoerb** [comment]
closing this in favor of #320
