### ISSUE TITLE
Do styles for elements that are inserted by javascript get detected by critical.js?

### ISSUE THREAD

**Issue by computapars** [addyosmani/critical#206]
I have various components that are above the fold that are inserted via javascript on page load. Does PhantomJS or Penthouse see these items?  Every time I run critical on these pages, I don't see any of the styles inlined so I'm assuming that Phantom Js does not run with javascript enabled or does not detect html that is added via javascript after the page is loaded.

**Comment by pocketjoso** [comment]
Penthouse has `blockJSRequests:true` as a default, so thats' what you're seeing. Critical css is used for the first render _before_ Javascript has even been requested, so styles for elements inserted via javascript should not be included in the critical css. By the time the page loads your full CSS should already be loaded, and will hence provide the style for such elements.
