### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by mciastek** [addyosmani/critical#208]
I use `critical` as gulp task. When I use it locally it works fine. Then I deploy my code via Travis CI and during building I get:
```
{ [Error: Unexpected end of JSON input]
  message: 'Unexpected end of JSON input',
  showStack: false,
  showProperties: true,
  plugin: 'critical',
  __safety: { toString: [Function: bound ] } }
```
I think it's related to https://github.com/pocketjoso/penthouse/issues/148. Locally I have PhantomJS in version `2.0`, on Travis there is `2.1.1`. Which means that I need to set custom options for Penthouse and PhantomJS used by it, but for now it's not possible due to https://github.com/addyosmani/critical/pull/178 not merged.

**Comment by arminnaimi** [comment]
I can confirm that the same issue happens on GitLab CI.

**Comment by pocketjoso** [comment]
My only hunch about these errors are that they could be related to the blocking `fs.read/writeFileSync` calls currently inside `Penthouse`; that phantomjs somehow doesn't handle that well. I haven't had time to try this hypothesis though.

**Comment by bezoerb** [comment]
Closing this as nothing happened in the last 2 years. 

I think this should be way better with the next version. The prerelease can be installed with `npm i critical@next`

Feel free to reopen if the issue still exists.
