### ISSUE TITLE
Preload pollyfill

### ISSUE THREAD

**Issue by retyui** [addyosmani/critical#210]
Im use custom preload pollyfill.
Please add option ignore insert script Preload pollyfill!

**Comment by bezoerb** [comment]
You can pass `inline: false` as an option to critical

**Comment by retyui** [comment]
Yes you are right ,
Only I need, that in the mode `inline: true` it would be possible to exclude the addition of an inline polyfill script ` rel="preload" `
So I'm trying to reduce the size of my <head> in the processed files!

**Comment by bezoerb** [comment]
@retyui: This should be addressed [here](https://github.com/bezoerb/inline-critical). Unfortunately i don't have much time to work on this right now but you're welcome to add a PR to `inline-critical`
