### ISSUE TITLE
Remote URL doesn't work

### ISSUE THREAD

**Issue by davidhellmann** [addyosmani/critical#211]
Hey, 

strange problem here. When I use the local url like website.dev all is fine. 
When I use the remote url: website.com the task run and he generate all the temp files but not the css files. 

Interesting part here is that the local tmp files are much longer as the remote tmp files.

Any Ideas?

**Comment by davidhellmann** [comment]
Looks like some dependencies faults. 
In old projects all fine but when I delete the node_modules folder and do a yarn install it's broken. 

meeeeeeeeeh :D

**Comment by davidhellmann** [comment]
```
const criticalDest = element.template + '_critical.min.css'
```

when I change the line above to this it works

```
const criticalDest = config.dist.markup + element.template + '_critical.min.css'
```

Looks like base doesn't work?
```
base: config.dist.markup,
```

**Comment by bezoerb** [comment]
Hey @davidhellmann,
sorry for the late response. Can you provide some more insights on your problem?
I'm currently not quite sure how to help you as your last comment indicates that the issue might be in your setup and not in critical itself.

**Comment by bezoerb** [comment]
Closing this due to lack of feedback.
Feel free to re-open if the error still exists. 

Maybe try the latest version of critical first ;)
