### ISSUE TITLE
Simple test with Gulp not outputting critical CSS

### ISSUE THREAD

**Issue by rmckeel** [addyosmani/critical#212]
Hello,

My tests worked on a complex example using `critical` command line, so I started to integrate with Gulp and automated builds.  Everything _runs_ fine, however it spits out less than desired critical CSS for the complex case.  So, I boiled it down to a simple case:

gulpfile.js
```
var gulp     = require( 'gulp' );
var critical = require( 'critical' );
gulp.task( 'critical-login', function () {
  critical.generate({
    inline: true,
    base: 'app/public',
    src: 'test.html',
    dest: 'test-critical.html'
  });
```

test.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" src="test.css" />
</head>
<body>
<div id="mydiv">
    pink stuff
</div>
</body>
</html>
```

test.css
```
body {
    color: blue;
}
#mydiv {
    color: pink;
}
```

Output:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">

    </style>
    <link rel="preload" src="test.css" as="style" onload="this.rel='stylesheet'">
    <noscript><link rel="stylesheet" src="test.css"></noscript>
    <script>!function(e)..........</script>
</head>
<body>
<div id="mydiv">
    pink stuff
</div>
</body>
</html>
```

In this incredibly simple example, I should have both CSS styles included, however I have none.  Clearly, the index.html file was retrieved and output properly.  So am I missing something?

I would normally file this sort of thing on StackOverflow, however since the command line worked for me and the Gulp integration did not (had much less output, and in some cases like the simple case, no CSS output), it smelled more like a bug than a misconfiguration on my part.

Thanks for any ideas!

P.S. relevant package.json dependencies:
    "critical": "^0.8.4",
    "gulp": "^3.9.1",
    "gulp-dest": "^0.2.3",
    "gulp-download": "0.0.1",
    "gulp-util": "^3.0.8"

**Comment by bezoerb** [comment]
@rmckeel: Thanks for detailed issue report. I'll take a look this evening

**Comment by bezoerb** [comment]
@rmckeel: sorry for the delay. You should use the `href` attribute on your link tag as the `src`attribute is not supported here ;) (See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link)
I've checked your example with the correct html and everything works fine as expected.

**Comment by rmckeel** [comment]
@bezoerb Good catch, perhaps my [Rubber Ducky](https://en.wikipedia.org/wiki/Rubber_duck_debugging) should have caught that one.

However, the problem remains after I re-run, I now get this output.  Should not #mydiv be part of the critical CSS running under near-default conditions?  It is the only element, and is visible at top left of the page.  Even explicitly setting width: 1300 and height: 900 does not change the output.  Only `body { color: blue }`.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
        body {
          color: blue;
        }

    </style>
    <link rel="preload" href="http://localhost/nv/app/test.css" as="style" onload="this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="http://localhost/nv/app/test.css"></noscript>
    <script>!function(e){"use strict";var t=function(t,n,r){function o(e){return i.body?e():void setTimeout(function(){o(e)})}function a(){d.addEventListener&&d.removeEventListener("load",a),d.media=r||"all"}var l,i=e.document,d=i.createElement("link");if(n)l=n;else{var s=(i.body||i.getElementsByTagName("head")[0]).childNodes;l=s[s.length-1]}var u=i.styleSheets;d.rel="stylesheet",d.href=t,d.media="only x",o(function(){l.parentNode.insertBefore(d,n?l:l.nextSibling)});var f=function(e){for(var t=d.href,n=u.length;n--;)if(u[n].href===t)return e();setTimeout(function(){f(e)})};return d.addEventListener&&d.addEventListener("load",a),d.onloadcssdefined=f,f(a),d};"undefined"!=typeof exports?exports.loadCSS=t:e.loadCSS=t}("undefined"!=typeof global?global:this),function(e){if(e.loadCSS){var t=loadCSS.relpreload={};if(t.support=function(){try{return e.document.createElement("link").relList.supports("preload")}catch(e){return!1}},t.poly=function(){for(var t=e.document.getElementsByTagName("link"),n=0;n<t.length;n++){var r=t[n];"preload"===r.rel&&"style"===r.getAttribute("as")&&(e.loadCSS(r.href,r,r.getAttribute("media")),r.rel=null)}},!t.support()){t.poly();var n=e.setInterval(t.poly,300);e.addEventListener&&e.addEventListener("load",function(){t.poly(),e.clearInterval(n)}),e.attachEvent&&e.attachEvent("onload",function(){e.clearInterval(n)})}}}(this);</script>
</head>
<body>
<div id="mydiv">
    pink stuff
</div>
</body>
</html>
```

**Comment by bezoerb** [comment]
@rmckeel: Sorry for the late response. 
I've just ran the test twice using `critical.generate` as well as `critical.stream` and everytime i ended up with the expected result:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
        body {
          color: blue;
        }

        #mydiv {
          color: pink;
        }

    </style>
    <link rel="preload" href="test.css" as="style" onload="this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="test.css"></noscript>
    <script>!function(e){"use strict";var t=function(t,n,r){function o(e){if(i.body)return e();setTimeout(function(){o(e)})}function a(){d.addEventListener&&d.removeEventListener("load",a),d.media=r||"all"}var l,i=e.document,d=i.createElement("link");if(n)l=n;else{var s=(i.body||i.getElementsByTagName("head")[0]).childNodes;l=s[s.length-1]}var u=i.styleSheets;d.rel="stylesheet",d.href=t,d.media="only x",o(function(){l.parentNode.insertBefore(d,n?l:l.nextSibling)});var f=function(e){for(var t=d.href,n=u.length;n--;)if(u[n].href===t)return e();setTimeout(function(){f(e)})};return d.addEventListener&&d.addEventListener("load",a),d.onloadcssdefined=f,f(a),d};"undefined"!=typeof exports?exports.loadCSS=t:e.loadCSS=t}("undefined"!=typeof global?global:this),function(e){if(e.loadCSS){var t=loadCSS.relpreload={};if(t.support=function(){try{return e.document.createElement("link").relList.supports("preload")}catch(e){return!1}},t.poly=function(){for(var t=e.document.getElementsByTagName("link"),n=0;n<t.length;n++){var r=t[n];"preload"===r.rel&&"style"===r.getAttribute("as")&&(e.loadCSS(r.href,r,r.getAttribute("media")),r.rel=null)}},!t.support()){t.poly();var n=e.setInterval(t.poly,300);e.addEventListener&&e.addEventListener("load",function(){t.poly(),e.clearInterval(n)}),e.attachEvent&&e.attachEvent("onload",function(){e.clearInterval(n)})}}}(this);</script>
</head>
<body>
<div id="mydiv">
    pink stuff
</div>
</body>
</html>
```

**Comment by rtkd** [comment]
Hi, i'm running into the same difficulties.

node: v8.5.0
critical: "^0.9.1"
gulp: "^3.9.0"

test.html
`
<!DOCTYPE html>
<html lang="de">
	<head>
		<meta charset="utf-8">
		<title>Index</title>
	</head>
	<body>
		<header id="header-main">test</header>
	</body>
</html>
`
test.css
`
body {
	background: #f00; }

#header-main {
	color: #0f0; }
`
critical test.css
`
body {
  background: red;
}
`

I fed sources before and after minification to same avail.

**Comment by rmckeel** [comment]
@rtkd Thanks for adding your example also. @bezoerb Would you be up for mimicking @rtkd setup and see if you can replicate the problem?

**Comment by rtkd** [comment]
I've set up a more sane env for testing: Node: 6.11.4, NPM: 5.4.2, Gulp: 3.9.1, Critical: 0.9.1
Issue persists. Also, when I explicitly include the element 'include'	: ['#header-main'] everything is fine.

**Comment by RobertJGabriel** [comment]
Sorry for being annoying, any update on this :) Same issue

**Comment by bezoerb** [comment]
Could you please check the current master branch of critical to see if the error still exists after switching to headless chrome?
/cc @RobertJGabriel @rtkd @rmckeel

**Comment by RobertJGabriel** [comment]
@bezoerb just tired again with the lastest and still the same issue :(

**Comment by midzer** [comment]
After updating npm packages yesterday I discovered not all critical CSS being extracted any more.
Updating to current master didn't solve it, too.

**Comment by bezoerb** [comment]
@RobertJGabriel, @midzer: I'm still not able to reproduce the issue. 

What about using the [`stream`](https://github.com/addyosmani/critical#gulp) method? Does this produce the same output?

**Comment by midzer** [comment]
@bezoerb I'm using `stream` call anyway. Here's my gulp task https://github.com/midzer/eisolzried/blob/master/_tasks/critical.js

**Comment by teodragovic** [comment]
Hi, I think I have the same problem. Only output I got is styles for `<html>` and `<body>` elements and `@font-face` rules.

Here is my reduced example (I'm using Windows 8, Node 6, npm 5):

html:
```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Title</title>
    <link rel="stylesheet" href="/main.css">
</head>
<body>
<div class="bg--purple-dark">
    <h1 class="txt--white">Title</h1>
</div>
</body>
</html>
```

css:
```
body { background: red; }

.bg--purple-dark { background: rebeccapurple; }

h1 { font-weight: bold; }

.text--white { color: white; }
```

gulp:
```
gulp.task( 'critical:css', () =>
    gulp.src( `${config.outputDir}/**/*.html` )
    .pipe( critical.stream({
        base : `${config.outputDir}/`,
        css : [ `${config.outputDir}/main.css` ],
    }) )
    .on( 'error', err => console.error( err ) )
    .pipe( gulp.dest( config.outputDir ) )
);
```

I also tried using CLI command `critical build/index.html --base build > critical.css` and output is the same. Per recommendations in Penthouse repo I checked my styles in AST explorer and used their online tool and output was as expected. This error started when I upgraded to v1.0.0., before it worked fine so I'm thinking it has something to do with Chrome Headless not being supported on Windows but same thing happens when I deploy.

**Comment by pocketjoso** [comment]
@teodragovic this was due to an [upstream issue in Puppeteer](https://github.com/GoogleChrome/puppeteer/issues/1506) - but I just published a new penthouse version (1.1.4) that downgrades puppeteer to avoid this issue. Please reset your penthouse module (how depends on your package manager, but you can f.e. uninstall `critical` and install it again) - and re-test - should work again.

**Comment by rmckeel** [comment]
@pocketjoso Thanks for finding & fixing the issue.  When I'm back on the original task, I'll try it again!

**Comment by pocketjoso** [comment]
I should have been more clear: the issue I'm referring to have only been there the last few days, so if you had an issue from before then it's unfortunately likely to still be there after this. Do try it though as you never now.

**Comment by teodragovic** [comment]
@pocketjoso yup, that solves it for me. Thank for such a quick response!

**Comment by einsteinreloaded** [comment]
I am facing similar type of issue but in my case when i run the critical.generate again it outputs the correct css.

**Comment by kamleshchandnani** [comment]
I'm still facing the same issue where few elements are above the fold but critical doesn't inlines them in my head tag.
