### ISSUE TITLE
Not generating loadCSS polyfill on inline:true

### ISSUE THREAD

**Issue by KhodorAmmar** [addyosmani/critical#214]
The code doesn't generate the loadcss polyfill inside the document, instead it's outputting a `<script>undefined</script>`

**Comment by bezoerb** [comment]
@KhodorAmmar: Could you give some more insights or a testcase to reproduce the error?

**Comment by bezoerb** [comment]
Closing this du to lack of feedback.
Feel free to re-open if there are any further questions
