### ISSUE TITLE
Failed to inline when there is no link, style or script tag.

### ISSUE THREAD

**Issue by josenobile** [addyosmani/critical#217]
When the HTML provided has not link, style or script tag it fails to inline the CSS. 
When there is not link, style or script tag, just insert it before closing head tag `</head>`
Reported here https://github.com/bezoerb/inline-critical/issues/227 too

**Comment by bezoerb** [comment]
@josenobile: Thanks for reporting this. I've already self-assigned the reported issue at inline-critical and i hope that i'll find some time over the weekend to address this.

**Comment by bezoerb** [comment]
Closing this as it should be fixed in `inline-critical`
