### ISSUE TITLE
Fetching from localhost

### ISSUE THREAD

**Issue by donoskaro** [addyosmani/critical#226]
Hi,

I have tried generating critical CSS however it fails due to pages being in subdirectories. Naturally my solution was to create a local server (using the nano-static-server package) which would allow me to specify the CSS files absolutely and resolve the issue of subdirectories.

However when I specify the base option as "http://localhost:8888/", I get the following error:
`Error creating critical CSS: Error: ENOENT: no such file or directory, open 'http:/localhost:8888/`. The missing forward slash after `http:/` is leading me to believe that either I am incorrectly configuring this or that this is currently not supported by critical.

I would really appreciate any feedback on this.

Regards.

**Comment by donoskaro** [comment]
I have managed to solve this, for anyone with the same issue you have to specify something for the base path (I specified `http://localhost:8888`) as well as pass the absolute path to the src option (i.e. `http://localhost:888/some-page').

**Comment by bezoerb** [comment]
I think there's some space for improvement ;)

**Comment by bezoerb** [comment]
I'll keep this open so we don't forget this one

**Comment by bezoerb** [comment]
Think this should be way better with the next version (check with `npm i critical@next`)
