### ISSUE TITLE
Finding css file issue with subfolders

### ISSUE THREAD

**Issue by bajras** [addyosmani/critical#230]
My project lives under subfolder `/nailba/appreciation/` 
config is:
```javascript 
base: path.resolve(__dirname, './../dist/nailba/appreciation'),
src: 'index.html',
dest: 'index.html'
```
I get the following error:
`Fatal Error: ENOENT: no such file or directory, open 'dist/nailba/appreciation/nailba/appreciation/static/css/app.20a8c875cb801af30e6c44a1821d6815.css'`

and the CSS in the index file is:
`<link href=/nailba/appreciation/static/css/app.20a8c875cb801af30e6c44a1821d6815.css>`

I can see that it is getting inside the index.html file but looks its not resolving the CSS url

**Comment by midzer** [comment]
@bajras Try to specify your .css file path directly via criticalCSS `css` config parameter

**Comment by bezoerb** [comment]
@bajras: `base` should reference your docroot. As your project is inside the folder `/nailba/appreciation/` you should set `base` to `path.resolve(__dirname, './../dist`

**Comment by bajras** [comment]
@midzer The CSS file name is hashed by Webpack so they dont remain the same after builds.
@bezoerb I tried that too and when I do that it cant find the index file. 
After the HtmlWebpackPlugin has been ran the folder structure looks like this for dist folder:

├── dist/
│   ├── nailba                 
│       ├── appreciation                 
│            └── index.html
│            └── static
│                    └── css
│                    └── js

The url path in the index file is correct but and critical is going inside index.html too and finds the css url but searches for 'dist/nailba/appreciation/nailba/appreciation/static/css/app.20a8c875cb801af30e6c44a1821d6815.css'

**Comment by bajras** [comment]
this work as @midzer mentioned as I can't figure why the base options isnt working.

```javascipt
src: path.resolve(__dirname, '../dist/nailba/appreciation/index.html'),
dest: path.resolve(__dirname, '../dist/nailba/appreciation/index.html'),
css: path.resolve(__dirname, '../dist/nailba/appreciation/static/css/app.css')
```

But I want to hash the css and use that instead of app.css all the time but when I try to use contenthash it doesnt work? Any Idea?

```javascript
new ExtractTextPlugin({
  filename: utils.assetsPath('css/[name].[contenthash].css')
}),
new HtmlCriticalPlugin({
  css: path.resolve(__dirname, '../dist/nailba/appreciation/static/css/[name].[contenthash].css')
})
```

I want to use the same [name].[contenthash] for two plugins, is that even doable? Thanks.

**Comment by smartinkth** [comment]
Did you find a solution to this @bajras ?
