### ISSUE TITLE
 [CRITICAL] QNetworkReplyImpl: backend error: caching was enabled after some bytes had been written

### ISSUE THREAD

**Issue by josenobile** [addyosmani/critical#232]
When I use Critical, I receive this intermitent error:
 [CRITICAL] QNetworkReplyImpl: backend error: caching was enabled after some bytes had been written

Critical is affected by https://github.com/ariya/phantomjs/issues/13165#issuecomment-322019503

The Phantomjs bug has a workaround consistent of enabling disk cache. I suggest when calling Penthouse pass the [--disk-cache=true](http://phantomjs.org/api/command-line.html) option to phantomjs using [phantomJsOptions](https://github.com/pocketjoso/penthouse/blame/master/README.md#L60) option.

**Comment by XhmikosR** [comment]
We don't use phantomjs anymore so this is fixed.
