### ISSUE TITLE
Incorrect handling of quotes in attributes

### ISSUE THREAD

**Issue by beingmrkenny** [addyosmani/critical#237]
Seems like quotes around attributes are being normalised. This is causing problems when using single quotes:

`<div data-test='"test informaiton"'>`

becomes

`<div data-test="" test="" informaiton""="">`

**Comment by bezoerb** [comment]
This is related to [`cheerio`](https://github.com/cheeriojs/cheerio).
Opened an issue over at [`inline-critical`](https://github.com/bezoerb/inline-critical/issues/228)
