### ISSUE TITLE
Issues with relative image paths

### ISSUE THREAD

**Issue by micahblu** [addyosmani/critical#24]
Relative image paths seem to also be an issue via declared CSS `background` and `background-image` properties which unchanged become invalid resources. I was able to get around this via a quick regex replace which, got rid of relative path references `../`. Not sure though if this works for all use cases and haven't thoroughly tested it.

**Comment by bezoerb** [comment]
This should be fixed by now. Feel free to re-open if there are still issues we did not consider yet.
