### ISSUE TITLE
CLI issue with some https sites: Error opening url: connection closed OR SSL handhsake failed

### ISSUE THREAD

**Issue by mikeytown2** [addyosmani/critical#240]
I can get the command line version of critical to work with certain sites but not others.

Broken: 

    critical https://www.drupal.org/
    critical https://groups.drupal.org/

Working:

    critical https://www.webpagetest.org/
    critical https://github.com/
    critical https://www.npmjs.com/

Related issues:
https://github.com/ariya/phantomjs/issues/12440
https://stackoverflow.com/questions/24473169/phantomjs-certain-pages-failing-to-open

I need to use phantomjs with the `--ssl-protocol=any` flag but I don't see a way to configure this when using the command line (global) version of critical.

**Comment by mikeytown2** [comment]
This looks like the cause 

> TLS 1.0 and 1.1 deprecated
> Drupal.org uses the Fastly CDN service for content delivery, and Fastly has depreciated support for TLS 1.1, 1.0, and 3DES on the cert we use for Drupal.org, per the mandate by the PCI Security Standards Council.

https://www.drupal.org/drupalorg/blog/whats-new-on-drupalorg-august-2017

**Comment by rjh427** [comment]
Just stumbled into this issue myself, after attempting to use a test suite on a new site. I've seen much written about passing arguments to phantomjs on the command line, that doesn't help me much because  this suite is invoked programatically in a PHP environment. I'm using self-signed certs in my dev environment too, but it's also an issue on the production site with CA-issued certs as well. Is there a fix?

**Comment by pocketjoso** [comment]
Just FYI: Once a PR for #229 lands these problems should all go away.

**Comment by rjh427** [comment]
:+1:

**Comment by Grawl** [comment]
@mikeytown2 How do you run like `critical https://github.com/`? I get an error: `"file" argument must be a non-empty string`

**Comment by mikeytown2** [comment]
@Grawl I installed critical like this
yarn global add https://github.com/addyosmani/critical.git#headless-chrome

**Comment by bezoerb** [comment]
@mikeytown2: we just released [v1.0.0](https://github.com/addyosmani/critical/releases/tag/v1.0.0). Would you mind to check again with the new version?

**Comment by developer-lindner** [comment]
@mikeytown2 

inside your script use: 
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

before using critical.generate()
