### ISSUE TITLE
ignore options doesn't work

### ISSUE THREAD

**Issue by developer-lindner** [addyosmani/critical#241]
Hey there!

Just playing around with critical css and i can't exclude things like:
ignore: ['@font-face', 'content', 'font-family', 'clearfix']

What's wrong here?

**Comment by developer-lindner** [comment]
Nevermind... got it!

ignore: ['@font-face', 'content', 'font-family', 'clearfix'],
ignoreOptions: {
        matchSelectors: true,
    	matchTypes: true,
    	matchDeclarationProperties: false,
    	matchDeclarationValues: false,
    	matchMedia: false
}

**Comment by XhmikosR** [comment]
@bezoerb: this should be documented if it's intended, otherwise it's a bug in filter-css.

The README there states:

>Per default filter-css will be applied to all parts of the CSS. This behavior can be customized by disabling specific matchers

If we have to specify explicitly

```js
ignoreOptions: {
  matchSelectors: true,
  matchTypes: true,
  matchDeclarationProperties: false,
  matchDeclarationValues: false,
  matchMedia: false
}
```

then something seems wrong :/
