### ISSUE TITLE
Empty User agent blocked

### ISSUE THREAD

**Issue by nico-martin** [addyosmani/critical#243]
Hi there

For security reasons we are blocking some user agents via .htaccess. There we also check if the user agent is empty, which caused some troubles with critical.
Going through the log files it seems like critical makes two requests per dimension. The first one has no user agent and the second one has the user agent defined for `penthouse`.
In our scenario the first request gets blocked because the .htaccess only finds an empty user agent.
I guess this first request collects all css from the given url, am I right?

Would it be possible to add a user agent to **both** requests?

Thanks!

**Comment by bezoerb** [comment]
user agent passed as option should already be considered for every request by now
