### ISSUE TITLE
Don't reject other 200 series response codes

### ISSUE THREAD

**Issue by ethanhinson** [addyosmani/critical#244]
When resources return something besides 200 (even another 2XX response) Critical rejects the request here: https://github.com/addyosmani/critical/blob/07be40bab23eb518bb689062b43f0db507c9a1f9/lib/file-helper.js#L145

We have a use case with CDN delivered assets that can return a `203` response. I believe Critical should be allowing any 200 series response.

**Comment by bezoerb** [comment]
@ethanhinson Thanks for reporting this. We'll change this in the next release.

**Comment by ethanhinson** [comment]
Thanks for following up, and for the great tool! We're using it on ~25 or so production sites.

**Comment by bezoerb** [comment]
Fixed in https://github.com/addyosmani/critical/commit/5b451dd4078bf529ac1b6aea9cc66e74205e46e1

**Comment by bezoerb** [comment]
[v1.0.0](https://github.com/addyosmani/critical/releases/tag/v1.0.0) Released :)

**Comment by ethanhinson** [comment]
Thank you!
