### ISSUE TITLE
Warning: Missing html source path. Consider 'folder' option. https://goo.gl/PwvFVb

### ISSUE THREAD

**Issue by stereobooster** [addyosmani/critical#245]
documentation doesn't say anything about `folder`

**Comment by bezoerb** [comment]
@stereobooster Thanks for reporting :)
I've added the `folder`option to the readme https://github.com/addyosmani/critical/commit/3da6fe9359589acf86cbee17ee5d8a8e7c0b099b

**Comment by halafi** [comment]
still missing from README, would reopen

**Comment by bezoerb** [comment]
@halafi: this option was removed in [v2.0.0](https://github.com/addyosmani/critical/releases/tag/v2.0.0)

Do you have any issues leading to this?

**Comment by halafi** [comment]
issue is I am using v1 lol, thanks
