### ISSUE TITLE
Is it a problem if almost ALL of my CSS is inlined as critical?

### ISSUE THREAD

**Issue by rfgamaral** [addyosmani/critical#250]
I have a very simple homepage (https://ricardoamaral.net/) and when I use this tool to extract the critical-path CSS, almost everything is extracted. I'm just wondering if this is a problem or if it's fine?

Also, as a follow up question, should I even worry this much with critical-path CSS on a very simple/basic homepage like this?

**Comment by pocketjoso** [comment]
As long as your site (and css) is going to stay this size, you can just inline the full css and not worry.

**Comment by rfgamaral** [comment]
> As long as your site (and css) is going to stay this size, you can just inline the full css and not worry.

You're saying to just inline everything? In that case, wouldn't be simpler for me to just use some Gulp  plugin for inlining a CSS file instead of using Critical?

**Comment by pocketjoso** [comment]
Yep probably.

**Comment by rfgamaral** [comment]
Thanks.
