### ISSUE TITLE
Gulp with critical v1.0

### ISSUE THREAD

**Issue by maseyuk** [addyosmani/critical#254]
Im just trying to setup gulp with critical. I've tried using the gulp code from here:
https://github.com/addyosmani/critical

But im getting "TypeError: critical is not a function"

Is the gulp setup now out of date with 1.0?

**Comment by bezoerb** [comment]
@maseyuk: The gulp setup should work the same way as with v0.9
Did you try this code https://github.com/addyosmani/critical#gulp?

**Comment by XhmikosR** [comment]
Works fine for me here.
