### ISSUE TITLE
CSS ordering / duplication

### ISSUE THREAD

**Issue by BB-000** [addyosmani/critical#256]
Here is a simple example of the issue

My main stylesheet, main.css includes this style near the top ( from a reset.css )

h1 { margin: 0.67em 0 }

Then this is overwritten by my styles, near the bottom of main.css

h1, h2, .h3, ul, p {
  margin: 0 0 0.9em;
}

The output in criticalcss file is like this, and causes my style to get overwritten

h1 {
  margin: 0.67em 0px;
  margin: 0.67em 0;
}
//....
h1,h2,.h3,ul,p {
  margin: 0px 0px 0.9em;
}
//...
h1 {
  margin: 0.67em 0;
}

I currently have been building my critical css from a stylesheet that has this style removed, is there a better solution available for this?

**Comment by pocketjoso** [comment]
@BB-000 It's possible that the issue comes direct from [Penthouse](https://github.com/pocketjoso/penthouse), the underlying critical css generating library. Would it be possible for you to retry using that library directly, and if you can reproduce the bug, raise an issue there instead/as well?

**Comment by BB-000** [comment]
I tested using Penthouse web service on the same page/stylesheet and the style was included correctly once. I am using filamentgroups grunt criticalcss https://github.com/filamentgroup/criticalCSS, I'll post an issue there

**Comment by XhmikosR** [comment]
I guess this is sorted.
