### ISSUE TITLE
Empty href in link throws cryptic error

### ISSUE THREAD

**Issue by Saturate** [addyosmani/critical#258]
The following link tag in HTML
`<link href="" media="all" rel="stylesheet">`

Will give an error saying:
`Unhandled rejection Error: EISDIR: illegal operation on a directory, read`

This can be quite cryptic, as this was a series of bugs that I encountered, both with the href not getting rendered and then with the strange error from critical.

I makes sense as it tries to open a dir, and it can't in this instance, but I feel that it could be handled a little better.

Node: `8.5.0`
Critical: `1.0.0`

**Comment by bezoerb** [comment]
Thanks for reporting @Saturate. We should definitely improve the error reporting

**Comment by chromadesign** [comment]
I am getting this rather cryptic error as well and can't find what the problem (it's not an empty href). I've tried different source URLs (local and remote) as well as different destination directories to no avail. Any idea how I can get to the bottom of this?

Fancy Log spits out the following error message after the task finishes:
 Error: EISDIR: illegal operation on a directory, read errno: -4068, code: 'EISDIR', syscall: 'read' }

**Comment by bezoerb** [comment]
Can you try the prerelease version of critical: `npm i critical@next`
We improved file handling & error reporting in this release.

**Comment by XhmikosR** [comment]
Closing as fixed.
