### ISSUE TITLE
Ignore class-selector plus child elements

### ISSUE THREAD

**Issue by developer-lindner** [addyosmani/critical#260]
I don't get it... could someone please enlighten me how to ignore certain class-selectors?!

**Comment by bezoerb** [comment]
@developer-lindner: You can use the `ignore` option like this:
```js
critical.generate({
  base: '...',
  src: '...',
  ignore: [/selector-regex/],
}
```

https://github.com/addyosmani/critical/blob/2f332dc8986e31b820b33f2e2cd98b4816b3d81a/test/02-generate.js#L514

**Comment by developer-lindner** [comment]
@bezoerb Thank you! But i've tried that already... class-selectors didn't work at all?!
Looks broken to me...

**Comment by bezoerb** [comment]
@developer-lindner thanks. I’ll look into it later today

**Comment by bezoerb** [comment]
@developer-lindner i just ran some tests and all worked as expected. What exactly do you want to achieve? Maybe there's a misunderstanding ;)

You can either _ignore_ css classes with the aim to keep them out of your critical css (this is what the ignore option in critical is for).
```js
critical.generate({
  base: '...',
  src: '...',
  ignore: [/selector-regex/],
}```
Or you want to _include_  the classes in your critical css even if they won't affect your critical rendering path. (for this one you need to pass the `forceInclude` option down to penthouse.

```js
critical.generate({
  base: '...',
  src: '...',
  penthouse: {forceInclude: [/selector-regex/]},
}
```

i just tested both versions and the result was as expected every time.

**Comment by developer-lindner** [comment]
I use include too for some non-visible stuff but the ignore option didn't work as expected for class-selectors. Just tried it again and now it did work?! I don't get it... thanks for taking time!
