### ISSUE TITLE
converts float?!

### ISSUE THREAD

**Issue by developer-lindner** [addyosmani/critical#261]
After extraction:
margin-bottom: 10,6066px; ?
font-size: 0,75rem; ?

Anyway to solve this easily?

**Comment by pocketjoso** [comment]
Converts from what to what exactly?

Might be because of Penthouse normalisation of your original css, if so this will be fixed (in Penthouse) sometime this week when this pr is merged: https://github.com/pocketjoso/penthouse/pull/209.

**Comment by developer-lindner** [comment]
Ya must be the normalization... should be font-size: 0.75rem; for example.
Hopefully the PR will soon be available! Thank you!
