### ISSUE TITLE
UnhandledPromiseRejectionWarning if Chrome can't be started

### ISSUE THREAD

**Issue by thewilkybarkid** [addyosmani/critical#263]
We were missing some system packages to be able to run Chrome, this lead to an `UnhandledPromiseRejectionWarning` and a 0 exit code (through Gulp).

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
[..]/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
```

**Comment by bezoerb** [comment]
We recently used this inside docker and we had to add a bunch of system packages to get headless chrome running.
* gconf-service
* libasound2 
* libatk1.0-0 
* libc6 
* libcairo2 
* libcups2 
* libdbus-1-3 
* libexpat1 
* libfontconfig1 
* libgcc1
* libgconf-2-4
* libgdk-pixbuf2.0-0
* libglib2.0-0
* libgtk-3-0
* libnspr4
* libpango-1.0-0
* libpangocairo-1.0-0
* libstdc++6
* libx11-6
* libx11-xcb1
* libxcb1
* libxcomposite1
* libxcursor1
* libxdamage1
* libxext6
* libxfixes3
* libxi6
* libxrandr2
* libxrender1
* libxss1
* libxtst6
* ca-certificates
* fonts-liberation
* libappindicator1
* libnss3
* lsb-release
* xdg-utils
* wget

After adding all those packages we were able to run headless chrome. 
See: https://github.com/Interlutions/docker-node/blob/master/Dockerfile

**Comment by pocketjoso** [comment]
Yeah this comes from puppeteer. So far penthouse only mentions it in the readme here:
https://github.com/pocketjoso/penthouse#not-working-on-linux

Feel free to open a PR to expand on that section in the readme (in Penthouse).

**Comment by teodragovic** [comment]
I'm not sure if I have same problem but I started getting this in my console when deploying (locally everything works and on server worked last friday dec. 8th):

```
[08:20:15] Starting 'critical:css'...
(node:14320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Page crashed!
(node:14320) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:14320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Page crashed!
(node:14320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Page crashed!
(node:14320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Page crashed!
{ [Error: undefinedundefinedError: Penthouse timed out after 30s. ]
  message: 'undefinedundefinedError: Penthouse timed out after 30s. ',
  showStack: false,
  showProperties: true,
  plugin: 'critical',
  __safety: { toString: [Function: bound ] } }
```
the `Page crashed` part got me thinking that it's not Chrome starting problem but something else with dependencies that's changed.

**Comment by thewilkybarkid** [comment]
Yeah, we had a separate bug that didn’t install all the packages. The problem here is the 0 exit code, as it didn’t cause our build to fail and created problems further down the line.

**Comment by hendrikeng** [comment]
@teodragovic did u solve the issue? i am running into the same problem.
following the steps didn't help https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

it all works lokal but not on the server

**Comment by hamedbaatour** [comment]
guys facing this issue on windows please **disable your antimalware / antiviruse** because it will kill the headless chrome process that puppeteer launches thinking its a dangerous sniffing process!
