### ISSUE TITLE
IE11 crashes due to cycling loading of css file

### ISSUE THREAD

**Issue by rokerkony** [addyosmani/critical#264]
Hi,
after upgrading critical from 0.9.1 to 1.1.0 is our angular 4 app failing due to the loading of the css file.

After first fetch of css file it loads that css and fonts (which are in the css file) all the time again and again until IE11 stops to be responsive anymore.

this is a list of requests from `http-server`:
```bash
[... 13:36:07 ...] "GET /" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:07 ...] "GET /inline.75e8870fba00c34a8a9e.bundle.js" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:07 ...] "GET /polyfills.16485738055aa9bd40b0.bundle.js" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:07 ...] "GET /scripts.5d01c0346c9e1aeba3f9.bundle.js" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:07 ...] "GET /main.34326e006e60e0462b5c.bundle.js" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:08 ...] "GET /styles.533a3b0559146cf11ddf.bundle.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:08 ...] "GET /lineto-brown-regular.aa679f9d3dd07c2053bd.eot?" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:08 ...] "GET /lineto-brown-bold.599a0123420af98d9e31.eot?" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:09 ...] "GET /styles.533a3b0559146cf11ddf.bundle.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:09 ...] "GET /lineto-brown-regular.aa679f9d3dd07c2053bd.eot?" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:09 ...] "GET /lineto-brown-bold.599a0123420af98d9e31.eot?" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:09 ...] "GET /styles.533a3b0559146cf11ddf.bundle.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:09 ...] "GET /lineto-brown-regular.aa679f9d3dd07c2053bd.eot?" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:09 ...] "GET /styles.533a3b0559146cf11ddf.bundle.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:09 ...] "GET /lineto-brown-regular.aa679f9d3dd07c2053bd.eot?" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:09 ...] "GET /styles.533a3b0559146cf11ddf.bundle.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:09 ...] "GET /lineto-brown-regular.aa679f9d3dd07c2053bd.eot?" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:09 ...] "GET /styles.533a3b0559146cf11ddf.bundle.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:09 ...] "GET /lineto-brown-regular.aa679f9d3dd07c2053bd.eot?" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:09 ...] "GET /lineto-brown-bold.599a0123420af98d9e31.eot?" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:09 ...] "GET /styles.533a3b0559146cf11ddf.bundle.css" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
[... 13:36:09 ...] "GET /lineto-brown-regular.aa679f9d3dd07c2053bd.eot?" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
...
```

After some investigation, I found out that a polyfill for a plugin `loadCSS` (dependency of `inline-critical`) changed - it dropped the `loadCSS` method.

When I put back the old polyfill it works.

I truly don't know if this is a good place to report this bug, if not give me a hint.

**Comment by XhmikosR** [comment]
@bezoerb: perhaps you need to set the `onload` handler to `null` like they recommend upstream?

https://github.com/bezoerb/inline-critical/blob/master/index.js#L148

>We also recommend nulling the onload handler once it is used, since some browsers will occasionally re-call the handler upon switching the rel attribute to stylesheet:

```html
<link rel="preload" href="path/to/mystylesheet.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="path/to/mystylesheet.css"></noscript>
```

**Comment by rokerkony** [comment]
it was my first try and unfortunately, it didn't help

the only solution which helped till now is to put back polyfill from this commit:
https://github.com/bezoerb/inline-critical/commit/5317ba2f55a31e56b38d83a22a3cf9e8b7a241f4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by XhmikosR** [comment]
So, you say that v2.0.0 works and v2.0.1 causes the issue? If that's the case, I guess you should report the issue to https://github.com/filamentgroup/loadCSS

**Comment by XhmikosR** [comment]
Regardless, I still think, @bezoerb should set the onload event to null per the upstream README.

**Comment by rokerkony** [comment]
@XhmikosR sorry I was not precise... I used just a polyfill used in tests from this PR

and what I read is, that 2.0.0 is deprecated as it was published incorrectly that is probably why is this PR with 2.0.1

**Comment by XhmikosR** [comment]
I confirm that the issue indeed exists. I might try to pinpoint the issue when I have some time unless someone else beats me to it.

**Comment by bezoerb** [comment]
Thanks @XhmikosR, @rokerkony. I‘ll publish a patch to inline-critical later today.

**Comment by XhmikosR** [comment]
I believe the issue is what I said above @bezoerb. I just tested IE 10 with `his.onload=null;` like the upstream docs and works fine. So we definitely need this.

I made https://github.com/bezoerb/inline-critical/pull/231

**Comment by bezoerb** [comment]
https://github.com/bezoerb/inline-critical/releases/tag/v3.1.0

**Comment by XhmikosR** [comment]
Confirmed, works fine. You can close this issue.

**Comment by rokerkony** [comment]
thanks guys for an effort and a fix, but it is still failing on IE11...
should I create another issue on loadCSS and close this one or how to proceed?

**Comment by XhmikosR** [comment]
Delete your local node modules folder and package lock and install
everything again.

It's definitely fixed but I guess Ben could release a new patch critical
version to circumvent your issue which others will have too.

**Comment by rokerkony** [comment]
I just did but it is still failing. `this.onload=null` is now applied but still loads css again and again... are you testing on IE11 as well?

**Comment by XhmikosR** [comment]
I tested on IE 10 which had the problem and the fix fixed it for me. I will
try IE 11 in a few minutes but my guess is it will work there too.

On Dec 15, 2017 12:20, "Konrad Černý" <notifications@github.com> wrote:

I just did but it is still failing. this.onload=null is now applied but
still loads css again and again... are you testing on IE11 as well?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/addyosmani/critical/issues/264#issuecomment-351968948>,
or mute the thread

**Comment by XhmikosR** [comment]
Yup, works fine for me, the issue is fixed as expected from my initial testing too.

If you have any more issues you should report them upstream since now the code is the recommended one. Just don't forget to post an issue to the repo that needs any updates if something is changed upstream.

**Comment by rokerkony** [comment]
ok, thx for testing...

maybe it is influenced by an angular app... I will try to test it on minimal code and then compare with our app if it works... if not I will try to investigate directly in `loadCSS` repo

we can close this issue here for now, right?

**Comment by 0reo27** [comment]
Got the same issue. Bumped the version of inline-critical. Working great now. I just tested on IE11. I guess we just need to wait for the author to bump the version?

**Comment by XhmikosR** [comment]
Until a new patch release of critical is out, you can just do the following:

```
rm -rf ./node_modules/ ./package-lock.json
npm i
```

@bezoerb: please release a new patch version where you explicitly bump inline-critical to the latest version.

**Comment by rokerkony** [comment]
Hey guys, would you be so kind and could anyone try this?
https://github.com/rokerkony/angular-critical-ie11-bug

This is a minimal angular app generated by CLI with critical on top of it, just run `npm run serveDist` after cloning the repo and it will install deps, build, apply critical and run http-server.

This is still failing for me ... If you confirm I will probably open an issue in the angular repo.

**Comment by XhmikosR** [comment]
While I'm on Windows and your test repo is probably from macOS (so I had to make a couple of changes), I tried it with msys2. I can reproduce your issue there with IE10, but I don't see how it's related to critical, when it happens if I remove your postbuild script which actually runs critical.

**Comment by rokerkony** [comment]
ok... I think it is caused by Zone.js which is monkey patching a `load` event...

after I have commented out all occurrences of `'load'` (4 occurrences) events it works ...

closing this issue and going to open one there...

**Comment by 0reo27** [comment]
Just wanted to chime in again. Simply did a yarn remove critical -D, yarn add critical -D and it's working without any additional configuration.

@rokerkony, thanks for reporting the bug and thanks to @XhmikosR and @bezoerb for sorting it out. Critical is an awesome tool for sure! :)
