### ISSUE TITLE
Because of JS frame,the first screen can not be rendered successly 

### ISSUE THREAD

**Issue by princewn** [addyosmani/critical#269]
hi~
If the contents of the first screen are depend on the rendering of JS framework,the first screen can not be rendered successfully.
May I ask if it is my problem or the plugin do not support JS frame rendering?

**Comment by princewn** [comment]
If the plugin do not support JS frame rendering,do you have a plan to do this and when?

**Comment by bezoerb** [comment]
Sorry for the very late response. 
This has already been answered here https://github.com/addyosmani/critical/issues/273#issuecomment-356915103 and here https://github.com/addyosmani/critical/issues/319#issuecomment-414607799
