### ISSUE TITLE
1.*.* breaks gulp task

### ISSUE THREAD

**Issue by lewisnyman** [addyosmani/critical#271]
Since upgrading to 1.0.0+ I've encountered fails that I'm finding really hard to debug.

Node 6.4.0

Task

```
gulp.task('critical', ['generate-site'], function (cb) {
  return gulp.src('destination/**/*.html')
  .pipe(critical({
      base: 'destination/',
      css: ['destination/css/style.css'],
      inline: true,
      dimensions: [{
        width: 320,
        height: 480
      },{
        width: 768,
        height: 1024
      }]
  }))
  .on('error', function(err) { gutil.log(gutil.colors.red(err.message)); })
  .pipe(gulp.dest('destination'));
});
```

Error message:

```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
```

**Comment by jdrzj** [comment]
Hi, I got the same error when running critical.
I got node 7.3.0, gulp 3.9.1.

**Comment by jdrzj** [comment]
I tried to rollback to version 0.9.1 with:
`$ npm install critical@0.9.1 --save`
but I got the error message:
```
[10:08:59] Using gulpfile ~/code/landing-pages/gulpfile.js
[10:08:59] Starting 'critical'...
Fatal undefined
```

**Comment by jdrzj** [comment]
But running it from CLI works.

**Comment by bezoerb** [comment]
Got the same error errors in my [`bump-dependencies`](https://github.com/addyosmani/critical/tree/bump-dependencies) branch 
https://travis-ci.org/addyosmani/critical/builds/319980576

**Comment by fjorgemota** [comment]
I'm having the same problem here.

However, instead of just showing ERESET from times to times...I'm having the following error shown randomly - too:

```[00:30:38] Protocol error (Runtime.callFunctionOn): Execution context was destroyed. undefined
[00:30:38] no writecb in Transform class```

Curiously, this only happens when using `public/**/*.html` as the `src` to the gulp task. When using just `public/*.html` all runs fine.

**Comment by pocketjoso** [comment]
> [00:30:38] Protocol error (Runtime.callFunctionOn): Execution context was destroyed. undefined

This error is tracked in Penthouse and a fix for it is coming:
https://github.com/pocketjoso/penthouse/issues/202#issuecomment-361909817

It happens when the page the critical css generation is working on issues a redirect to another page (~~ window.url = something else).

**Comment by fjorgemota** [comment]
Oh. Nice!

Now it makes sense the fact that sometimes `ERESET` error is shown, sometimes that error is shown.

I will try today to execute spawn a new instance of `critical` for each HTML file found, to see if most files are, at least, processed (trying to avoid those who redirect to another pages).

Anyway, thanks for the answer. =)

**Comment by mohitsinghs** [comment]
@fjorgemota You can fix these errors for now by downgrading `ws@3.3.3` to `ws@3.3.2` . [see my comment](https://github.com/addyosmani/critical/issues/181#issuecomment-357414945)

**Comment by begincalendar** [comment]
Is anyone able to consistently reproduce this issue?

It occurs sporadically for me and hence is infeasible to debug.

**Comment by shiftie** [comment]
Hi, I can't use critical on Travis & it also fails in local as well with:
```
read ECONNRESET
    at _errnoException (util.js:1022:11)
```
any updates concerning this?

**Comment by XhmikosR** [comment]
This should have been fixed a long time ago.
