### ISSUE TITLE
Duplication of css rules

### ISSUE THREAD

**Issue by Fenrirkp** [addyosmani/critical#272]
Source HTML:

> <header>
	<div class="menu">
		<div class="menu-toggle">
		</div>
		<div class="menu-list">
			<a href="#">String1</a>
			<a href="#">String2</a>
			<a href="#">String3</a>
			<a href="#">String4</a>
			<a href="#">String5</a>
		</div>
	</div>
	<div class="section">Some content...</div>
</header>
Source CSS-file:

> <section>
	.menu {
		position: fixed;
		top: 0;
		left: 0;
		width: 100%;
		height: 50px;
	}
	.menu-toggle {
		position: absolute;
		right: 0;
		display: none;
		width: 50px;
		height: 100%;
		cursor: pointer;
		background: #0a0;
	}
	.menu-list {
		height: 100%;
		text-align: center;
		background: #fa0;
	}
	.section {
		background-image: url(../img/bg.jpg);
	}
	@media screen and (max-width:639px) {
		.menu-toggle {
			display: block;
		}
		.menu-list {
			display: none;
		}
	}
</section>
Inlined CSS;

> <section>
	.menu {
		position: fixed;
		top: 0;
		left: 0;
		width: 100%;
		height: 50px
	}
	.menu-toggle {
		position: absolute;
		right: 0;
		display: none;
		width: 50px;
		height: 100%;
		background: #0a0
	}
	.menu-list {
		height: 100%;
		text-align: center;
		background: #fa0
	}
	.section {
		background-image: url(img/bg.jpg)
	}
	@media screen and (max-width:639px) {
		.menu-toggle {
			display: block
		}
		.menu-list {
			display: none
		}
	}
</section>
Output CSS-file:

> <section>
	.menu-toggle {
		position: absolute;
		right: 0;
		display: none;
		width: 50px;
		height: 100%;
		cursor: pointer;
		background: #0a0;
	}
	.section {
		background-image: url(../img/bg.jpg);
	}
</section>
Why not:

> <section>
	.menu-toggle {
		cursor: pointer;
	}
</section>

**Comment by Fenrirkp** [comment]
My gulp-task:

> <section>
	gulp.task('critical', function () {
		return gulp.src('app/*.html')
		.pipe(critical({
			base: 'app/',
			inline: true,
			width: 600,
			height: 1080,
			extract: true
		}))
		.pipe(gulp.dest('app/'));
	});
</section>

**Comment by bezoerb** [comment]
The extraction is done by the [`cave`](https://github.com/bevacqua/cave) module.
I've proposed a [PR](https://github.com/bevacqua/cave/pull/5) to some time ago. Until this is landed we can't do much about this.

**Comment by pocketjoso** [comment]
And just a friendly reminder from me that removing "duplicated" rules from the original css is bad practice, as you no longer have a shared full stylesheet that the browser will cache and that will be re-used on later page loads.

**Comment by bezoerb** [comment]
Thanks @pocketjoso :)
https://github.com/addyosmani/critical#options

> Use with caution. Removing the critical CSS per page results in a unique async loaded CSS file for every page. Meaning you can't rely on cache across multiple pages

**Comment by Fenrirkp** [comment]
That's ok. I have only one page.

**Comment by bezoerb** [comment]
@Fenrirkp: Sorry for the very late response. As of critical 2.x we have replaced cave with [`postcss-discard`](https://github.com/bezoerb/postcss-discard) which also removes duplicate rules. 
I'm closing this as it shouldn't be an issue anymore with critical 2.x. Feel free to reopen if it doesn't work as expected.
