### ISSUE TITLE
Use in react app

### ISSUE THREAD

**Issue by NikolaySolodukhin** [addyosmani/critical#273]
Can I use critical in react app?

**Comment by pocketjoso** [comment]
If your server side render it, yes.

**Comment by developer-lindner** [comment]
It works even without server side rendering...

**Comment by pocketjoso** [comment]
> It works even without server side rendering...

**No.**
Even though critical might run without throwing any errors, and even return you a critical css - it is not of any use without (some kind of) server side rendering.

Critical css is used to enable browsers to render your website _before_ it has loaded CSS + JS, based purely on the initial HTML (i.e. what your server returns) and the critical css. If your HTML is empty, the first render with critical css will be blank, hence no better than not using critical css at all.

Google's PageSpeed Insights has in my view been a big culprit on why people have false conceptions about critical css, as it always just measured signals and never real performance (read more f.e. [here](https://www.absentdata.com/blog/google-page-speed-insights-accurate/), and would hence give thumbs up to things like non server side rendered react + critical css usage _despite it making no difference for performance_. With the [recent update](https://developers.googleblog.com/2018/01/real-world-data-in-pagespeed-insights.html), even  PSI should show now more clearly show you the lack of benefits of this use.

You don't have to do a perfect SSR, but if do do none, your performance efforts are better spent on something other than critical css.

I'm trying to be helpful here so if there's any confusion about what I've written, please tell me! I might write up a blog post about this.

**Comment by bezoerb** [comment]
Closing this because the question is perfectly answered. Thanks @pocketjoso.

**Comment by nimaa77** [comment]
> If you server side render it, yes.

@developer-lindner HOW?
it's impossible with to do it with [afterjs](https://github.com/jaredpalmer/after.js/) ([razzle](https://github.com/jaredpalmer/razzle)) or nextjs.
