### ISSUE TITLE
Replace deprecated dependency gulp-util

### ISSUE THREAD

**Issue by phil-r** [addyosmani/critical#274]
[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been deprecated recently. Continuing to use this dependency may prevent the use of your library with the recently released version 4 of Gulp, **it is important to replace `gulp-util`**.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is popular but still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

**Comment by bezoerb** [comment]
Done in https://github.com/addyosmani/critical/releases/tag/v1.1.1
