### ISSUE TITLE
Double quotes within single quoted attributes cause invalid output

### ISSUE THREAD

**Issue by davidmurdoch** [addyosmani/critical#275]
Swapping `'` for `"` in something like `<a title='My Title Here'></a>` isn't usually a problem, however, it is valid HTML to have something like `<a title='Read more "Double Quotes around me"'></a>`.

Critical does something strange in these cases (even with `minify: false`). It'll take the above HTML and output:

`<a title="Read more " double="" quotes="" around="" me=""=""></a>`

Which obviously isn't right.

Additionally, and likely related, if the input HTML is:

`<a href=/link></a>` I expect the HTML output to be exactly `<a href=/link></a>`. critical is currently adding in double quotes around all attributes values, i.e., `<a href="/link"></a>`.

My options are: `{inline: true, minify: false}`

Let me know if you need anything else.

**Comment by brezanac** [comment]
Confirmed. It's especially problematic with data attributes containing values like JSON etc.

```
<div data-something='{ "key" : value }'></div>
```
becomes
```
<div data-something="{ " key"="" :="" value="" }"=""></div>
```

**Comment by bezoerb** [comment]
This behavior is caused by [`cheerio#720`](https://github.com/cheeriojs/cheerio/issues/720) which is used under the hood by `inline-critical` to inline the critical css.

**Comment by sergeiliski** [comment]
This is still open and I was wondering if there was a solution to this? As far as I know, it's not possible to pass the `decodeEntities: false` that is suggested in the [cheerio#720](https://github.com/cheeriojs/cheerio/issues/720)

**Comment by bezoerb** [comment]
@sergeiliski: Can you check if your issue still exists with the prerelease version of critical `npm i critical@next`?

We have replaced `cheerio` with `jsdom` in [`inline-critical`](https://github.com/bezoerb/inline-critical) and we're only using it for the `<head>` section of the html. So as long as you only have double quotes within single quotes in your `<body>` everything should be fine.

**Comment by nairod** [comment]
I faced this problem too, with the stable version. With the next version this problem has gone. 
Thanks for your work!

**Comment by NivedhaKumaran** [comment]
@nairod From which version this problem has gone ?
Can you please mention that version ?
