### ISSUE TITLE
Error to download Chromium

### ISSUE THREAD

**Issue by NikolaySolodukhin** [addyosmani/critical#276]
Failed to download Chromium r508693! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download. After npm install --save critical. Node v. 8.9.3. Can you help me how to fix this mistake?

**Comment by muuvmuuv** [comment]
- Try updating to LTS version of node and try it again
- Try to save it as dev dependency 
- Use next version `npm i -D critical@next`

**Comment by XhmikosR** [comment]
Closing since this is a very old issue and in the usual environments we test everything works fine.

**Comment by NivedhaKumaran** [comment]
Failed to download Chromium r508693! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Got this error with Node version 18.18.0
How to fix this ?
