### ISSUE TITLE
How to set `folder` option when html is generated by server side rendering?

### ISSUE THREAD

**Issue by chenesan** [addyosmani/critical#285]
Hi,

In my project I do server side rendering, then pass the output html through express.js middleware to generate critical path css. The options is here:

```javascript

// `html` is the html string; `cssFilePath` is bundled css file path.

critical.generate({
  inline: false,
  html,
  css: [cssFilePath],
  minify: true,
  extract: true,
  dimensions: [{
     width: 1250,
     height: 900,
  }, {
     width: 600,
     height: 900,
  }]
})

```

Then I see the following warning message each time when I run the `critical.generate`:

`Warning: Missing html source path. Consider 'folder' option. https://goo.gl/PwvFVb`

My problem is, since the html is generated in backend code, not a static file, How do I set the `folder` option? The critical css works correctly in fact, but I want to fix the warning message.

Thanks!

**Comment by bezoerb** [comment]
The folder option is used to compute the path to relative assets inside your css. It should reflect the the directory structure of your page.
You should use the destFolder option to specify the relative to your base directory.
If your html resists in the document root you can pass `destFolder: './'`

**Comment by chenesan** [comment]
OK I got it. Thanks!
