### ISSUE TITLE
Package install fails. ERROR: Failed to download Chromium r508693!

### ISSUE THREAD

**Issue by chiragbhansali** [addyosmani/critical#286]
When I run `npm install critical`, I get the following error message:

`npm WARN deprecated fg-loadcss@2.0.1: @2.0.0
> puppeteer@0.12.0 install C:\Users\Neera\Desktop\chiragWork\webD\web-dev-generators\boilerplate\node_modules\puppeteer
> node install.js
`
`
ERROR: Failed to download Chromium r508693! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
npm WARN babel-loader@7.1.1 requires a peer of webpack@2 || 3 but none is installed. You must install peer dependencies yourself.
npm WARN boilerplate@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
``
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.12.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@0.12.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

NPM Version: 5.7.1

**Comment by situ185** [comment]
I have a similar issue...
i have added the http and https proxies to the npm config but still doesnt work.
i added the PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true in config but still the same issue

**Comment by bezoerb** [comment]
@chiragbhansali: i'm sorry but this behavior is not directly caused/related to critical. Maybe take a look here: https://github.com/GoogleChrome/puppeteer/issues/1994

**Comment by bezoerb** [comment]
Hehe, just found the issue you posted over at the puppeteer repo:
https://github.com/GoogleChrome/puppeteer/issues/2173

I guess you've already tried the solution they posted there?

**Comment by situ185** [comment]
this is what I did to get over this:
-I installed critical in my personal machine
-Copied the critical node modules form node_modules folder including the .bin folder
-Copied the dependencies object from the package.json from  my personal machine to the development machine
-run npm install

**Comment by XhmikosR** [comment]
Closing as this is not something we can or should solve here.

**Comment by alex-79** [comment]
`npm install -g -D critical --unsafe-perm=true --allow-root`
