### ISSUE TITLE
Error on Travis when using multi-dimension config

### ISSUE THREAD

**Issue by shiftie** [addyosmani/critical#287]
Hi,

I'm having this error when trying to run `generate()` on Travis (works on local MacOS) with multiple resolutions provided:

```
(node:7511) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): 
TypeError: Cannot read property 'send' of null
```

My config:

```
critical
        .generate({
          base: '.',
          src: `somefile.html`,
          inline: false,
          css: ['style1.css', 'style2.css'],
          dimensions: [
            {
              width: 375,
              height: 667,
            },
            {
              width: 768,
              height: 1024,
            },
            {
              width: 1920,
              height: 1080,
            },
          ],
          include: [/\.someselector/],
          ignore: [/someotherselector/],
        })
        .then(output => { /* .... */ });
        ....
```

I'm using node 8.9.4. 

ps.: When ran with only one resolution (width & height attributes directly in config object), I've had ECONNRESET errors which I've solved by force resolving `ws@3.3.2` due to lack of `on('error')` handler in ws 3.3.3 (which is resolved by puppeteer dependencies).

Could you please help with the multi-dimensions issue?

Thank you.

**Comment by bezoerb** [comment]
Working on a solution in https://github.com/addyosmani/critical/pull/326

**Comment by bezoerb** [comment]
Just published a new prerelease version. Would you mind trying?
You can install the new version with **npm i critical@next**

Thanks
