### ISSUE TITLE
Ignoring CSS from Urls with relative domains and https:

### ISSUE THREAD

**Issue by emiespo** [addyosmani/critical#288]
Hi all,

I think I'll probably have to use penthouse directly, but I wanted to report this issue I came across.
Basically, when passing a url like this:

https://www.domain.com/

...and having CSS served from a different domain (edit: the URL is protocol-relative):

//www.cnd-domain.com/css/awesome-site.css

I get this warning in the output:

`Ignoring http://www.cnd-domain.com/css/awesome-site.css (404)`

(notice it tried http instead of https).

Looking at the code, I found this in critical/lib/file-helper.js:138:

```
        // Handle protocol-relative urls
        uri = url.resolve('http://te.st', uri);
```

Apparently it's assuming the url is not a secure one, it should rather get the same protocol as the main request (if any). Or maybe default to https? Changing that to https did the trick, btw.

As a side issue, I wasn't able to get the CDN path to appear in the inlined source (for images), is that possible at all? I've tried with the assetPaths option with no luck.

Thank you!

**Comment by pocketjoso** [comment]
404 means there was no such file on the server. So this would normally mean it's a problem on your end (or the sites you're loading css from).

**Comment by emiespo** [comment]
Read better: it is trying to access http instead of https (as it should be). If I change that line to https, it works :).

**Comment by pocketjoso** [comment]
I see, then indeed it's a bug in critical.
