### ISSUE TITLE
Doens't run correctly on the Windows Subsytem for Linux (WSL)

### ISSUE THREAD

**Issue by JacobDB** [addyosmani/critical#289]
I'm not sure how to describe this issue exactly, so please bear with me.

If you're not familiar with the Windows Subsystem for Linux (WSL), it's essentially a way to run various Linux distros on Windows. It makes using Linux-based development tools much easier on Windows.

I've been trying to get critical working on-and-off for the last few months, and I've been having a lot of trouble, either getting a bunch of promise rejection errors, or otherwise not picking up all the styles correctly. Today I decided to try this in Command Prompt instead of WSL, and was surprised to see that it ran without issue on the first try.

I'm using Node v8.9.4 on both systems, so the only difference I can discern is that one's running the Linux version and one's running the Windows version.

I've created a small test script, and it's consistently erroring in WSL and running correctly in Command Prompt. The error is as follows:

```
(node:3753) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: kill ESRCH
(node:3753) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections th
at are not handled will terminate the Node.js process with a non-zero exit code.
(node:3753) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: kill ESRCH
```

My test script is attached. [critical-test.zip](https://github.com/addyosmani/critical/files/1816891/critical-test.zip)

I plan on testing this on a Unix-based machine this afternoon, and will report back my results. I'd really appreciate some help in understanding what's happening here, and if there's a way to fix it.

**Comment by JacobDB** [comment]
I just did a few more test cases:

|Machine|System|Node Version|Status|
|---|---|---|---|
|1|Windows - WSL|v8.9.4|Failure|
|1|Windows - CMD|v8.9.4|Success|
|2|Windows - WSL|v6.10.3|Failure|
|2|Windows - CMD|v.7.8.0|Success|
|3|Windows - WSL|v8.9.4|Failure|
|3|Windows - CMD|v8.9.4|Success|
|4|Mac - Terminal|v7.0.0|Success|

**Comment by pocketjoso** [comment]
Looks like this is the underlying issue:
https://github.com/GoogleChrome/puppeteer/issues/1837

**Comment by JacobDB** [comment]
Interesting, thanks for that. There's a new update for Windows 10 coming out next month, maybe it'll fix whatever incompatibility that's causing this.
