### ISSUE TITLE
npm script dev usage

### ISSUE THREAD

**Issue by XhmikosR** [addyosmani/critical#290]
I'm trying to set up critical for bootstrapcdn.

I tried this in package.json scripts:

```json
"critical": "npm start && critical http://127.0.0.1:3333/ --base public --assetPaths public > public/assets/css/critical.css && npm stop",
```

But I always end up with: `Error: css should not be empty`

I'm probably missing something, but any help appreciated!

**Comment by XhmikosR** [comment]
OK, the problem is two-fold:

1. We already inline our custom main CSS (which is just a few bytes) so critical doesn't see any `link`s. I can work around this by not inlining it for development
2. The other CSS file we need as input is a remote one, which we load via `loadjs`. critical doesn't see this stylesheet at all

**Comment by bezoerb** [comment]
Thanks for reporting @XhmikosR. I seems this relates to #277. I‘ll see what I can do.

**Comment by bezoerb** [comment]
@XhmikosR: i just released a new version allowing external stylesheets passed as css option. 

Could you try `"critical": "npm start && critical http://127.0.0.1:3333/ --base public --assetPaths public --css [REMOTE CSS] > public/assets/css/critical.css && npm stop",` with the latest version of critical?

**Comment by XhmikosR** [comment]
@bezoerb: thanks for the quick fix! Although I already changed our code, I'll give it a go tomorrow and get back to you.

**Comment by XhmikosR** [comment]
@bezoerb: confirmed; it now works with remote URLs. Thanks!
