### ISSUE TITLE
position:absolute not evaluated

### ISSUE THREAD

**Issue by dalimian** [addyosmani/critical#292]
I have an absolute positioned div at the bottom of the page that is supposed to show at the top of the page, so I expect this lib to consider it in viewport and extract the styles, but it doesn't.  any workaround?

**Comment by pocketjoso** [comment]
Is it really showing at the top of the page _before any javascript is executed_? If so, then it would be a bug. Could you share a url for where this is happening?

**Comment by dalimian** [comment]
let me reword

I have an absolute positioned div at the bottom of my html markup but I have it show at the top of the page, not a bug, this is by design. so I expect this lib to consider it in viewport and extract the styles, but it doesn't.

**Comment by pocketjoso** [comment]
Normally it should indeed be included in this scenario. This is really a [Penthouse](https://github.com/pocketjoso/penthouse/) issue, but in either case - to debug I will need at least a public url for which this happens, or even better a reduced reproducable test case.

**Comment by dalimian** [comment]
Thanks for quick reply. we’re trying to incorporate this at www.edmunds.com/, and the css for nav header does not make it into critical

**Comment by pocketjoso** [comment]
@dalimian I tried generating critical css for your site, and it looks fine:
![h1p_lozqz-after](https://user-images.githubusercontent.com/7192832/37799723-dfc94362-2e20-11e8-8309-8ed968c81563.jpg)

Are you referring to carousel controls not showing, or something else?
The critical css generation happens without any javascript running, as critical css is used before javascript has loaded in the browser. So any javascript injected content will not be styled by critical css.

**Comment by dalimian** [comment]
thanks @pocketjoso, in your version it does show, I was referring to the header bar, one that has the New Cars, Used Cars, etc, looks good in your mock, does not in mine

in my version it looks like this https://www.screencast.com/t/Ak3w7ehPz - notice the top bar missing

what did you specify for viewport width/height? 

when I leave it out, thus using the defaults - `width: 1300, height: 900` or overriding to "height: 1200" - the bar is missing. when I specify `height:10000` it works, I want it to work with `width:900`

**Comment by bezoerb** [comment]
@dalimian: Can you confirm that nothing in your config/setup is causing the error?
When i use critical on the commandline with the stylesheets specified which i found in the html source the `global-nav` styles are included. Even when i'm overriding the height parameter with 200
```sh
critical https://www.edmunds.com/ -c https://venom-assets.edmunds-media.com/home_page.chunk.9dae07167ffa23f3be6551bf98321d05.css -c https://venom-assets.edmunds-media.com/vendor.bundle.d131791d79a14cc78252d2718c6d6c04.css -h 200
```

**Comment by dalimian** [comment]
thanks @bezoerb 

when I try your command it works for me too, but doing it from js api does not, maybe im not using the api correctly

I created a small repo reproducing the issue - https://github.com/dalimian/critical-test

**Comment by dalimian** [comment]
@bezoerb

**Comment by bezoerb** [comment]
@dalimian: Sorry for the (very) late response. I just checked your example. After switching to the 2.x version of critical (`npm i critical@next`) everything works fine. 
I'm closing this as it's fixed in the latest version of critical and it also might be far too late for the fix. (Sorry for that)

**Comment by dalimian** [comment]
Thanks alot for the update, i will update the package and clean up the dirty workaround. And thanks for the library, it is powering all of edmunds.com

**Comment by bezoerb** [comment]
@dalimian: feel free to reopen this or open a new issue if it’s not working as expected.
