### ISSUE TITLE
Command line; how to do basic http authentication. Get Error: Wrong status code 401 for css files

### ISSUE THREAD

**Issue by mikeytown2** [addyosmani/critical#295]
This almost works
`critical https://user:pass@example.com/`
Looks like resources on the same domain don't add the given user and pass.

**Comment by bezoerb** [comment]
Authentication for resources is currently not implemented.

**Comment by mikeytown2** [comment]
What file would I need to edit in order to do a pull request for this feature? Could you point me in the right direction?

**Comment by bezoerb** [comment]
Maybe you could add user/pass options and use these in `lib/file-helper.js` 
Method: `requestAsync`

**Comment by bezoerb** [comment]
@mikeytown2: I just released critical v1.3.0
You should be able to use it like this now:
```bash
critical https://example.com/ --user user --pass pass
```
