### ISSUE TITLE
Error: css should not be empty

### ISSUE THREAD

**Issue by wizardnet972** [addyosmani/critical#298]
Hi, I have a html file like this:
`<html></html>` 

When I try to run critical it throws an error `Error: css should not be empty`.
Why throw an error instead of doing nothing and return this HTML when css doesn't exist?

**Comment by bezoerb** [comment]
I think it doesn't make any sense to run critical on a html file like this ;)
The purpose of critical is to compute & inline the critical css. If there are no styles to inline there might be something wrong. So instead of failing silently i think it's better to throw an error.

**Comment by wizardnet972** [comment]
I agree if there are no styles to inline there might be something wrong.
But take a look at this case of [offline-webpack-plugin](https://github.com/NekR/offline-plugin), it produce a html file (manifest.html) with this content: 
```
<!doctype html>
<html manifest="manifest.appcache"></html>
```
And after that, I run the critical to iterate each html file inside `dist`. As you can see I can't predict the content of the HTML.
The problem comes when it failed the entire build. Sure, I can catch this error, but take a consider that files are generated by third-party and I got an error about them. 
So this is why I need to critical just return html without any error.

Are you agree?

**Comment by pratham2003** [comment]
`I run the critical to iterate each html file inside dist`
Add an exclusion for manifest.html?
This is something you could do at your side.

Through I would re-think about throwing an error or showing a warning and return an empty response?
An empty HTML page with no styles is still valid HTML.

**Comment by bezoerb** [comment]
@pratham2003: Totally agree :)
This is fixed in the 2.x version of critical. 
You can install critical v2.x like this: `npm i -D critical@next`
