### ISSUE TITLE
@Import is lower the performance score

### ISSUE THREAD

**Issue by wizardnet972** [addyosmani/critical#299]
@addyosmani @bezoerb,
I can see that `@import` lower the score on the performance. for example:
 ```
<html>
<head>
<style>
    @import url(//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css);
    @import url(//cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css);
    @import url(//fonts.googleapis.com/css?family=Varela+Round|Merienda+One|Indie+Flower|Open+Sans:400italic,700italic,400,700);
```
if I remove them, I get a high score, if not I got a lower score. so what can I do about that? is it possible that I should not use `@import`?

**Comment by XhmikosR** [comment]
Yes, just don't use imports because they are blocking.

@bezoerb you can close this issue, it's unrelated to critical.
