### ISSUE TITLE
Duplicate critical CSS block

### ISSUE THREAD

**Issue by Jack89ita** [addyosmani/critical#301]
Hello!
i've got a problem: every time i start my gulp task it creates a new block of critical CSS and append it to my pages. The CSS ruels are perfect but the entire block is duplicated.
This is my task:
```
const gulp = require('gulp');
const print = require('gulp-print').default;
const log = require('fancy-log');
const critical = require('critical').stream;

// Generate & Inline Critical-path CSS
gulp.task('critical-css', function () {
  return gulp.src('build/**/*.html')
    .pipe(critical({
      base: 'build/',
      inline: true,
      css: ['build/resources/css/main.css'],
      include: []
    }))
    .on('error', function (err) { log.error(err.message); })
    .pipe(print(filepath => `Critical generato per il file: ${filepath}`))
    .pipe(gulp.dest('build'));
});
```
Any tip to avoid this problem?
Thanks!

**Comment by Jack89ita** [comment]
Any news about this?

**Comment by BrianEmilius** [comment]
I have this same issue.
critical version 1.3.0
gulp version 4.0.0

**Comment by bezoerb** [comment]
This should be fixed with the latest version of critical.

`npm i critical@next`

See https://github.com/bezoerb/inline-critical/blob/master/test/index.test.js#L274 and https://github.com/bezoerb/inline-critical/blob/master/test/index.test.js#L284

/cc @Jack89ita @BrianEmilius
