### ISSUE TITLE
Extract producing unexpected results

### ISSUE THREAD

**Issue by robbishop** [addyosmani/critical#304]
Hi, I am having an issue with the extract feature when using the following code
css input:
```
.default .sub {
    background-color: #ffffff;
}

.a .sub {
    background-color: #000001;
}

.b .sub {
    background-color: #000000;
}
```
html input
```
    <div class="default a">
        <div class="sub">19.99</div>
    </div>
    <div class="default b">
        <div class="sub">39.99</div>
    </div>
```
with generator
```
critical.generate({
        inline: true,
        base: 'src/',
        src: 'index.html',
        dest: 'index-critical.html',
        width: 1300,
        height: 900,
        extract: true,    
    });
```
The output is as follows

inlined css: 
`.default .sub{background-color:#fff}.a .sub{background-color:#000}.b .sub{background-color:#000}`

extracted css:
```
.default .sub {
  background-color: #ffffff;
}

.b .sub {
  background-color: #000000;
}
```
So the inlined css is correct, but the extracted is not as it duplicates some of the rule-sets. If it is going to produce duplicates then it needs make sure that when they are applied the same effect is achieved. This will result in .a .sub having its color set back to .default .sub. 

However if I change the value of background-color on rule-set .a .sub to #000000 then I get

```
.default .sub {
  background-color: #ffffff;
}

.a .sub {
  background-color: #000000;
}

.b .sub {
  background-color: #000000;
}
```
which is better in that the rule-sets are applied in the right order, but are unnecessarily duplicated.
I have also found that if I minify the input css file first (using clean-css) then extract produces the correct results, which in this case is an empty file (but I have also tested with more rule-sets not above the fold and the extract does contain the correct rule-sets).

Am I missing something?
Thanks

**Comment by bezoerb** [comment]
@robbishop: we replaced the library extracting the critical css with [`postcss-discard`](https://github.com/bezoerb/postcss-discard) which works better than the previous library. 

You can try by installing the prerelease version of critical: `npm i critical@next`

**Comment by XhmikosR** [comment]
Closing due to lack of reply.
