### ISSUE TITLE
Not working in node 10.1.0 -  ExperimentalWarning: The fs.promises API is experimental

### ISSUE THREAD

**Issue by josenobile** [addyosmani/critical#307]
Hi, 
(node:11922) ExperimentalWarning: The fs.promises API is experimental

A related comment: https://github.com/jprichardson/node-fs-extra/pull/578#issuecomment-389058537

**Comment by bezoerb** [comment]
Patch Version of asset resolver is released

**Comment by bezoerb** [comment]
We published a new prerelease version. Would you mind checking the error again?
You can install the new version with `npm i critical@next`

Thanks

**Comment by XhmikosR** [comment]
@bezoerb I personally don't see any warning with 1.3.4 either. You can check the CI too.

**Comment by bezoerb** [comment]
Thanks for checking @XhmikosR!
Closing this as i can’t see any warnings, too.

@josenobile: feel free to reopen if the error still exists or if there are any new insights
