### ISSUE TITLE
vulnerabilities in libraries used by critical

### ISSUE THREAD

**Issue by josenobile** [addyosmani/critical#308]
npm audit

                       === npm audit security report ===

# Run  npm update sshpk --depth 6  to resolve 4 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ sshpk                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ critical                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ critical > postcss-image-inliner > asset-resolver > request  │
│               │ > http-signature > sshpk                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/606                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ sshpk                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ critical                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ critical > postcss-image-inliner > request > http-signature  │
│               │ > sshpk                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/606                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ sshpk                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ critical                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ critical > request > http-signature > sshpk                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/606                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ sshpk                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ micro-cors                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ micro-cors > request > http-signature > sshpk                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/606                       │
└───────────────┴────────────────────────────────────────

**Comment by josenobile** [comment]
Related to https://github.com/joyent/node-http-signature/issues/70

**Comment by bezoerb** [comment]
Thanks @josenobile: i've managed to get rid of the *high* vulnerabilities so far.
Keep this open until the moderate one is also done :)

**Comment by jonahbron** [comment]
It's been almost a month, can one of the primary contributors merge this in? @bezoerb?

**Comment by bezoerb** [comment]
Closing this as there are only 2 low severity vulnerabilities left which are already addressed in the libraries
