### ISSUE TITLE
styleTarget generates critical file, but doesn't add that filename to the html source

### ISSUE THREAD

**Issue by japrescott** [addyosmani/critical#311]
When using the `styleTarget` option, the file is correctly stored at the specified path.
But the inlined part instead references the filename with the generated hash.

e.g

	{
		base: './bin/',
		pathPrefix: '/',
		dimensions:[
			{
				width: 1024,
				height: 1024
			},
			{
				width: 800,
				height: 800
			}
		],
		styleTarget: './bin/css/style.crit.min.css',
		css: [
			'./bin/css/style.min.css'
		],
		assetPaths: [
			'./bin/img',
			'./bin/css/'
		],

		inlineImages:true,
		minify: true,
		inline: true,
		extract: true
	}

the file `bin/css/style.crit.min.css` is correctly generated, but inside the html file, it is referenced as `css/style.crit.min.40c1712.css`

predicting the name of the outcoming css file is critical for when generating the manifest or caching with serviceworkers

**Comment by japrescott** [comment]
I realized, I have misunderstood "styleTarget", as it is intended to save the critical styles, not the "leftover". After reviewing the code, I've created two forks and added the option `overrideOriginal` to [critical](https://github.com/japrescott/critical) and [inline-critical](https://github.com/japrescott/inline-critical).

As this can be a very dangerous option for people not fully understanding what is happening it could lead to loss of their original files. Thus, I am a bit hesitant to create pull request.

**Comment by bezoerb** [comment]
Related to: https://github.com/addyosmani/critical/issues/253
After https://github.com/addyosmani/critical/pull/326 is merged i planed to rewrite the way extract works right now. It will be possible to define a target filename for the critical-extracted original css as well as the critical css which should be respected by `inline-critical`

**Comment by bezoerb** [comment]
@japrescott: critical now generates the "leftover" css by default. 

`const {css, html, extracted} = await critical.generate({...});`

**Comment by bezoerb** [comment]
Just realized that `extracted` was not the best naming choice :)
Maybe i'll just rename this to `uncritical`:D
