### ISSUE TITLE
Other parameters for determining critical CSS besides width/height?

### ISSUE THREAD

**Issue by dolanb12** [addyosmani/critical#312]
Hi,

I’m building a web app that has a bunch of absolute positioned divs on top of each other, each acting as it’s own “screen.”

Is there a way to tell critical to determine by telling it which divs contain critical css?

If not, any suggestions?

Thank you!

**Comment by dolanb12** [comment]
Could one simply set the width and height options to 0, and use the include option to specify the correct divs? Would this be clean?

**Comment by bezoerb** [comment]
@dolanb12: critical is using penthouse under the hood to compute the critical css. Penthouse uses the puppeteer (headless chrome). When all absolute divs are inside the initial viewport of your app you should get the correct results. 
I never tried using 0 as a value for height but i guess this won't bring the expected results.

**Comment by pachiraDIG** [comment]
I see,

I'd love to see this implemented -- a "class-based" feature to go along with the height-based feature for determining what is and isn't critical css.

Any takers?  : )

**Comment by pocketjoso** [comment]
@pachiraDIG can you expand, what do you mean with a "class-based" feature?

**Comment by bezoerb** [comment]
@pachiaDIG: you could try penthouse’ forceInclude option

**Comment by pachiraDIG** [comment]
@bezoerb forceInclude is just what I was looking for, thanks! I now see the include option in the latest version documentation. I was previously looking at the front page readme. 

My only other question is -- what would be the best way to get Critical to not use viewport width & height to determine the critical css? I'd like to use the include option as the sole method for determining what's generated.

**Comment by pachiraDIG** [comment]
I'm sorry, I didn't provide a reference case. [Here's the project.](https://pachira.site)

If you feel Critical is overkill for this type of site, what might you recommend to automate the process?

**Comment by pachiraDIG** [comment]
Hope that makes sense, I'm simply layering absolute-positioned sections on top of each-other, rather than displaying them vertically, one-by-one, as Critical is traditionally designed for. So I'd like to be able to use it strictly for this case.

**Comment by pocketjoso** [comment]
Well like I said before it is overkill using Critical and penthouse for your use case. Just use a css parser like [css-tree](https://github.com/csstree/csstree) (the one Penthouse uses) and filter out the rules you don't want. This execution time for this will be orders of magnitudes faster than using Penthouse (via Critical).
