### ISSUE TITLE
Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined

### ISSUE THREAD

**Issue by XhmikosR** [addyosmani/critical#314]
I was just trying to see why "out of the blue", my gulp tasks just exited after the critical task ran.

Using the code from the [README.md](https://github.com/addyosmani/critical#gulp) I get

```
Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined
```

and my whole gulp task exits there.

```
C:\Users\xmr\Desktop>node -v && npm -v
v10.4.1
6.1.0
```

critical is the current 1.3.3 release.

I know this worked up until some time recently, but I don't know when this broke exactly.

/CC @bezoerb

**Comment by XhmikosR** [comment]
@bezoerb: were you able to reproduce?

**Comment by bezoerb** [comment]
sorry @XhmikosR but i wasn't able to reproduce your error (but i also have no windows machine to test on) 
i used the code from the readme to walk over all the html files in test/fixtures 
and everything was as expected. Can you give some more context to your error or provide a sample repo which is failing?

**Comment by XhmikosR** [comment]
@bezoerb: unfortunately I can't share the source. Is there a gulp + critical demo repo I can use to try to replicate this?

**Comment by XhmikosR** [comment]
@bezoerb: there's definitely a regression somewhere. I'll try to set up a test repo, but it would save me some time if I could just try an existent repo.

**Comment by bezoerb** [comment]
Hey @XhmikosR
I‘m quite busy at the moment but i will try to push my test to a repository later today

**Comment by XhmikosR** [comment]
@bezoerb: I pinpointed the cause. The error is thrown in my case when any HTML files include this:

```html
<meta http-equiv="refresh" content="0; url=https://example.com/" />
```

So, you should be able to reproduce the error with this test file:

```html
<!doctype html>
<html>

<head>
    <title>https://example.com/</title>
    <link rel="canonical" href="https://example.com/" />
    <meta name="robots" content="noindex">
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <!--
    Uncomment the next meta to see critical (or puppeteer) throw:
    `Protocol error (Runtime.callFunctionOn): Cannot find context with specified id undefined`
    -->
    <!--<meta http-equiv="refresh" content="0; url=https://example.com/" />-->
</head>

</html>
```

**Comment by XhmikosR** [comment]
This error makes critical unusable on sites using any redirect via the meta tag.

**Comment by bezoerb** [comment]
@XhmikosR: what is the expected result when running critical/penthouse on a page with a meta redirect? I would just skip the page as there will never be any content visible

**Comment by XhmikosR** [comment]
@bezoerb: I will try it tomorrow and let you know. Thanks for looking into it!

**Comment by XhmikosR** [comment]
@bezoerb: tested it and seems to work fine :)

**Comment by XhmikosR** [comment]
I'll wait for the next npm release, but this seems fixed now.

**Comment by XhmikosR** [comment]
@bezoerb BTW, maybe you could update all deps?

**Comment by XhmikosR** [comment]
Thanks @bezoerb, it works fine!
