### ISSUE TITLE
Any Idea for using critical css in SPA？

### ISSUE THREAD

**Issue by Genuifx** [addyosmani/critical#319]
Most SPA pages separate their HTML elements into components. CSS is scoped, some even import as javascript. Directly using critical in this scenes is not a good choice, so any Idea for using critical CSS in SPA？

**Comment by bezoerb** [comment]
@Genuifx: i would generate the critical css by using the url to my SPA as src and then inline it manually in the head.

E.g.

```bash
critical http://localhost:3000 -m > destination/path/critical.css
```

**Comment by Genuifx** [comment]
@pocketjoso awesome! Does Critical use puppeteer to achieve it? if so, why not wait for js executing, it seems we can get the first render.

Another question is after using Critical to extract CSS if we need drop duplicate CSS from our app? Cause extracting stylesheet, in my opinion, just copies the CSS code to Style element. 😸

**Comment by pocketjoso** [comment]
> @pocketjoso awesome! Does Critical use puppeteer to achieve it? if so, why not wait for js executing, it seems we can get the first render.

The first render happens before JS is loaded. When you depend on JS to render content, critical css makes no sense - there's no performance benefit for you.

> Another question is after using Critical to extract CSS if we need drop duplicate CSS from our app? Cause extracting stylesheet, in my opinion, just copies the CSS code to Style element. 

Only the full stylesheet is cached and re-used on subsequent page visits. It needs to contain all styles.

**Comment by Genuifx** [comment]
got it.(⁎⁍̴̛ᴗ⁍̴̛⁎)
