### ISSUE TITLE
Extracting css for full height of page

### ISSUE THREAD

**Issue by sheerun** [addyosmani/critical#321]
Currently critical only allows to extract CSS for visible viewport, but it breaks for our use case: our CSS is compressed into one file for multiple pages but we want to serve only relevant for page user browsed to. Now our css is quite huge and on mobile it can load slower than user starts interacting with page. It means that user is likely to scroll out of initially visible viewport and see unstyled CSS because critical didn't include it. So here's our feature request:

Allow to extract CSS for all elements on page, visible and not visible in current viewport, so users can scroll through the page before full CSS for all pages is loaded.

**Comment by sheerun** [comment]
(we can hack around this by setting huge height but I don't believe this is the correct solution)

**Comment by pocketjoso** [comment]
Hi @sheerun,
Of course the first call to action would ideally be to reduce the size of your full css, but I can understand if that's not feasible at least not as a quick solution.

For your workaround, first keep an eye on how big your page css is. If it's too large it will slow down your first render, if so it would make more sense to keep both a regular critical css (fast first render), then extract a full page css (quicker full css loaded), and finally also have the full css (cache styles for full site).

How to do this in critical: I think setting huge height is an acceptable workaround. Sure, a more proper feature support in the library could perform a different check for "presence" of different css selectors, but the end result should be the same. What your asking for is also quite an edge case, so if there's already a way you can achieve what you want, I think that might have to be enough. Did you try setting a high height?

**Comment by sheerun** [comment]
In our case full CSS for initial view of single page is not much bigger than full CSS of first visible viewport of this page so there's no sense to do triple load you mention. Critical is good at removing CSS needed only after interactions but we really need CSS for full height of the page so users can interact before full CSS is loaded (or JavaScript is loaded). 

Setting huge height kind of works, but I'm not convinced it's efficient memory-wise and it involves "magic number".

Sorry if I'm mistaken, but isn't the solution as simple as always returning true from `isElementAboveFold` in https://github.com/pocketjoso/penthouse/blob/master/src/browser-sandbox/pruneNonCriticalSelectors.js ?

**Comment by bezoerb** [comment]
@sheerun: How does the critical css for the whole page differ from the output when running [uncss](https://github.com/uncss/uncss) for the page?

**Comment by sheerun** [comment]
I don't know, I use critical and this is issue about critical.. :)

**Comment by dkrnl** [comment]
Hi!
I use critical css with 100vh:
```
    width: 1920,
    height: 99999, // 1080,
    dimensions: [{
        width: 320,
        height: 99999, // 568,
    }, {
        width: 768,
        height: 99999, // 1024,
    }, {
        width: 1200,
        height: 99999, // 900,
    }, {
        width: 1920,
        height: 99999, // 1080,
    }, {
        width: 3840,
        height: 99999, // 2160,
    }],
```

99999 -- magic number 😊

**Comment by bezoerb** [comment]
Closing this as there would be no option for this in critical besides the mentioned "magic number". The purpose of critical is to compute the styles for the critical path.
