### ISSUE TITLE
Getting Ambiguous ENOENT Error

### ISSUE THREAD

**Issue by kightlingerh** [addyosmani/critical#322]
I am getting the following error when running critical (v: 1.3.4): 

```
{
  Error: ENOENT: no such file or directory, open 'dist/[object Object]'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'dist/[object Object]' 
}
```

I have tried using both relative and absolute paths for varying combinations of the src, base, and dest fields to no avail. My current options are:

```
{
  base: 'dist/',
  src: 'index.html',
  dest: 'index.html',
  inline: true,
  minify: true,
  dimensions: [
    {
      width: 425,
      height: 800
    },
    {
      width: 1920,
      height: 1080
    }
  ],
  timeout: 45000,
  penthouse: {
    blockJSRequests: true,
    renderWaitTime: 1000
  }
};

```
Would appreciate any help/advice you have. Thanks.

**Comment by bezoerb** [comment]
Just published a new prerelease version. Would you mind checking the error again?
You can install the new version with **npm i critical@next**

Thanks

**Comment by XhmikosR** [comment]
Closing due to lack of reply.
