### ISSUE TITLE
Remove type="text/css"

### ISSUE THREAD

**Issue by catalinred** [addyosmani/critical#339]
I was thinking if it might be a good idea to remove the `type="text/css"` attributte&value pair from the output?

> If one of the two files was returned without a Content-Type metadata [...], then the default type for stylesheet links would kick in. Since that default type is `text/css`, the style sheet would nonetheless be applied.

> This attribute is optional and defaults to `text/css` if it is not specified

From: 
- https://www.w3.org/TR/html52/document-metadata.html#processing-link-type
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#Attributes

**Comment by bezoerb** [comment]
Done in `critical@next` *v2.0.0-8*
https://github.com/bezoerb/inline-critical/blob/master/test/expected/cartoon-expected-minified.html#L11
