### ISSUE TITLE
 File not found in v2.0.0-12

### ISSUE THREAD

**Issue by joshuaavalon** [addyosmani/critical#355]
**Project**
```
project/
├── dist/
│   ├── index.html
│   └── css/
│         └── vendors.e739fbab34bf82cbf77f.3b93ccbe.css
└── scripts/
      └── postbuild.js
```

**postbuild.js**
```js
const path = require("path");
const critical = require("critical");

const resolvePath = relativePath => path.resolve(__dirname, "..", relativePath);

critical.generate({
  base: resolvePath("dist"),
  src: "index.html",
  target: "index.html",
  inline: true,
  minify: true,
  extract: true,
  penthouse: {
    blockJSRequests: false
  }
});
```

**Error**
> (node:4176) ExperimentalWarning: The fs.promises API is experimental
(node:4176) UnhandledPromiseRejectionWarning: Error: Error: File not found: /css/vendors.e739fbab34bf82cbf77f.3b93ccbe.css
       Current working directory: C:\Users\user\git\project
       Searched in: C:\Users\user\git\project\dist, ., C:\Users\user\git\project
    at resolve (C:\Users\user\git\project\node_modules\critical\src\file.js:181:9)
(node:4176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by
throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I was running 1.3.4 with the same postbuild.js with `dest` instead of `target`. It ran fines.

**Comment by bezoerb** [comment]
Thanks for posting the issue @joshuaavalon.
I tried to reproduce your error but everything seems fine. 

According to the error message, the hashed "uncritical" file is could not be found
> Error: File not found: /css/vendors.e739fbab34bf82cbf77f.3b93ccbe.css
Current working directory: C:\Users\user\git\project
Searched in: C:\Users\user\git\project\dist, C:\Users\user\git\project

To help you i might need some more context information.
1) From which location/how do you call the `postbuild.js`
2) It looks like you overwrite the index.html, correct? 
3) Can you assure the `vendors.e739fbab34bf82cbf77f.3b93ccbe.css` is in place the time you call `critical.generate`
4) Can you set the DEBUG environment Variable to `critical:*` before running your script and post the output here?

Furthermore it would be really helpful if you can provide a gist or something else to reproduce the error.

**Comment by joshuaavalon** [comment]
@bezoerb Sorry,  for  wasting your time. I think I found where is the problem. I was using `node scripts/postbuild.js` instead of `npm run`.
