### ISSUE TITLE
can i use a remote html file url instead of a local one?

### ISSUE THREAD

**Issue by vzaidman** [addyosmani/critical#357]
i have a deployed site i'd like to run critical on but it has many problems running locally.

**Comment by bezoerb** [comment]
Yes ;)

**Comment by almare** [comment]
How ?

**Comment by bezoerb** [comment]
Just pass the url instead of the local filepath:
```
await critical.generate({ src: 'URL' })
```

CLI:
```
npx critical@next https://www.github.com
```

**Comment by almare** [comment]
Thank you. I tried that before, but I think I made a mistake. Now it works.
