### ISSUE TITLE
Issue with dynamically loaded content / components

### ISSUE THREAD

**Issue by vertic4l** [addyosmani/critical#358]
Hi,

we are using https://github.com/jamiebuilds/react-loadable to reduce page load and therefore increase pagespeed scores.

We now noticed that critical can't handle this sort of dynamically loaded content correctly.
There are missing styles in the critical css. Does anyone know how to get it work ?

JS is enabled and changing the wait time in the settings doesn't work unfortunately.

**Comment by pocketjoso** [comment]
The first render with critical css happens before Javascript is loaded, this is one of the reasons it can be fast. So no, the critical css will not style your dynamic content, your full css should do that.
