### ISSUE TITLE
"await critical.generate" doesn't return an object

### ISSUE THREAD

**Issue by b12k** [addyosmani/critical#360]
Hello,
I want to ask for a little guidance.
Following this example:
```javascript
const {css, html, uncritical} = await critical.generate({
  base: 'test/',
  src: 'index.html',
  width: 1300,
  height: 900,
});
```
I'm trying extracting `css` in node server, for server side rendered `React/Vue` application.
```javascript
const html = await renderToString(req.context);
const cssFiles = clientManifest
  .initial
  .filter(asset => asset.match('.css'))
  .map(asset => resolve(path.folder.public, asset));
const generated = await critical.generate({
  html,
  css: cssFiles,
  width: 1920,
  height: 1280,
});
```
I expect `generated` to be an object like `{ css, html, uncritical }`;
I plan to manually inject critical css into html later.

Problems:
1) I'm getting an error: `Warning: Missing html source path. Consider 'folder' option.`
In documentation its written that: `This option takes precedence over the src option.`
2) `generated` is a string

Can someone, please, tell me what am I doing wrong.

Thanx in advance!

**Comment by bezoerb** [comment]
@b12k: it looks like you're running critical v1.3.4. This version only returns a string which is either the html or the critical css based on the `inline` option.
I would recommend installing the prerelease version using `npm i -D critical@next` as we have fixed a lot of bugs in there ;)
