### ISSUE TITLE
Critical is not working with webpack-dev-server using remote css

### ISSUE THREAD

**Issue by HenriqueLimas** [addyosmani/critical#361]
Critical version `2.0.0-X` is making a `head` request to check if the css file exist, but right now webpack-dev-server doesn't support `head` request only get ([issue on webpack-dev-server](https://github.com/webpack/webpack-dev-server/issues/924)). 
I am opening the issue here only to discuss if we could move to `get` request instead of `head` but also to let people know that this is happening.

Some logs from critical:

```
critical:file Fetching resource: http://localhost:3001/static/home.css
critical:file http://localhost:3001/static/home.css failed: Response code 404 (Not Found)
```

**Comment by bezoerb** [comment]
@HenriqueLimas: you can now overwrite the request method using 
```js
generate({
  ...
  request: {method: 'get'}
});
```

**Comment by HenriqueLimas** [comment]
That is perfect. Thanks @bezoerb :+1:
