### ISSUE TITLE
ASP.NET MasterPage/Content overwriting ASP tags

### ISSUE THREAD

**Issue by richie2838** [addyosmani/critical#362]
Hi,

I’m using critical to extract and inline critical-path for my website, but I’ve run into an issue in which the .NET generated code is being modified. 

e.g.

<%@ page language="VB" masterpagefile="~/SiteNoLeftPanelV2.master" autoeventwireup="false" inherits="__ASPNET_INHERITS" enableeventvalidation="false" validaterequest="false" maintainscrollpositiononpostback="true" maxPageStateFieldLength="3000" %>

<%@ Register TagName="PurchaseControl" TagPrefix="uc" Src="~/Components/PurchaseControlNew.ascx" %>

<asp:Content ID="Content1" ContentPlaceHolderID="cpCSSOverride" runat="Server">
    
    <link rel="stylesheet" type="text/css" href="/css/new/magicscroll.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/new/core-product.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/new/caro.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/new/forms.min.css" />

</asp:Content>

When I run the following script, the <%@ tags are modified which breaks the code.  The inline css isn’t included either as the page is a Content page for an <asp:MasterPage

  critical.generate({
        inline: true,
        base: path,
        src: 'Product.aspx',
        dest: './Product.aspx',
        minify: true,
        width: 320,
        height: 480
    });

<%@ **page=""** language="VB" masterpagefile="~/SiteNoLeftPanelV2.master" autoeventwireup="false" inherits="__ASPNET_INHERITS" enableeventvalidation="false" validaterequest="false" maintainscrollpositiononpostback="true" maxpagestatefieldlength="3000" **%=""**>

<%@ **register=""** tagname="PurchaseControl" tagprefix="uc" src="~/Components/PurchaseControlNew.ascx" **%=""**>

<asp:content id="Content1" contentplaceholderid="cpCSSOverride" runat="Server">
    
    <style>
        @charset 'UTF-8';
    </style>
    <link rel="preload" type="text/css" href="/css/new/magicscroll.min.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" type="text/css" href="/css/new/magicscroll.min.css"></noscript>
    <link rel="preload" type="text/css" href="/css/new/core-product.min.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" type="text/css" href="/css/new/core-product.min.css"></noscript>
    <link rel="preload" type="text/css" href="/css/new/caro.min.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" type="text/css" href="/css/new/caro.min.css"></noscript>
    <link rel="preload" type="text/css" href="/css/new/forms.min.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" type="text/css" href="/css/new/forms.min.css"></noscript>
    <script>!function(n){"use strict";n.loadCSS||(n.loadCSS=function(){});var o=loadCSS.relpreload={};if(o.support=function(){var e;try{e=n.document.createElement("link").relList.supports("preload")}catch(t){e=!1}return function(){return e}}(),o.bindMediaToggle=function(t){var e=t.media||"all";function a(){t.addEventListener?t.removeEventListener("load",a):t.attachEvent&&t.detachEvent("onload",a),t.setAttribute("onload",null),t.media=e}t.addEventListener?t.addEventListener("load",a):t.attachEvent&&t.attachEvent("onload",a),setTimeout(function(){t.rel="stylesheet",t.media="only x"}),setTimeout(a,3e3)},o.poly=function(){if(!o.support())for(var t=n.document.getElementsByTagName("link"),e=0;e<t.length;e++){var a=t[e];"preload"!==a.rel||"style"!==a.getAttribute("as")||a.getAttribute("data-loadcss")||(a.setAttribute("data-loadcss",!0),o.bindMediaToggle(a))}},!o.support()){o.poly();var t=n.setInterval(o.poly,500);n.addEventListener?n.addEventListener("load",function(){o.poly(),n.clearInterval(t)}):n.attachEvent&&n.attachEvent("onload",function(){o.poly(),n.clearInterval(t)})}"undefined"!=typeof exports?exports.loadCSS=loadCSS:n.loadCSS=loadCSS}("undefined"!=typeof global?global:this);</script>

</asp:Content>

Any help/comments would be very much appreciated.

**Comment by bezoerb** [comment]
@richie2838: There's no support for .NET in critical. 
To generate the critical css you need either a compiled html version of your .NET template or an url where the html can be accessed. You should then use `inline:false` to just generate the critical css and do the inlining with .NET as we assume regular html for this which breaks your template.
