### ISSUE TITLE
Unable to use glob for css:

### ISSUE THREAD

**Issue by hildissent** [addyosmani/critical#363]
Using a glob for css throws an error that the file doesn't exist.

```
const critical = require("critical");

function build_nstyle() {
	return gulp.src("dist/*.html")
	.pipe(critical.stream(
		{
			base: "dist/",
			css: ["dist/assets/css/*.css"],
			inline: true,
			dimensions:
				[
					{ height:  896, width:  414 },
					{ height: 1024, width:  768 },
					{ height: 1336, width: 1024 },
					{ height: 1440, width: 2560 }
				],
			ignore: { atrule: ["@font-face"] }
		}
	))
	.pipe(gulp.dest("dist"))
}
```

My build works if I pass the full file names to critical, but I use gulp-rev when I generate styles so I don't have permanent file names to pass to it. For now, I'm building a second instance of my styles explicitly to pass to critical, but that redundancy is annoying.

I'm relatively new to all of this, and not very handy with JS, so I haven't ruled out the idea that I'm just doing something wrong.

**Comment by bezoerb** [comment]
@hildissent: which critical version are you running? Glob support for css isn't available in 1.x

**Comment by hildissent** [comment]
Yep. I knew this would be a "me" problem. I see the differences in the installation instructions now. I did a straight "npm --save-dev critical", so I'm on 1.3.4.
