### ISSUE TITLE
Google Cloud Platform function integration - Puppeteer timeouts

### ISSUE THREAD

**Issue by Kalt** [addyosmani/critical#364]
Hello,

I am trying to integrate this project into google cloud background function, but I am having troubles with puppeteer timeouts:

`Function execution took 30004 ms, finished with status: 'timeout'` after calling `critical.generate()`.

`TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r637110 at Timeout.onTimeout (/srv/node_modules/puppeteer/lib/Launcher.js:353:14) at ontimeout (timers.js:498:11) at tryOnTimeout (timers.js:323:5) at Timer.listOnTimeout (timers.js:290:5)`

Sample of one variation of code, that I have used:
```
const critical = require("critical");

exports.criticalCssWorker = async (event, context) => {
  var options = {
    src: "https://www.google.com/",
    // ...
    penthouse: {
      puppeteer: {
        args: ['--no-sandbox'],
        ignoreDefaultArgs: ['--disable-extensions']
      },
    }
  };

  const {css, html, uncritical} = await critical.generate(options);

  // Write result.

  callback();
};
```

I think that this could be caused by an older version of puppeteer used in Penthouse (1.13.0) according to the issues posted [https://github.com/GoogleChrome/puppeteer/issues/3944 ](here) and to the changelog of the puppeteer releases [https://github.com/GoogleChrome/puppeteer/releases](url). Also everything works fine in locally emulated environment.

Is anyone experiencing same issues? 

Should I wait for the package update, or could it be please caused by something else that I am missing?

Thanks in advance for any tips and help & thank you for this awesome project :)

**Comment by bezoerb** [comment]
@pocketjoso do you have any experience with running penthouse in an environment like this?

**Comment by pocketjoso** [comment]
@Kalt if you want to try out the latest puppeteer version, it is avaialble via `penthouse@2.1.1-rc2`. It should be merged and released as `latest` within about one week.

**Comment by Kalt** [comment]
Thank you very much for your replies. I just tried latest penthouse@2.1.1-rc2 in GCP function and everything works as expected! :) 

Sadly, in GCP function I am not able to redefine dependency versions using shrinkwrap or package-lock.json, so I will need to wait for the new version of critical. 

@bezoerb will be please available new version of critical after penthouse 2.1.1 release anytime soon?

**Comment by bezoerb** [comment]
@Kalt: released [v2.0.0-17](https://github.com/addyosmani/critical/releases/tag/v2.0.0-17) with `penthouse` 2.2.0

**Comment by Kalt** [comment]
@bezoerb Thank you very much for the package update! :) Critical started to work for simple cases, but when I specify more than 4 dimensions, then suddenly I am getting the very same issue.

`...,
dimensions: [ { width: 440, height: 594 }, { width: 766, height: 1360 }, { width: 1060, height: 594 }, { width: 1280, height: 720 }, { width: 1660, height: 936 } ].
...`

It is really strange, because for 4 dimension critical css generation takes ~30 secs and works smoothly and then for 5 dimensions I am getting timeout after 300 seconds. Any ideas please?

**Comment by bezoerb** [comment]
@Kalt: you can try the concurrency option. This is currently undocumented.
See https://github.com/addyosmani/critical/issues/371

The default value is `Infinity`. If you set this to 4 it might help.
```js
const critical = require("critical");

exports.criticalCssWorker = async (event, context) => {
  var options = {
    src: "https://www.google.com/",
    concurrency: 4,
    // ...
    penthouse: {
      puppeteer: {
        args: ['--no-sandbox'],
        ignoreDefaultArgs: ['--disable-extensions']
      },
    }
  };

  const {css, html, uncritical} = await critical.generate(options);

  // Write result.

  callback();
};
```

**Comment by Kalt** [comment]
@bezoerb Awesome! It looks like setting concurrency to **1** is essential to work reliably on GCF. I completely missed that option. Setting concurrency to higher values caused ocasional failures, so for me is **1** the safest value.

Thank you very much for your help :)
