### ISSUE TITLE
Using critical.css

### ISSUE THREAD

**Issue by thelgevold** [addyosmani/critical#372]
The example below allows me to correctly separate critical css from non critical css, but I am noticing that the generated index-index.html file still preloads the original css file. Wouldn't it be more appropriate to pre load uncritical.css? Looks like I have to manually make that change, or am I missing something?
```
return critical.generate({
   src: 'index.html',
   base: 'dist/apps/critical-css/',
   inline: true,
   target: {css: 'critical.css',
            html: 'index-critical.html',
            uncritical: 'uncritical.css'},
   minify: true,
   width: 1300,
   height: 900,
 }
```

This is happening in the current @next version.

Thanks.

**Comment by bezoerb** [comment]
@thelgevolt: have you already tried adding extract:true to the options? 
I could take a look this evening but hopefully the extract option already does the trick :)

**Comment by thelgevold** [comment]
Thanks. I tried updating it to 

```
critical.generate({
    src: 'index.html',
    base: 'dist/apps/critical-css/',
    inline: true,
    target: {css: 'critical.css', 
             html: 'index-critical.html', 
             uncritical: 'uncritical.css'},
    minify: true,
    width: 1300,
    height: 900,
    extract:true
  })
```
But it seems like it still loads the original stylesheet in the preload link.

**Comment by bezoerb** [comment]
Thanks for the feedback. It should use the the target you specified for uncritical if both options are set. I’ll check that

**Comment by bezoerb** [comment]
@thelgevold: just published a small fix for this. Can you try again using the latest version `critical@next`?

**Comment by thelgevold** [comment]
I just confirmed that this is fixed in the latest version. Thanks @bezoerb for the quick turnaround time on this. 

Closing.
