### ISSUE TITLE
'Parameter file needs to be a vinyl object'

### ISSUE THREAD

**Issue by WebDevLuke** [addyosmani/critical#373]
Hey, I'm trying to use this via Gulp 3.9.1, but I'm running into the same console error even when using the example from the README.md.

`Parameter file needs to be a vinyl object`

This is my Gulp task so far:-

```
var log = require('fancy-log');
var critical = require('critical');

// Generate & Inline Critical-path CSS
gulp.task('test', function() {
  return gulp
    .src('./dist/*.html')
    .pipe(critical.stream({
    	base: './dist/',
    	inline: true,
    	minify: true,
    	css: ['dist/css/*.css'],
    	dimensions: [
    		{
    			width: 320,
    			height: 480
    		},
    		{
    			width: 768,
    			height: 1024
    		},
    		{
    			width: 1280,
    			height: 800
    		}
    	],
    	ignore: {
    		atrule: ['@font-face']
    	}
    }))
    .on('error', function(err) {
      log.error(err.message);
    })
    .pipe(gulp.dest('./dist'));
});
```

Anybody have any ideas? I feel as though it's something obvious, but I'm not seeing it. 🤔

**Comment by bezoerb** [comment]
Hey @webdevluke, which version of critical are you running?

**Comment by WebDevLuke** [comment]
I'm on 2.0.0-18. 👍

**Comment by bezoerb** [comment]
@WebDevLuke: Just tried this with a fresh install of `gulp`, `fancy-log` & `critical@next` and everything is working just as expected. One cause i could imagine though might be an outdated version of the [`vinyl`](https://gulpjs.com/docs/en/api/vinyl-isvinyl) library. Which gulp version do you use?

**Comment by jlukic** [comment]
I recently encountered this issue with my build pipeline and found that it was caused by using [`gulp-plumber`](https://github.com/floatdrop/gulp-plumber) to handle stream errors.

For anyone who uses this in their pipeline, simply removing `.pipe(plumber())` from stream will fix issue.

**Comment by jlukic** [comment]
I think this is an incompatibility with Gulp 3

* Gulp 3 uses [`vinyl-fs 0.30`](https://github.com/gulpjs/gulp/blob/v3.9.1/package.json#L41)
* Vinyl-fs 0.30 uses [`vinyl 0.20`](https://github.com/gulpjs/vinyl-fs/blob/v0.3.0/package.json#L19)
* Vinyl `0.20` does not support this method (added in [0.5.3](https://github.com/gulpjs/vinyl/releases/tag/v0.5.3))

**Comment by jlukic** [comment]
It looks like this use-case was already handled but some functions weren't using the necessary helper.
https://github.com/addyosmani/critical/pull/378
