### ISSUE TITLE
Hugo and/or PostCSS compatibility

### ISSUE THREAD

**Issue by bronze** [addyosmani/critical#380]
Has anyone made this work with Hugo?

I get errors about not finding the index file (ok, that was to be expected running async).
On 2nd pass everything works. However, on server it doesnt run twice, so i need to make it work on 1st pass.

Been looking for a defer postcss.config way to do it but didnt find one.
Tried running after hugo with npm run hugo && critical (...), also didnt work.

Id gladly accept ideas/insights on this.

cheers

**Comment by XhmikosR** [comment]
The static site generator shouldn't matter. You might be referencing stylesheets that critical cannot find, but the only way someone can help you is to have access to a minimal reproducible example.

**Comment by bronze** [comment]
ok i have been cracking my head over this for a bit and decided to try fitting gulp instead of relying on CLI. I found a [good example](https://gitlab.com/anthonytang411/temp-critical-repro/tree/master) from #216 
i can reproduce his example with full url of the css files. 
relative stylesheets like `<link rel="stylesheet" href="./css/uikit.min. ... .css" integrity="..." media="print" onload="this.media='all'">` arent being found. "Missing base path."

but thats another issue, and some screw up on my part,  thanx!
