### ISSUE TITLE
Remove inlined CSS rules from source stylesheets

### ISSUE THREAD

**Issue by bevacqua** [addyosmani/critical#39]
We could use `cave` to go through the stylesheets where the critical CSS is pulled from, and "diff" the two, removing critical CSS from the original stylesheets.

e.g:

```js
critical = 'a{color:#f00}'
cave(stylesheet, { css: critical }, saveUpdates)
```

**Comment by bezoerb** [comment]
f2428a480154fce93af504009e1f4eb5016262e0
