### ISSUE TITLE
PAGE_UNLOADED_DURING_EXECUTION tests fail in appveyor

### ISSUE THREAD

**Issue by bezoerb** [addyosmani/critical#394]
The tests are currently skipped in `master` & `1.x`.
The tests pass locally and fail on appveyor.

We need to inspect if this can be fixed in `critical` or if this needs to be handled in [`penthouse`](https://github.com/pocketjoso/penthouse)

https://ci.appveyor.com/project/addyosmani/critical/builds/26706172/job/3x255lx5pn2ipajp

**Comment by XhmikosR** [comment]
I tested this recently on GitHub Actions CI and they fail there too.

**Comment by bezoerb** [comment]
PAGE_UNLOADED_DURING_EXECUTION is working fine now
