### ISSUE TITLE
Can you return the http headers from penthouse as you do the html ?

### ISSUE THREAD

**Issue by cameronbraid** [addyosmani/critical#398]
Currently I am running generate using a URL, and I wish to verify that the correct version of the content is being rendered, and this information is available as a http header.  Are you able to expose the http headers so I can do the following :

```
let { css, html, headers } = await critical.generate(...)
```

**Comment by bezoerb** [comment]
@cameronbraid: Thanks for using critical. I'm sorry but there is currently no way to expose the response headers.
