### ISSUE TITLE
Any background images already inlined cause problems with imageinliner

### ISSUE THREAD

**Issue by nowherenearithaca** [addyosmani/critical#40]
This seems to be an issue with the imageinliner module (I posted note there about this) - in my case, it looks like this that seems to cause the problem - "background-image: url("data:image/svg+xml;base64,PD94bW...")

for the moment, may be that you need to add an option to avoid the imageinliner (line 74 of index.js)

**Comment by bezoerb** [comment]
Closing this as the imageinliner can already be turned off. 
See: https://github.com/addyosmani/critical/blob/master/test/02-generate.js#L126
