### ISSUE TITLE
Even After setting inline option to false, still returns both css and html

### ISSUE THREAD

**Issue by NaghaveerR** [addyosmani/critical#416]
This is my request Obj

```js
let criticalRequestObj = {
      inline: false,
      src: htmlURL,
      width: 4000,
      height: 4000,
      minify: false,
      penthouse: {
        timeout:    60000
      },
    };
```

And I'm calling the critical 
`let criticalResponse = await critical.generate(criticalRequestObj);`

`criticalResponse` is having both HTML as well as CSS.
I have set inline to false so that I no need to get the big HTML content in my response.

**Comment by bezoerb** [comment]
The html is always returned just in case you want to handle the inlining yourself. If you don't want it in your response you could use destructuring to only grab the critical css:
```js
 let {css:criticalResponse} = await critical.generate(criticalRequestObj);
```
