### ISSUE TITLE
Media query from <link> should be used to wrap the <link> contents

### ISSUE THREAD

**Issue by mklepaczewski** [addyosmani/critical#443]
With sample files as below the contents of the `test.css` is included in the critical CSS without any media query around it. In my opinion, the media query from the link should be used to wrap the contents of the `test.css` file in the output.

## test.html
```
<html>
<head>
    <link rel="stylesheet" href="test.css" type="text/css" media="(max-width: 9px)">
</head>
<body>
    <div id="container">Lorem ipsum</div>
</body>
</html>
```

## test.css
```
#container {
    padding: 1em;
    border: 1px solid red;
}
```
## Current output
```
#container {
    padding: 1em;
    border: 1px solid red;
}
```

## Expected output
```
@media (max-width: 9px) {
#container {
    padding: 1em;
    border: 1px solid red;
}
}
```

**Comment by bezoerb** [comment]
Fixed in [v4.0.1](https://github.com/addyosmani/critical/releases/tag/v4.0.1)
