### ISSUE TITLE
Move to media=print async CSS loading

### ISSUE THREAD

**Issue by Snugug** [addyosmani/critical#444]
Working off of Critical v2.0.0-24, I'm seeing async CSS links being rewritten to a `preload` based strategy presumably based on the loadCSS project, but it looks like the [currently recommended code](https://www.filamentgroup.com/lab/load-css-simpler/) favors `media="print"` instead of `preload`, and in doing so improves browser support greatly.

I think it's be worthwhile to move Critical 2.x to this `print` based approach, maybe optionally allowing for a declarative property to include the `preload` option as described further down in that article.

**Comment by bezoerb** [comment]
Hey @Snugug 
thanks for this issue :)
The inlining is done by [`inline-critical`](https://github.com/bezoerb/inline-critical) so i will move the issue there.

**Comment by bezoerb** [comment]
fixed in `v2.0.0-25`
