### ISSUE TITLE
Backslashes in output url()s on Windows

### ISSUE THREAD

**Issue by r-flash** [addyosmani/critical#45]
When rebasing urls starting with `../`, backslash is used as a path separator.

For example `background-image:url(../img/sprite.png);` in my original stylesheet is translated to `background-image:url(\img\sprite.png);`, which results in an incorrect request for /imgsprite.png, instead of /img/sprite.png.

**Comment by bezoerb** [comment]
@addyosmani I've just configured appveyor to run tests on windows but it looks like they don't start automatically. I think you need to add the following webhook for `push` and on `pull request` to critical:
https://ci.appveyor.com/api/github/webhook?id=cn6jw7r3ur0gmyg6

**Comment by bezoerb** [comment]
@addyosmani added you as admin to the `appveyor` project
