### ISSUE TITLE
Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by Krishnakumarskr** [addyosmani/critical#450]
I'm getting this error while deploying from docker.
![Screenshot 2020-06-09 at 7 13 14 PM](https://user-images.githubusercontent.com/29063514/84160467-d7727500-aa8b-11ea-9c40-808d5e22f9ed.png)

**Comment by bezoerb** [comment]
This seems to be a problem with puppeteer rather than critical itself.
You should try here: https://github.com/puppeteer/puppeteer/issues?q=docker
