### ISSUE TITLE
 creating critical-css incorrectly? How to open chrome browser while creating critical-css to debug

### ISSUE THREAD

**Issue by admicro** [addyosmani/critical#462]
I want this software to open chrome browser while creating critical-css, what should I do?
This tool has a built-in penthouse, but I don't know how to use it. Can you give me some snippets to learn from it.

Purpose: before creating critical-css I want the browser to wait a few seconds, mouse click or scroll down a little (understand that there is interaction with the page).

I think action like that will generate critial css correctly.

Thank very much.

**Comment by bezoerb** [comment]
Hey @admicro, 
the purpose of critical css is to let the browser render the initial viewport before the site is fully loaded. When you scroll or interact with the page the browser should have already loaded the non critical styles.

What styles are you missing or which styles are not generated correctly?

**Comment by admicro** [comment]
thank you! i fixed it.

**Comment by bezoerb** [comment]
Could you describe how you fixed it? Maybe this helps other users facing the same issue. Thanks

**Comment by bezoerb** [comment]
I'm closing this due to lack of feedback.
Feel free to reopen if there are new insights
