### ISSUE TITLE
update csp tags and/or integrity attributes

### ISSUE THREAD

**Issue by chrisguttandin** [addyosmani/critical#465]
Hi there, thanks for providing this package. I'm using it to inline the CSS of a prerendered Angular application. The app has a CSP tag and also sets the integrity attribute for all stylesheets. After running critical I have to manually adjust those since they are of course affected by the newly created stylesheet and by the preload tags.

Do you think it makes sense to handle this as part of critical itself?

**Comment by chrisguttandin** [comment]
Hi @bezoerb, do you want me start with a PR for this feature?

**Comment by bezoerb** [comment]
Hey @chrisguttandin, thanks for bringing this up again.

I think this needs to be fixed in [`inline-critical`](https://github.com/bezoerb/inline-critical) as `critical` does't do any dom manipulations itself. If you want to start a PR i would be happy to get this landed :)

**Comment by bezoerb** [comment]
Fixed in [`inline-critical v6.0.2`](https://github.com/bezoerb/inline-critical/releases/tag/v6.0.2)
