### ISSUE TITLE
Example for cli command

### ISSUE THREAD

**Issue by LexKoomen** [addyosmani/critical#473]
Hi guys,

Is it possible you add some cli commands on how to pass all the different kinds of options?
I'm trying to figure out how to use the penthouse and request option

penthouse is probably working like:
``` --penthouse-renderWaitTime=3000 --penthouse-blockJSRequest=false```

But how is request working? I want to skip ssl verification. Because of local development:
``` Error: unable to verify the first certificate```

Docs says you need to set https.rejectUnauthorized to false but I get an error whenever I try:
``` --request-https.rejectUnauthorized=false```

```   Error: Expected value which is `predicate returns truthy for any value`, received value of type `Array`.```

**Comment by bezoerb** [comment]
Hey @LexKoomen,
thanks for using critical. Which version do you have installed? I just tested the use case you described with `v2.0.6` and it seems the rejectUnauthorized option is set correctly

```bash
❯ DEBUG=critical:config node cli.js test/fixtures/generate-default.html --base test/fixtures/ --request-https.rejectUnauthorized=false

  critical:config {
  critical:config   base: 'test/fixtures/',
  critical:config   inline: false,
  critical:config   extract: false,
  critical:config   inlineImages: false,
  critical:config   dimensions: [ { width: 1300, height: 900 } ],
  critical:config   request: { https: { rejectUnauthorized: 'false' } },
  critical:config   src: 'test/fixtures/generate-default.html',
  critical:config   strict: false,
  critical:config   width: 1300,
  critical:config   height: 900,
  critical:config   minify: true,
  critical:config   maxImageFileSize: 10240,
  critical:config   include: [],
  critical:config   concurrency: Infinity,
  critical:config   penthouse: { forceInclude: [], timeout: 30000, maxEmbeddedBase64Length: 10240 }
  critical:config } +0ms


```

**Comment by LexKoomen** [comment]
Hee @bazoerb,

Thanks for replying 👍 
I just tried it again but I still receive the error for my local domain.

How to scan self signed ssl sites?

```DEBUG=critical:config cli.js 'https://local.test/' --base 'pub/static/frontend/default/' --dimensions 500x900 --dimensions 1300x900 --request-https.rejectUnauthorized=false
  critical:config {
  critical:config   base: pub/static/frontend/default/',
  critical:config   dimensions: [ { width: 500, height: 900 }, { width: 1300, height: 900 } ],
  critical:config   inline: false,
  critical:config   extract: false,
  critical:config   inlineImages: false,
  critical:config   request: { https: { rejectUnauthorized: 'false' } },
  critical:config   src: 'https://local.test/',
  critical:config   strict: false,
  critical:config   width: 1300,
  critical:config   height: 900,
  critical:config   minify: true,
  critical:config   maxImageFileSize: 10240,
  critical:config   include: [],
  critical:config   concurrency: Infinity,
  critical:config   penthouse: { forceInclude: [], timeout: 30000, maxEmbeddedBase64Length: 10240 }
  critical:config } +0ms
```

```Error: Expected value which is `predicate returns truthy for any value`, received value of type `Array`.```

**Comment by LexKoomen** [comment]
Is it maybe because the ```request: { https: { rejectUnauthorized: 'false' } },``` parameter is with quotes?

**Comment by bezoerb** [comment]
> Is it maybe because the `request: { https: { rejectUnauthorized: 'false' } },` parameter is with quotes?

That's it, good catch :) I totally missed that 🤦🏼‍♂️ 
Try 
```bash
DEBUG=critical:config cli.js 'https://local.test/' --base 'pub/static/frontend/default/' --dimensions 500x900 --dimensions 1300x900 --no-request-https.rejectUnauthorized
```

**Comment by LexKoomen** [comment]
Totally forgot to respond, that was it! I'll close the issue
