### ISSUE TITLE
I read your article today，very fruitful，I have a question

### ISSUE THREAD

**Issue by qianguyihao** [addyosmani/critical#474]
Hello, big  boss,  I read your article today, I feel very good, very fruitful：

Faster Web App Delivery with PRPL：https://addyosmani.com/blog/the-prpl-pattern/

By the way, what tool do you use for image annotation in this article? It’s so beautiful. I look forward to hearing from you.Thank you.

![image](https://user-images.githubusercontent.com/8827896/99362046-eccab580-28ed-11eb-9d89-fbcf2c65fa11.png)

**Comment by bezoerb** [comment]
Hey @qianguyihao,
thanks for the kind words. I'm closing this issue because it's unrelated to critical.
