### ISSUE TITLE
How to debug what critical sees?

### ISSUE THREAD

**Issue by pattonwebz** [addyosmani/critical#475]
Hi there,

First of all thank you for this package - it is very easy to use and I was able to get it running against local files and also live urls quite quickly. I am having some issues though and I don't know how to debug the cause.

Basically CSS that I don't expect in the critical path is being extracted to the `critical.css file`. Elements from the page which are thousands of px below the fold are being included - things that are away in the footer.

If I have configs with very small heights and give penthouse extra time to wait on render it still gets CSS from way down the page:

```
    penthouse: {
      'renderWaitTime': 15000
    },

    width: 1200,
    height: 50,

    // dimensions: [
    //   {
    //     height: 100,
    //     width: 414,
    //   },
    //   {
    //     height: 120,
    //     width: 1200,
    //   },
    // ],
```

Any ideas how I can debug why this is happening? Thanks in advance!

**Comment by bezoerb** [comment]
You can enable critical debug messages by setting the `DEBUG` env variable to `critical:*`
