### ISSUE TITLE
critical CSS not generated while using with "defer" CSS

### ISSUE THREAD

**Issue by krish4u** [addyosmani/critical#478]
Hi,

I am generating critical CSS for a series of URL. After I the implementation of defer CSS the critical css generation stopped. 

My project has "defer" css like below
`<link rel="stylesheet" href="/path/to/my.css" media="print" onload="this.media='all'">`

Also there was no issues logged.  I assume this behavior is due to the media attribute "print" which has low priority and makes the critical CSS to skip the CSS files.  

If the issue is due to the defer CSS concept, Is there any option to tell critical module to wait certain time before act on the page so that the media attribute values changes from print to all.

config I am using for critical
```
base: './',
src: files[i],
target: files[i],
minify: true,
inline: true,
dimensions: [{
    width: 414,
    height: 736
                    }],
ignore: ['@font-face']
```

Thanks.

**Comment by bezoerb** [comment]
critical statically analyzes the html and uses the relevant css files found. You can specify the css via config though:
```js
base: './',
src: files[i],
css: './path/to/my.css',
target: files[i],
minify: true,
inline: true,
dimensions: [{
    width: 414,
    height: 736
                    }],
ignore: ['@font-face']
```

**Comment by gherkz** [comment]
This is affecting me. I use critical to generate critical CSS for remote web pages via the CLI. Many web sites follow these standards (as per https://www.filamentgroup.com/lab/load-css-simpler/) for inlining critical CSS. This means that critical doesn't pick up the CSS file.

One solution would be to check the onload attribute here: https://github.com/addyosmani/critical/blob/6b3e957ee2081dccb7113f23f4d648142687ef53/src/file.js#L376 to see if it contains the strings 'media'. This would support `onload="this.media='all'"` as well as `onload="this.media='screen'"`. I'll submit a PR for this soon, but happy to change it if there's a better way to do it.

**Comment by bezoerb** [comment]
This has lended in [v4.0.0](https://github.com/addyosmani/critical/releases/tag/v4.0.0)
