### ISSUE TITLE
CSP header doesn't like hashed onload attribute

### ISSUE THREAD

**Issue by paulshryock** [addyosmani/critical#480]
When I use Critical, I end up with this HTML `link` element after the inlined styles:

```html
<link rel="stylesheet" href="/css/main.css" media="print" onload="this.media='all'">
```

And this when it's minified in production:

```html
<link href=/css/main.min.css rel=stylesheet media=print onload='this.media="all"'>
```

I'm using a Content Security Policy header with `script-src 'self';`, and of course the `onload` inline script throws a browser console error.

So I've tried hashing `this.media="all"` (with double quotes) and adding `'sha256-kx8Md/dUVxiWxH0xNDfI+0jY+S4Ev2Jri3jBG4rrm9E='` to the `script-src` directive. The same console error is thrown.

I've also tried instead hashing `this.media='all'` (with single quotes) and adding `'sha256-MhtPZXr7+LpJUY5qtMutB+qWfQtMaPccfe7QXtCcEYc='` to the `script-src` directive. Same console error.

Has anyone managed to use Critical along with a secure CSP header that works with the `onload` attribute (without using `unsafe-inline`)?

**Comment by bezoerb** [comment]
Hey @paulshryock,
In CSP-2 script hashes only apply to elements, not event handlers.
CSP-3 introduces the 'unsafe-hashed-attributes' but i don't know how well it's supported.
https://w3c.github.io/webappsec-csp/#unsafe-hashes-usage

**Comment by paulshryock** [comment]
> Hey @paulshryock,
> In CSP-2 script hashes only apply to elements, not event handlers.
> CSP-3 introduces the 'unsafe-hashed-attributes' but i don't know how well it's supported.
> https://w3c.github.io/webappsec-csp/#unsafe-hashes-usage
> 

Yeah, I came to the same conclusion. Thanks for following up. It's kind of a bummer to not be able to use this along with a secure CSP. 🤷

**Comment by bezoerb** [comment]
Seems like a dead end for now 
> The unsafe-hashes directive was added to CSP Level 3. It is currenlty only supported in Chrome 69+ or Chromium Based Edge 79+.

**Comment by bezoerb** [comment]
Maybe we could add something like this to [`inline-critical`](https://github.com/bezoerb/inline-critical):
https://github.com/filamentgroup/loadCSS/issues/312

**Comment by paulshryock** [comment]
> Maybe we could add something like this to [`inline-critical`](https://github.com/bezoerb/inline-critical):

Yeah, I've been using something similar, except I hash the JS instead of using a nonce. I post-process the HTML to move `onload` to `data-onload`. It works sometimes in some browsers, but seems to add more headache than it's worth, without a smooth experience across browsers and environments. After a while I think "wait why am I not just loading the CSS the normal way instead of jumping through all these hoops for a standard baseline of security?"

https://github.com/paulshryock/paul-shryock/blob/v0.1.5/src/pshry.com/assets/js/utilities/onload.js#L14-L29

**Comment by Macleykun** [comment]
@paulshryock may i suggest using this approach:
`rel="stylesheet preload"`? 

This should be valid html, that is not violating CSP that hopefully, isn't blocking css.

https://www.sitepoint.com/critical-rendering-path-css-fast-loading-website/

I sadly lack the experience to properly test this, but alas maybe you can have a go with it :).

**Comment by paulshryock** [comment]
> @paulshryock may i suggest using this approach:
> `rel="stylesheet preload"`?
> 
> This should be valid html, that is not violating CSP that hopefully, isn't blocking css.
> 
> https://www.sitepoint.com/critical-rendering-path-css-fast-loading-website/
> 
> I sadly lack the experience to properly test this, but alas maybe you can have a go with it :).

Yeah, I may end up going with something like this instead of the way `critical` loads stylesheets after the DOM `load` event. It's a shame, because I think the inline JS is a great solution (if it worked with CSP).

**Comment by Macleykun** [comment]
> > @paulshryock may i suggest using this approach:
> > `rel="stylesheet preload"`?
> > This should be valid html, that is not violating CSP that hopefully, isn't blocking css.
> > https://www.sitepoint.com/critical-rendering-path-css-fast-loading-website/
> > I sadly lack the experience to properly test this, but alas maybe you can have a go with it :).
> 
> Yeah, I may end up going with something like this instead of the way `critical` loads stylesheets after the DOM `load` event. It's a shame, because I think the inline JS is a great solution (if it worked with CSP).

True, but if rel="stylesheet preload" is equally good in fuctionality as the DOM load event. Then it's feasible to add a --preload flag or --onload flag to criticalcss. So that users can pick what suites their needs
> Use [onload](https://caniuse.com/?search=onload) to support older browsers like IE.
> Use [preload](https://caniuse.com/?search=preload) to have none violating CSP.

Curious what @bezoerb thinks about this proposal.

**Comment by paulshryock** [comment]
> @paulshryock may i suggest using this approach:
> `rel="stylesheet preload"`?
> 
> This should be valid html, that is not violating CSP that hopefully, isn't blocking css.
> 
> https://www.sitepoint.com/critical-rendering-path-css-fast-loading-website/

The problem with using the method linked above is that it's basically the same implementation: using `onload` to change the `<link>` element and trigger an async stylesheet download. That would still fail a CSP with `script-src 'self';`.

```html
<link rel="preload" as="style" href="style.css" onload="this.rel='stylesheet'">
```

**Comment by Macleykun** [comment]
Well i'm using script-src self as shown here (i'm using a cf worker)
https://securityheaders.com/?q=https%3A%2F%2Fvoxsiren.net&followRedirects=on
and here is the style
https://github.com/TheVoxSiren/voxsiren.net/blob/main/index.html#L19
you can visit voxsiren.net and see that no csp is violated.

**Comment by paulshryock** [comment]
Ah, so skipping the `onload` handler. Yeah, that makes sense.

**Comment by jaylinski** [comment]
I'm confused, does this really make CSS non-render-blocking?
```
<link rel="stylesheet preload" href="assets/css/bootstrap.css" as="style">
```
I read the spec, but it doesn't mention combining `preload` with other link-types: https://www.w3.org/TR/preload/
So I assume the browser falls back to `stylesheet` and the stylesheet is still render-blocking. Or is there some browser magic happening? Lighthouse reports the styles as non-render-blocking, but maybe it gets confused by the `preload` keyword.

**Comment by Macleykun** [comment]
It should given the REL spec: https://stackoverflow.com/questions/19185431/can-you-have-two-values-in-a-single-rel-attribute

Also, you can test our site: https://voxsiren.net/ to see if there's any difference. I think you can test it by loading a big CSS file and try loading two css files with both preload and one withoud. You can then compare how they are loaded and see if preloading this way works.

Hope you can verify it's workings

**Comment by jaylinski** [comment]
@Macleykun I checked this with your site and the Chrome DevTools performance-tab. If I interpret the results correctly, your styles are render-blocking, because they are parsed before the first layout/paint occurs:

![Bildschirmfoto 2021-03-30 um 12 54 30](https://user-images.githubusercontent.com/1668766/112978020-12e34a80-9157-11eb-8917-18901ae278cb.png)

But I could be totally wrong...

**Comment by Macleykun** [comment]
https://github.com/TheVoxSiren/voxsiren.net/commit/1feab78b245c2c34606d5ff1e7c94e81cb83f31d
Remove them now, you can test again if your result indeed shows that two values in rel, with preload doesn't work (or maybe i need to try preload and then stylesheet in rel).

**Comment by jaylinski** [comment]
@Macleykun Now the styles are loaded non-render-blocking, but they are never applied to the DOM. You have to do this manually via JavaScript (https://www.w3.org/TR/preload/#example-1-using-markup). Only your critical (inlined) CSS is applied to the DOM now.

![Bildschirmfoto 2021-03-30 um 13 20 48](https://user-images.githubusercontent.com/1668766/112980885-c00b9200-915a-11eb-876e-2d06889497c5.png)

**Comment by Macleykun** [comment]
ah i see, so there isn't a easy way to preload withoud causing csp to act up?

**Comment by jaylinski** [comment]
> ah i see, so there isn't a easy way to preload withoud causing csp to act up?

It seems there isn't 😕 (https://discourse.wicg.io/t/deferred-stylesheets-take-3/4721)

**Comment by Macleykun** [comment]
then there's no other way then to allow unsafe-inline for styles i'm afraid
thank you jaylinski for your insight into the chrome dev tools! gonna remove preload from stylesheets and just defer them

**Comment by paulshryock** [comment]
Yes, this is what I was getting at.

**Comment by ianjmacintosh** [comment]
@paulshryock fwiw, I'm not sure how you got the SHA256 hash you did, but I am successfully using:

```
script-src 'unsafe-hashes' 'self' 'sha256-MhtPZXr7+LpJUY5qtMutB+qWfQtMaPccfe7QXtCcEYc='
```

I generated the hash following [these instructions](https://content-security-policy.com/hash/):

```bash
$ echo -n "this.media='all'" | openssl sha256 -binary | openssl base64
MhtPZXr7+LpJUY5qtMutB+qWfQtMaPccfe7QXtCcEYc=
```

**Comment by bezoerb** [comment]
I've added a `strategy` [option]((https://github.com/bezoerb/inline-critical#inlinehtml-styles-options)) to inline-critical.
Critical defaults to `strategy: media` but you could use the default strategy to load the stylesheets without JS.

```bash
npx critical URL --inline-strategy=default
```

```js 
const {css, html, uncritical} = await critical.generate({
  src: 'URL',
  inline: {
    strategy: 'default'
  }
});
```

**Comment by paulshryock** [comment]
@bezoerb, nice, thanks for adding that flexibility. 😃

**Comment by paulshryock** [comment]
> ```
> script-src 'unsafe-hashes' 'self' 'sha256-MhtPZXr7+LpJUY5qtMutB+qWfQtMaPccfe7QXtCcEYc='
> ```
> EDIT: 🤦 Sorry, I just saw you already tried that.

@ianjmacintosh, yeah that's one of the hashes I tried. `unsafe-hashes` is part of CSP Level 3 and only supported in Chrome 69+ or Chromium Based Edge 79+. And it's, by definition, unsafe. It seems async stylesheet loading is just not compatible with a secure CSP.
