### ISSUE TITLE
Use puppeteer without libX11-xcb.so.1 possible?

### ISSUE THREAD

**Issue by LexKoomen** [addyosmani/critical#481]
Hee I use the CLI command to get the critical css for a page. However we now run into an the following issue:

Error: Failed to launch the browser process!
```/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory```

I found enough references to fix these issues by installing additional packages. 

We do not own the server and can't make any write changes at all except for the var folder.

Now my question is:
Is it maybe possible to either add these missing packages ourselfs somewhere and link to them

Or

Is is possible to add parameters to the command so these packages are not needed

We now use the following command:
```./node ~/node_modules/critical/cli.js 'https://example.com' --dimensions 500x900 --dimensions 1300x900 --no-request-https.rejectUnauthorized```

Maybe add something to the puppeteer config?

**Comment by bezoerb** [comment]
Hey @LexKoomen,
i'm sorry but i think it's not possible to run puppeteer without the required system dependencies
