### ISSUE TITLE
Handle base64 css

### ISSUE THREAD

**Issue by alexflorisca** [addyosmani/critical#489]
I found myself using critical css on a website that has base64 encoded css (don't ask why). It would be great to handle these edge cases, either by ignoring the css or parsing it. At the moment, the app throws a "File not found" error.

`<link rel="stylesheet" type="text/css" href="data:text/css;base64,Ym9keSBpbnB1dCxib2R5IHRleHRhcmVhLGJvZHkgYnV0dG9uLGJvZHkgc2VsZWN0IHtmb250LWZhbWlseTogaW5oZXJpdDt9c2VjdGlvbltkYXRhLWxheW91dGh1Yj0ic2VjdGlvbiJdLCBbZGF0YS1sYXlvdXRodWI9InNlY3Rpb24iXSAqIHtwYWRkaW5nOiAwcHg7bWFyZ2luOiAwcHg7fSp7LS1saC1mb250LWZhbWlseTogIlBvcHBpbnMiICFpbXBvcnRhbnQ7LS1saC10aXRsZS1mb250LWZhbWlseTogIlBvcHBpbnMiICFpbXBvcnRhbnQ7LS1saC1mb250LXNpemU6IDE0cHggIWltcG9ydGFudDstLWxoLWNvbG9yOiAjMTRDMzlCICFpbXBvcnRhbnQ7LS1saC1jb2xvci1yZ2I6IDIwLCAxOTUsIDE1NSAhaW1wb3J0YW50O31ib2R5IHNlY3Rpb25bZGF0YS1sYXlvdXRodWI9InNlY3Rpb24iXSB7Y29sb3I6ICM3QTdBN0E7Zm9udC1mYW1pbHk6ICJQb3BwaW5zIiAhaW1wb3J0YW50O2ZvbnQtc2l6ZTogIjE0cHgiICFpbXBvcnRhbnQ7fXNlY3Rpb25bZGF0YS1sYXlvdXRodWI9InNlY3Rpb24iXSBoMSwgc2VjdGlvbltkYXRhLWxheW91dGh1Yj0ic2VjdGlvbiJdIGgyLCBzZWN0aW9uW2RhdGEtbGF5b3V0aHViPSJzZWN0aW9uIl0gaDMsIHNlY3Rpb25bZGF0YS1sYXlvdXRodWI9InNlY3Rpb24iXSBoNCwgc2VjdGlvbltkYXRhLWxheW91dGh1Yj0ic2VjdGlvbiJdIGg1IHtjb2xvcjogIzFBMUExQjtmb250LWZhbWlseTogIlBvcHBpbnMiICFpbXBvcnRhbnQ7fSBpbWcubGgtbGF6eTpub3QoW3NyY10pIHt2aXNpYmlsaXR5OiBoaWRkZW47fQ==" media="all">`

**Comment by bezoerb** [comment]
Base64 support landed in [v3.1.0](https://github.com/addyosmani/critical/releases/tag/v3.1.0)
Sorry @alexflorisca, must have missed this issue while looking at your [PR](#496)  :)
