### ISSUE TITLE
Bad configuration or bug?

### ISSUE THREAD

**Issue by NizarBlond** [addyosmani/critical#491]
I want to extract critical CSS for a website with this simple script

`
  const fs = require('fs')
  const path = require('path');
  const critical = require('critical');
  const outputDir = path.resolve(__dirname, './output');
  const inputUrl = 'https://ashkarwinery-sandbox.mha9ui.ap-southeast-2.wpstaqhosting-sandbox.com';
  
  const options = {
    base: './output',
    target: './critical.css',
    src: inputUrl,
    width: 1300,
    height: 900,
  };
  critical.generate(options, function(err, data) {
    if (err) {
      console.log('error: ', err);
      return;
    }
    console.log('OK!', data);
  });
`

However, the result is huge in critical.css, in many cases it is like 50000+ chars while https://www.sitelocity.com/critical-path-css-generator and other generators give 10% of the chars and are closer to the critical CSS displayed on Chrome.

What am I missing?

**Comment by bezoerb** [comment]
Hey @NizarBlond,
thanks for the issue :)

There was a bug fixed in (v3.0.1)[https://github.com/addyosmani/critical/releases/tag/v3.0.1]
Now the critical css should be half the size. 
I'll try to look into this later to see if i can find more *bugs*.

**Comment by bezoerb** [comment]
I'm closing this due to lack of feedback.
Feel free to reopen if there are new insights
