### ISSUE TITLE
vulnerabilities with dependencies

### ISSUE THREAD

**Issue by mykola-shkut** [addyosmani/critical#494]
![image](https://user-images.githubusercontent.com/50704732/117961847-41903b80-b327-11eb-8f4d-6d167200027b.png)
last version has 4 vulnerabilities 
could you change the dependencies?

**Comment by bezoerb** [comment]
Fixed in [v4.0.0](https://github.com/addyosmani/critical/releases/tag/v4.0.0)

**Comment by mykola-shkut** [comment]
now I see vulnerabilities with **css-what** and **normalize-url**
@bezoerb could you fix it?
