### ISSUE TITLE
 Error: PostCSS plugin postcss-discard requires PostCSS 8.

### ISSUE THREAD

**Issue by the-prodigy** [addyosmani/critical#499]
Error: PostCSS plugin postcss-discard requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users

My code:

critical.generate({
            inline: true,
            base: websitePath,
            src: 'index.html',
            target: 'index-critical.html'
          });

what did I wrong ?

@bezoerb @addyosmani

**Comment by bezoerb** [comment]
Hey @the-prodigy,
i accidentally released a breaking change as patch version on postcss-discard yesterday. 
I've deprecated the version and released a new patch version without the breaking change.
I guess you're still using critical v2.x as v3 already requires postcss 8.

When you npm install again everything should be working now. 
Sorry for the inconvenience and thanks for reporting the issue :)

**Comment by the-prodigy** [comment]
@bezoerb Alright I will try it!

Btw, can I make like 

src: *.html 

So I can find all html files?

**Comment by the-prodigy** [comment]
@bezoerb 

postcss-discard: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration

... -.-

My command to install:

npm i critical --save

**Comment by the-prodigy** [comment]
@bezoerb Now I receive a other error when I add inlineImages and maxImageFileSize attribute:

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Buffer
    at validateString (internal/validators.js:124:11)
    at Object.dirname (path.js:583:5)
    at C:\Projects\flashsites\flowhub\flowhub\node_modules\critical\src\core.js:154:73
    at Array.reduce (<anonymous>)
    at create (C:\Projects\flashsites\flowhub\flowhub\node_modules\critical\src\core.js:154:37)

**Comment by the-prodigy** [comment]
Also, the inlining part works now, but it doesnt really inline the css file, rather it makes the css from

<link href="....min.css" rel="stylesheet" type="text/css">

to

media="print" onload="this.media='all'"

Which is not inlining. Inlining is when you put the css file in the html file which speeds up heavy the website

**Comment by bezoerb** [comment]
I'm currently rewriting inline-critical to allow more inclining variants. When I'm done with this I'll bump the Version in critical and the deprecation warning should go away. Can you send a link to the sources so I can check the inclining issue?

**Comment by bezoerb** [comment]
media="print" onload="this.media='all'" is just to asynchronous load the complete css. The critical styles should be inclined in a style tag

**Comment by the-prodigy** [comment]
Unfortunately, I need that the whole CSS file gets inlined not only the critical part. That would speed up crazy the Website for everyone.

**Comment by bezoerb** [comment]
@the-prodigy: The point with critical css is that just the css required for the initial viewport gets inlined while the rest of the css is loaded non-blocking. Considering performance, this should be even better unless the whole css is small enough.

When you want to inline the whole css you m
