### ISSUE TITLE
no output / errors / processing occurs  when running a simple critical task

### ISSUE THREAD

**Issue by propertunist** [addyosmani/critical#50]
i have created a gulpfile.js within my working folder here, which contains:

```
// Include gulp
var gulp = require('gulp'); 
var critical = require('critical');

// Generate Critical-path CSS
gulp.task('critical', function (cb) {
    critical.generate({
        base: '/',
        src: 'mypage.html',
        dest: 'styles/main.css',
        width: 320,
        height: 480
    });
});
```
and i have (as far as i am aware) correctly installed the github master project for critical, as well as gulp, node and npm.
i have just tested by adding the optional 'css' config variable into the critical task function too - though this didn't make any difference either.

i'm out of ideas here, does  anyone know what i might be missing?
the output of the terminal is:
```
$ gulp critical
[11:04:36] Using gulpfile /mypath/critical-working/gulpfile.js
[11:04:36] Starting 'critical'...
```

**Comment by bezoerb** [comment]
Tested against `master`
* downloaded homepage from www.ureka.org as a complete file
* put inlined styles in separate css files 
* run `cat index.html | node ~/GitHub/critical/cli.js -im > test.html`

Everthing went fine except that i was asked if phantomjs is allowed to access `https://assets.swarmcdn.com``

**Comment by propertunist** [comment]
ok i am v. busy here presently, but will come back to this asap. thanks
