### ISSUE TITLE
vulnerabilities with "css-what" module

### ISSUE THREAD

**Issue by mykola-shkut** [addyosmani/critical#503]
after updating to v4.0.0 I have vulnerabilities with **css-what**
![image](https://user-images.githubusercontent.com/50704732/121473759-ce342500-c9cb-11eb-8a3a-bfe56bbfe389.png)
@bezoerb could you fix it?

_Originally posted by @mykola-shkut in https://github.com/addyosmani/critical/issues/494#issuecomment-858336569_

**Comment by bezoerb** [comment]
Hehe seems like there are new vulnerabilities popping out of nowhere every day. I'll take a look
