### ISSUE TITLE
Noscript inline styles are overriding stylesheets

### ISSUE THREAD

**Issue by jameslk** [addyosmani/critical#507]
Thank you for all the hard work done on this wonderful library. I recently upgraded to the latest version of this library (v4) and it looks like inline styles are being included in the generated critical CSS where as this was not the case before (from https://github.com/addyosmani/critical/commit/3ed099cb8e387523a82b7a7baf3e7063dc02b073). Unfortunately for me, this means inline CSS included in `<noscript>` tags is making it into the generated critical CSS and overriding stylesheet CSS. Is there any way to disable the inclusion of inline CSS? An option for this seems like it would be pretty important. Thank you!

**Comment by bezoerb** [comment]
Hey @jameslk 
sorry for the very late response :/
Don't know if this is still relevant for you but i've added an option to ignore inlined stylesheets in the linked PR

**Comment by bezoerb** [comment]
Option is available in [v5.1.0](https://github.com/addyosmani/critical/releases/tag/v5.1.0)
