### ISSUE TITLE
Why use java script to unblock css?

### ISSUE THREAD

**Issue by markusfalk** [addyosmani/critical#508]
Hey there, 

I was wondering why critical uses javascript to switch from media="print" to media="all" instead of just moving the styles to the end of body. Do I have to wait for onload to unblock styles? 

### Why this ... 

```html
<!doctype html>
<html lang="en">
  <head>
    <title>Critical</title>
    <style>.foo {color: red}</style>
    <link rel="stylesheet" href="css/main.123.css" async="" media="print" onload="this.media='all'">
  </head>
  <body>
    <h1>Critical</h1>
    <noscript><link rel="stylesheet" href="css/main.123.css" async=""></noscript>
  </body>
</html>
```

### not this?

```html
<!doctype html>
<html lang="en">
  <head>
    <title>Critical</title>
    <style>.foo {color: red}</style>
  </head>
  <body>
    <h1>Critical</h1>
    <link rel="stylesheet" href="css/main.123.css" async>
  </body>
</html>
```

**Comment by bezoerb** [comment]
You can pass inline options to configure the preload strategy:
https://github.com/bezoerb/inline-critical#inlinehtml-styles-options

See https://github.com/addyosmani/critical/issues/480#issuecomment-855470176

**Comment by markusfalk** [comment]
@bezoerb thanks, looking good. 
I am more interested in the why than the how. 
I don't quite get the benefit of the one over the other 🤔

**Comment by bezoerb** [comment]
Hehe, ok :)
We initially used `loadCSS` to defer the loading of the CSS. With the release of [v3](https://github.com/filamentgroup/loadCSS#changes-in-version-30-no-more-preload-polyfill) the recommended pattern changed to `<link rel="stylesheet" href="/path/to/my.css" media="print" onload="this.media='all'; this.onload=null;">`.
From my perspective this was fine until we got issues with CSP so i added other preload strategies to inline critical.

As far as i understand, the pattern provided by filamentgroup brings the best loading experience as the print stylesheet is loaded early in a nonblocking manner whereas with the non-js approach (putting the link tag at the end of the document body), the final css might be available a bit later but won't cause headaches concerning CSP ;)

**Comment by markusfalk** [comment]
So for everyone interested, @bezoerb pointed me in the right direction. You can read all about the why in more detail here: https://www.filamentgroup.com/lab/load-css-simpler/

thanks 🤓
