### ISSUE TITLE
Is it possible to pass ignore option to command line?

### ISSUE THREAD

**Issue by markusfalk** [addyosmani/critical#511]
I'm not sure wether this is a command line questions or a critical question. 

I tried passing `--ignore` options via command line but it still extracts `@font-face`-rules to the inline style which breaks lighthouse rule "Ensure text remains visible during webfont load" even when using `font-display: swap`. 

```json
scripts: {
  "critical": "critical ./dist/index.html --base ./dist --ignore={atrule: ['@font-face']} --extract=true --inline > ./dist/critical.html",
}
```

Same when using quotes: `--ignore='{atrule: ['@font-face']}'`

What I like to achive is that all `@font-face`-rules are ignored when extracting styles from the css file. 

any help would be appreciated :)

**Comment by bezoerb** [comment]
See https://github.com/addyosmani/critical/issues/518#issuecomment-927903104
