### ISSUE TITLE
Error prepending parent directory to non-relative URL paths

### ISSUE THREAD

**Issue by delucis** [addyosmani/critical#519]
I have a CSS file that loads a font via a root-relative URL, e.g. something like this

```css
/* ./css/style.css */
src: url('/css/assets/font.woff2') format('woff2');
```

This is included in an HTML file that is processed using `critical` (simplified example):

```html
<!-- ./index.html -->
<link href="/css/style.css" />
```

`critical` inlines the font URL as:

```css
src: url('/css/css/assets/font.woff2') format('woff2');
```

Note the double prefix `/css/css`.

I’m guessing maybe there’s some logic somewhere that prepends relative URLs with the path to the CSS file to maintain path integrity when inlining the CSS, but that this logic doesn’t account for root-relative URLs starting with `/`, which should behave the same across locations.

---

Here are the options I’m passing to `critical` in case that’s helpful:

```js
critical.generate({
  base: 'dist/', // this is my build directory
  html: content, // a string containing index.html
  inline: true,
  dimensions: [/* ... */],
})
```

**Comment by dineshtrivedi** [comment]
I am having the same issue. Have you found a solution @delucis

**Comment by delucis** [comment]
@dineshtrivedi I ended up making my font URLs relative. So with the following files

- `/css/fonts.css`
- `/css/fonts/font.woff2`

I updated the `fonts.css` like this:

```diff
-  src: url('/css/fonts/font.woff2') format('woff2');
+  src: url('fonts/font.woff2') format('woff2');
```

**Comment by dineshtrivedi** [comment]
Thank you, I use the [rebase option](https://github.com/addyosmani/critical#generate-critical-path-css-and-specify-asset-rebase-behaviour) to solve my issue.

Thank you for your response @delucis
