### ISSUE TITLE
Why do 3 developers running the same task generate different results?

### ISSUE THREAD

**Issue by timbednar** [addyosmani/critical#521]
I bet this is a complicated answer. But we use critical on a large team and recently had an issue where there different developers ran the same gulp task on the same code in master and the results were slightly different. Not hugely different, but different. Which can matter.

I'm sure this is a complicated thing -- but any ideas?

**Comment by bezoerb** [comment]
Hey @timbednar,
sorry for the late response. This seems like a very complicated issue to trace ;)
Maybe there are some slight differences in module versions of the used libraries inside `node_modules` or some user specific settings messing with the headless chrome instance used by penthouse to generate the critical css?

These would be the first things i would check when i were facing this problem.

**Comment by bezoerb** [comment]
@timbednar: Any updates on this?

**Comment by bezoerb** [comment]
I'm closing this due to lack of feedback.
Feel free to reopen if there are new insights
