### ISSUE TITLE
simplify usage of critical

### ISSUE THREAD

**Issue by bezoerb** [addyosmani/critical#53]
@addyosmani 
While implementing some tests for the CLI i've stumbled across parameter inconsistence between `generate` and `generateInline`. For `generateInline`we use `styleTarget` and `htmlTarget` and for `generate`we only use `dest`. This could be a bit confusing.
Maybe we should consider deprecating the options `styleTarget` and `htmlTarget` in favor of just using `dest` and and select the right task based upon the filetype
* html: generateInline
* css: generate

With this is mind we could also strip down `generate`and `generateInline` because then only one public method is needed for either generate and inline to produce html or for just generating the critical css. What do you think?

**Comment by bezoerb** [comment]
What about adding `inline` as an option for `generate`, deprecate `generateInline` and leave only the `dest` option.
So we would only expose the `generate` method and do inlining when the `inline` option is set.

**Comment by bezoerb** [comment]
Started on another [branch](https://github.com/addyosmani/critical/tree/deprecated) 
This one is currently blocked by https://github.com/pocketjoso/penthouse/issues/53
See: https://travis-ci.org/addyosmani/critical/jobs/59405654

**Comment by bezoerb** [comment]
merged in master, so this could be closed

**Comment by asuh** [comment]
This ticket took me a while to find, and it's good to know, but [looking at the Critical Path CSS Demo](https://github.com/addyosmani/critical-path-css-demo) makes it appear think `styleTarget` and `htmlTarget` are the way to go and not deprecated.
