### ISSUE TITLE
ConfigError Minify not allowed

### ISSUE THREAD

**Issue by ruvesa** [addyosmani/critical#535]
while running my script by `node criticalcss.mjs` it says "ConfigError Minify not allowed"

**Comment by bezoerb** [comment]
The minify option was removed in version 4.0.0

**Comment by ruvesa** [comment]
Yes. I have gone through the previous threads. But if it is removed then why it is throwing that error? My script does not have minify option and still getting that error.

> The minify option was removed in version 4.0.0

**Comment by bezoerb** [comment]
Can you share the contents of your criticalcss.mjs file?

**Comment by bezoerb** [comment]
I'm closing this due to lack of feedback.
Feel free to reopen if there are new insights
