### ISSUE TITLE
Async loaded CSS stylesheets and embedded CSS

### ISSUE THREAD

**Issue by khalwat** [addyosmani/critical#54]
So I'm using critical to generate critical path CSS for my website, which I embed into web pages as embedded stylesheets.  Then I load the full CSS later on via loadCSS();  All is great so far.

However, I'm using Bootstrap; so let's say there is a Bootstrap declaration such as:

```
.alert { border-radius: 5px; }
```

...which gets embedded into my webpage because it's used in the above the fold content.

Further down the page, in below the fold content, I have HTML that looks like this:

```
 <div class="alert my_alert"></div>
```

...which the CSS style my_alert being:

```
 .my_alert { border-radius: 15px; }
```

So the problem here is that the embedded CSS for "alert" is overriding the "my_alert" style that's applied via my async loaded CSS, so border-radius ends up staying set to 5px;

Is there a way to handle this reasonably?

**Comment by rosslavery** [comment]
Can you elaborate on your solution to this? It looks like your sentence was cut off.

I'm encountering the exact same issue. The inlined css of above-the-fold styles is impacting the classes that override those styles in the below-the-fold content.

**Comment by bezoerb** [comment]
Take a Look here https://github.com/bezoerb/grunt-critical/issues/5

**Comment by rosslavery** [comment]
Hey @bezoerb , thanks for the link. My fix was the same.

**Comment by khalwat** [comment]
Yeah so basically, it was working as expected. But I was using loadCSS() to async load the full CSS later on. The problem is that by default loadCSS() puts the style sheet in front of the first script tag it encounters in the head

So because of where the first script tag was in my html head tags, it was loading the full CSS before the inline CSS from grunt-critical... so the full CSS would never override the inline critical CSS.

Moving the tags around fixed the loading order, and thus fixed the issue.

**Comment by biokillos** [comment]
I have the same issue, but cannot reorder script tags, i.e. having cloudflare or browser extensions that push them at the top. loadCSS() has a useful argument that allows to point an element and inserts all stylesheets before it. So the questions are:

1. Can I pass the argument?
or
2. Can I inline css in HTML, but withous using 'yours' loadCSS() and instead use 'mine' with the argument, stylesheets passed

**Comment by biokillos** [comment]
@bezoerb anything?

**Comment by bezoerb** [comment]
@biokillos sorry for the late response. I've just released a new [`inline-critical`](https://github.com/bezoerb/inline-critical) version which enables you to either pass in an selector for the `before` element or just skip `loadCSS` by ignoring all `link` tags. `link` tags inside of `noscript` will be ignored by default so in case you're using loadCSS already and there are no link tags left it should just be fine. The options won't be passed through `critical` yet so you'll have to generate the critical css first and inline it via `inline-critical` in the next step. 
Hope this helps
