### ISSUE TITLE
critical just stucks at loading and does nothing

### ISSUE THREAD

**Issue by TerrenceAddison** [addyosmani/critical#542]
Hi I'm using gulp to run critical and everytime I run it just stays stuck. Code for `gulpfile.js` as below:

```
var critical = require("critical");

function defaultTask(cb) {
  critical.generate({
    inline: true,
    base: "./",
    src: "index.html",
    target: "index-critical.html",
    width: 1300,
    height: 900,
  });
  cb();
}

exports.default = defaultTask;
```

I run it using `gulp` and this is the only thing that happens:
![image](https://user-images.githubusercontent.com/63777677/185180782-513f44e6-89ed-40c1-bdf6-cdc31cab814d.png)

Please do inform me if you need more context, thank you

**Comment by bezoerb** [comment]
Hey @TerrenceAddison, more context would be helpful.
Have you already tried to use the `stream` export as described here: https://github.com/addyosmani/critical#gulp

If using it this way i guess you need to wait for critical to complete before calling the `cb()` callback

**Comment by bezoerb** [comment]
I'm closing this due to lack of feedback.
Feel free to reopen if there are new insights
