### ISSUE TITLE
'noscript)>[rel="stylesheet"]' is not a valid selector

### ISSUE THREAD

**Issue by xtianares** [addyosmani/critical#559]
I tried  a few configuration changes but nothing is fixing it so I started removing some of the HTML elements on a test project and found that anytime I have a `<link>` element on a page it will result to this error: 

```
'noscript)>[rel="stylesheet"]' is not a valid selector
```

```
critical({
      base: paths.site.dest,
      inline: true,
      css: [/path/to/css/files],
      penthouse: {
        forceInclude: ['#selector'],
        timeout: 90000,
        pageLoadSkipTimeout: 30000,
        renderWaitTime: 500,
      },
      dimensions: [{
        width: 1400,
        height: 1200
      }]
    })
```

**Comment by diebevares** [comment]
I solved the issue commented:
`inline: true`

**Comment by braco** [comment]
I think Netlify's "netlify-plugin-inline-critical-css" plugin uses this package? It recently started throwing this error and breaking builds.

**Comment by bezoerb** [comment]
i guess this needs to be handled upstream in https://github.com/bezoerb/inline-critical/issues/300

**Comment by bezoerb** [comment]
can someone please provide a failing example/test for this issue? i tried reproducing the error using `inline-critical` as well as `critical` but everything runs smoothly as expected.
