### ISSUE TITLE
Test are failing

### ISSUE THREAD

**Issue by bezoerb** [addyosmani/critical#56]
Since the last release of `penthouse` (0.2.52) https://github.com/pocketjoso/penthouse/commit/704c29490d8bba398f6a3f232d0e83006f25e39a all tests are failing.
It looks like we get a totally different critical css now.
We should lock the last working penthouse version (0.2.51) 
/cc @pocketjoso

**Comment by bezoerb** [comment]
Created an issue at `penthouse`
https://github.com/pocketjoso/penthouse/issues/37

**Comment by bezoerb** [comment]
hey @addyosmani,
i think we need a version bump to get critical back running.

**Comment by sindresorhus** [comment]
https://github.com/addyosmani/critical/releases/tag/v0.5.2

**Comment by bezoerb** [comment]
Thanks

**Comment by pocketjoso** [comment]
Resolved in `Penthouse 0.6.0`.

**Comment by addyosmani** [comment]
All 29 tests are passing locally using 0.2.53. @bezoerb @sindresorhus if one of you can verify too, we should be good to update.

**Comment by sindresorhus** [comment]
@addyosmani Yup https://github.com/addyosmani/critical/releases/tag/v0.5.3

**Comment by bezoerb** [comment]
I'll try this evening

**Comment by bezoerb** [comment]
@addyosmani All tests are passing on Windows & OSX. Tests for grunt-critical passing, too.
