### ISSUE TITLE
Generate ciritical for multiple pages

### ISSUE THREAD

**Issue by nikunp** [addyosmani/critical#560]
Is there a way to generate critical for multiple pages in batches so there are no errors

**Comment by devtombiz** [comment]
If this is not too late, look here:
https://github.com/addyosmani/critical/issues/575
I wanted to do the same thing but was having puppeteer errors.
Note: the 2nd solution is better IMHO, the 1st is slower but works too.

**Comment by bezoerb** [comment]
Thanks @devtombiz :)
Awesome solution 🚀
