### ISSUE TITLE
Does not take redirects into account when looking for relative CSS

### ISSUE THREAD

**Issue by khaxan** [addyosmani/critical#565]
If I try to get the critical CSS for the website https://cbslocal.com/ I get the following error:

```
Error: File not found: /fly/bundles/cbsnewscontent/css/door.min.css?v=181d27d1e918a6408b48ea2e220df310
       Current working directory: /critical-css
       Searched in: https://cbslocal.com, https://cbslocal.com/, /critical-css
```

And the reason is that the domain name redirects to https://www.cbsnews.com/cbslocal/

The CSS file is alive and well at https://www.cbsnews.com/cbslocal/fly/bundles/cbsnewscontent/css/door.min.css?v=181d27d1e918a6408b48ea2e220df310

But this package is looking in the wrong place.

**Comment by bezoerb** [comment]
@khaxan: would you please check [`v6.0.1`](https://github.com/addyosmani/critical/releases/tag/v6.0.1)? :)

**Comment by bezoerb** [comment]
closing this as it should be resolved. Feel free to re-open if there are related issues
