### ISSUE TITLE
Does not take the <base HTML tag into account when looking for relative CSS

### ISSUE THREAD

**Issue by khaxan** [addyosmani/critical#566]
If I try to find the critical CSS for https://www.ikea.com/ I get the following error:

```
Error: File not found: styles-b3b8d77f-5e9k8p.css
       Current working directory: /
       Searched in: https://ikea.com, https://ikea.com/, /
```

The correct URL where it should be looking is https://www.ikea.com/global/en/styles-b3b8d77f-5e9k8p.css because there is a <base tag in the markup that points to https://www.ikea.com/global/en/ so all CSS should use that as the base.

**Comment by bezoerb** [comment]
@khaxan: could you please try again with [v5.2.0](https://github.com/addyosmani/critical/releases/tag/v5.2.0)?

**Comment by bezoerb** [comment]
Seems to work ;)
Feel free to reopen you you still have issues

**Comment by SCZone1** [comment]
Still not working 😕

**Comment by SCZone1** [comment]
I'm sorry, I don't know how I was tagged into this email. I'm having issues
with a different platform, and it's been pure frustrating because now they
stopped replying to me.

**Comment by khaxan** [comment]
Hey @bezoerb, thanks for acting on it so quickly. I haven't had a chance to recheck but will try to do it soon.

Any chance this one could get the same love, it is also quite prevalent: https://github.com/addyosmani/critical/issues/565

**Comment by bezoerb** [comment]
Already working on it 😊
