### ISSUE TITLE
dimensions don't work

### ISSUE THREAD

**Issue by mschoenlaub** [addyosmani/critical#574]
With critical 6.0.4, setting `--dimensions` in the CLI doesn't seem to work. 

<img width="985" alt="Screenshot 2023-10-17 at 3 34 08 PM" src="https://github.com/addyosmani/critical/assets/3697357/1ff87158-a86f-4c65-be1d-bf7605c090f3">

**Comment by bezoerb** [comment]
Hey @mschoenlaub, if you only want to specify dimensions for one viewport you could use this:
```
manuel. schonlaub@PRODIGYMAC-C02G13RGML85 mschoenlaub.github.io % cat public/index.html | critical --width 1280 --height 1024
```

**Comment by bezoerb** [comment]
if you want to specify multiple dimensions this could be done like this:
```
cat public/index.html | critical --dimensions 800x600 --dimensions 1280x1024
```
