### ISSUE TITLE
*Ignore 

### ISSUE THREAD

**Issue by jimmyjamieson** [addyosmani/critical#58]
Is there any way to ignore specific css or images/fonts in the inlined css.

For example, I have a font that gets inserted into the inlined critial css due to it being part of an icon in the header. I don't want the font to load at all, until the page has loaded.

Is there anyway to make criticalcss ignore specific files for include?

**Comment by bezoerb** [comment]
Until now there is no way to ignore specific selectors but you can specify which css files to use. 
As a workaround you could define the font in a separate css file and concat this after you applied critical.

**Comment by alanontheweb** [comment]
+1 for ignoring specific stylesheets. I specified which CSS file to use but it doesn't seem to be using that information to ignore the other...

**Comment by rupl** [comment]
I think ignoring specific stylesheets is a big ask, and often people are concatenating everything together like @bezoerb said. Some sort of rule for excluding specific properties would be grand, e.g. exclude `font-face` blocks, anything with `url` as a value, etc.

My current workflow just includes a small test to scan the generated file for these problematic strings so I don't accidentally ship them.

**Comment by bezoerb** [comment]
I've just released [`filter-css`](https://github.com/bezoerb/filter-css). A small module to filter out css rules.
We could add an `ignore` option to critical and use `filter-css` to remove the ignored rules from the critical css.

**Comment by oliverfarrell** [comment]
+1 for this. Currently get some print media queries returned so would be useful to ignore specific media queries at the very least.

**Comment by bezoerb** [comment]
@oliverfarrell wanna give it a try?

**Comment by bezoerb** [comment]
Seems to work ;)
#88
