### ISSUE TITLE
Allowing internal functions to be imported

### ISSUE THREAD

**Issue by khaxan** [addyosmani/critical#583]
Hey @bezoerb, the internal functions that resolve the CSS for a page e.g. getDocument and getDocumentFromSource are quite useful for my project, any chance they could be made available to the outside world by adding the relevant files to "exports" in package.json?

I know it's a long shot but thought I'd ask before looking for a separate package that does this, or creating my own implementation 😃

Thanks so much!

**Comment by bezoerb** [comment]
Hey @khaxan, I think this shouldn't be a problem.

**Comment by khaxan** [comment]
Hey [bezoerb](https://github.com/bezoerb), that sounds great, how do we proceed?

**Comment by bezoerb** [comment]
hey @khaxan :)
wanna try [v6.0.5](https://github.com/addyosmani/critical/releases/tag/v6.0.5) ?
