### ISSUE TITLE
HEAD requests are not using the provided request headers

### ISSUE THREAD

**Issue by frogleon** [addyosmani/critical#592]
Request options passed as part of the initial "HEAD" request to verify if there is a redirect from the original provided URL are not the ones specified in the initial configuration. This could lead to discrepancies across GET and HEAD requests when specific headers are required (even as part of the HEAD request).

**Comment by bezoerb** [comment]
Hey @frogleon 
thanks for submitting this issue. Can you give an example?

**Comment by frogleon** [comment]
Hi @bezoerb , thanks for you answer!

I don't have one, unfortunately. However, let's take for example, this situation:

There is an auth-only URL endpoint that accepts headers as part of the request and grabs the credentials from there; if the auth fails (missing/invalid credentials), there is a 301 redirect to the application's login page.

In this case, the expectation would be that the specified headers are used for the request to succeed.

What is happening is that this HEAD request exists in the code (see: src/file.js:795) and does not use the specified headers before the GET request. The final URL collected would be the login page, not the expected one. Therefore, it will create the wrong critical CSS content.

I hope this helps clarify the issue.

Thank you again!

**Comment by gman-wa** [comment]
I can second this issue - we set a custom userAgent for got that was only working half the time, and one of my team noticed all the requests with the default got user agent were all HEAD requests.   GETs were all using the custom user agent.

**Comment by bezoerb** [comment]
Hey @frogleon 
i just released patch version [v7.1.2](https://github.com/addyosmani/critical/releases/tag/v7.1.2) which should fix the issue.
Can you please try again?

**Comment by gman-wa** [comment]
@bezoerb - it's working for me - thanks!

**Comment by frogleon** [comment]
Thanks!
