### ISSUE TITLE
Move the tmp css file into a .tmp folder?

### ISSUE THREAD

**Issue by KingScooty** [addyosmani/critical#60]
It appears that critical generates a `tmp-.css` file in the base directory while it's running. Annoyingly for me, this file is getting picked up on tasks that run after (if chained as a dependency).

It's showing up in my cache manifest file :(

Is there any chance we can get it to generate inside a `.tmp` folder? At least that way i can set gulp-manifest to ignore that folder.

**Comment by sindresorhus** [comment]
It should be generated in an `os.tmpdir()` folder instead so it's not littering up the project folder. Maybe using: https://github.com/sindresorhus/tempfile

**Comment by KingScooty** [comment]
Hmm. Well it's definitely littering my project folder, and stays long enough to affect tasks running after it :/

**Comment by bezoerb** [comment]
i'm working on a pull request

**Comment by KingScooty** [comment]
@bezoerb Awesome!

**Comment by bezoerb** [comment]
unfortunately we only can use `tempfile` for the temporary generated stylesheets.
Critical also creates temporary html files when the html option is used instead of src.
These files need to be inside the base directory.

@KingScooty could you try the PR branch and see if this fixes your issue?

**Comment by KingScooty** [comment]
@bezoerb Yep, that sorts my issue right out! :+1:
