### ISSUE TITLE
Noscript tag is not generated

### ISSUE THREAD

**Issue by kristijan11b** [addyosmani/critical#602]
Version: 7.2.0

```
const { html } = await generate({
      inline: {
        strategy: 'media',
        noscript: 'body',
      },
      src: path,
      base: distPath,
      width: 1440,
      height: 1080,
})
```

This produces link with valid strategy:
`<link href="/assets/index.9ZZiJ3aT.css" rel="stylesheet" media="print" onload="this.media='all'">`

But the noscript is missing.
Any idea why?

**Comment by bezoerb** [comment]
hey @kristijan11b,
thanks :)
There seems to be an issue in `inline-critical` when the html is minified.
I opened an issue and i'm trying to fix this as soon as possible.

**Comment by bezoerb** [comment]
@kristijan11b 
can you please try again on the current master branch?

**Comment by bezoerb** [comment]
i've just released a new version. 
You could also try with `v7.2.1`

**Comment by kristijan11b** [comment]
@bezoerb Awesome, it works like a charm! Thanks!
