### ISSUE TITLE
npm test exits with 0 even when tests fail

### ISSUE THREAD

**Issue by samccone** [addyosmani/critical#67]
@bezoerb and I found this nasty little surprise this morning. Something that we should investigate and fix.

https://travis-ci.org/addyosmani/critical/jobs/51025275
^^

**Comment by samccone** [comment]
Upon further thought, it looks like the CLI testing is masking the exit status of mocha since it is calling process.exit when it prints the help output.

:crying_cat_face:

**Comment by bezoerb** [comment]
Thanks, I'll take a look at it

**Comment by bezoerb** [comment]
Should not be closed by comment

**Comment by addyosmani** [comment]
Ah. Sorry we didn't catch this sooner. Hoping we can nail the exit code issue. Thanks for looking at the tests @bezoerb!

**Comment by bezoerb** [comment]
Exit codes should be fixed with c469c030524b0e3b16164279940d41a12bf450cd

**Comment by samccone** [comment]
![](http://giphy.com/gifs/reaction-bill-oreilly-fuck-it-tHdS8HFtuawZa)

**Comment by samccone** [comment]
![](http://i.ytimg.com/vi/eUFY8Zw0Bag/hqdefault.jpg)

**Comment by addyosmani** [comment]
\o/
