### ISSUE TITLE
Use larger viewport dimensions in examples

### ISSUE THREAD

**Issue by pocketjoso** [addyosmani/critical#69]
The critical css generated by tools like `Penthouse` in almost all case works well for all dimensions **up to** the dimension asked for - but not higher. This means that if you want to cover all grounds, you should ask for the highest possible dimensions you want to include styles for "above the fold" elements for. The downside then is that your critical css will include styles for elements not seen (above the fold) for the majority of your users, which is why `Penthouse`'s default takes the compromise at `1300x900` (yes, quite arbitrary choice).

`critical` however uses `480x320` in it's examples - which would leave out styles needed for many non mobile viewports. I don't think this a sensible default - we should increase the dimensions specified to `1300x900`, or something around there.

**Comment by addyosmani** [comment]
Thanks for weighing in @pocketjoso. I'm personally in favour of bumping the dimensions up to a higher default. cc'ing @sindresorhus @bezoerb for their take before we make any changes here.

**Comment by bezoerb** [comment]
I'm fine with higher defaults :+1:

**Comment by sindresorhus** [comment]
Sure
