### ISSUE TITLE
Critical CSS and CSS animations / Bootstrap Carousel

### ISSUE THREAD

**Issue by khalwat** [addyosmani/critical#73]
I've been using and loving grunt-critical, thank you!

I do have one issue that I can't quite figure out.  I have a site that has critical CSS for all of the pages, and it works great... but for pages that have CSS animations on them in form of Twitter Bootstrap carousel animations it's not quite doing the trick.

Here's an example URL:

http://www.onlinelandusa.com/listings/colorado-land-6.458-acres-with-a-driveay-and-cleared-level-area

There some CSS in there that critical isn't picking up on, because PageSpeed Insights says:

"Approximately 19% of the above-the-fold content on your page could be rendered without waiting for  the following resources to load. Try to defer or asynchronously load blocking resources, or inline the critical portions of those resources directly in the HTML.

http://cssjs.onlinelandusa.net/site_assets/css/site.combined.min.css"

Somehow critical isn't picking up on all of the CSS that needs to be rendered, so it has to wait to load the full CSS file before it can render the above-the-fold content.  There is a similar result on an even simpler page:

http://www.onlinelandusa.com/site/about-us

...that just has one carousel animation on it, so I'm assuming that's what is doing it.  You can see the extracted critical CSS here:

http://www.onlinelandusa.com/site/css/about_us_critical.min.css

**Comment by rasteiner** [comment]
I'm having a similar problem. I don't think it's strictly related to bootstrap, I just think it doesn't include the `@keyframes` declarations that are used. I guess this "bug" might actually come from [penthouse](https://github.com/pocketjoso/penthouse) and not critical...

**Comment by pocketjoso** [comment]
I pushed a new patch yesterday for penthouse to keep critical animation declarations and `@keyframes` - [0.9.10](https://github.com/pocketjoso/penthouse/releases/tag/v0.9.10).

If you manually remove your installed `penthouse`/`critical` folder in your `node_modules` (depending on whether you are on `npm@3` or lower) and then re-do `npm install` you should get the latest `penthouse` version, with this fix.

Let me know if that solves your issues (not sure it will solve all of them, but least keyframes should remain, if they are critical).

**Comment by bezoerb** [comment]
Should be fixed by now as we're on penthouse 0.10.9
