### ISSUE TITLE
Bump clean-css

### ISSUE THREAD

**Issue by bezoerb** [addyosmani/critical#74]
We got an issue over at grunt-critical with conflicting versions of `clean-css`. See https://github.com/bezoerb/grunt-critical/issues/11 

I think bumping `clean-css` in `critical` would be the most simple fix for this

**Comment by addyosmani** [comment]
Here's a list of our currently outdated deps:

```
cli (package: ^0.6.5, latest: 0.6.6)
cheerio (package: ^0.18.0, latest: 0.19.0)
clean-css (package: ^2.2.4, latest: 3.1.9)
imageinliner (package: ^0.2.2, latest: 0.2.3)
oust (package: ^0.2.0, latest: 0.2.3)
penthouse (package: 0.3.0, latest: 0.3.1)
tmp (package: 0.0.24, latest: 0.0.25)
inline-critical (package: ^0.1.0, latest: 0.1.2)
```

Is there anything else we should bump along with this?

**Comment by bezoerb** [comment]
Done.

**Comment by sindresorhus** [comment]
Only `cheerio`, `clean-css`, `tmp` needs updating though. The other ones semver match latest.

**Comment by bezoerb** [comment]
thanks sindre, although it's too late (1dd89b63292e88967bc7e86080ab2d6d6705ff28) ;)
I would complete appveyor integration for tests on windows later this day and then we should be fine for a new patch version.

**Comment by bezoerb** [comment]
https://github.com/addyosmani/critical/releases/tag/v0.5.7
