### ISSUE TITLE
Unicode Hex in generated *.html

### ISSUE THREAD

**Issue by martindrzka** [addyosmani/critical#78]
Generated output for index-critical.html contain Unicode Hex Codes.

gulp critical ->
Instead "Test čeština" it returns "Test &#x10De&#x161tina". Any idea?

**Comment by bezoerb** [comment]
`cheerio` converts special characters to unicode. We use `cheerio` to inline the critical path css.

**Comment by yethee** [comment]
`cheerio` has option `decodeEntities` (by default: `true`)

```
cheerio.load(String(html), {
  decodeEntities: false
});
```
In this case content will remain the same, without replace special characters to entities.

**Comment by martindrzka** [comment]
Thank you guys, cheerio saved me...

**Comment by bezoerb** [comment]
Fixed entity encoding in [`inline-critical`](https://github.com/bezoerb/inline-critical/commit/91f0c24d1714849cd69d3dc3e776ad182a61b3cf)

Thanks @yethee
