### ISSUE TITLE
critical breaks self-closing tags

### ISSUE THREAD

**Issue by tbredin** [addyosmani/critical#79]
My use case is an inline svg, where critical removes the closing tag, which causes some problems

eg:
`<polygon fill="#DD7B27" points="55.92,7 91.96,61.76 20.24,61.76   "/>`

Becomes:
`<polygon fill="#DD7B27" points="55.92,7 91.96,61.76 20.24,61.76   ">`

**Comment by bezoerb** [comment]
Added an issue for this in [`inline-critical`](https://github.com/bezoerb/inline-critical/issues/8)

**Comment by bezoerb** [comment]
Waiting for https://github.com/fb55/htmlparser2/pull/129 to be merged

**Comment by bezoerb** [comment]
@tbredin it looks like this should be fixed now. Want to give it another try?

**Comment by bezoerb** [comment]
Tests are green so i'm closing this one. Please feel free to re-open it if the error still occurs
