### ISSUE TITLE
0.5.7 on npm is missing .stream

### ISSUE THREAD

**Issue by adam-lynch** [addyosmani/critical#83]
I'm not sure what's going on here but the docs and the `index.js` have `.stream`, but I just installed the latest from npm and it's not there. The rest of the exported methods are there. 0.5.7 is the version that was installed and that's the version in the package.json on GitHub.

**Comment by bezoerb** [comment]
This is not yet published on npm. You'll need to use the `master` branch for `.stream`.

**Comment by adam-lynch** [comment]
Ah ok. Yeah, I've done that. Thanks.
