### ISSUE TITLE
Option for specific CSS files?

### ISSUE THREAD

**Issue by brianmontana** [addyosmani/critical#85]
Since it grabs all link elements and inlines them, what if there was an option to include only specified css files you want inlined?

I use a noscript async fallback for css and critical inlines that :(

**Comment by bezoerb** [comment]
Critical already adds a noscript async fallback for the existing stylesheets when inlining the critical path css with `inline-critical` so you shouldn't need to implement this on your own.

**Comment by brianmontana** [comment]
Instead of checking against 'stylesheet' string in 
```html
<link rel="stylesheet" href="styles/style.css">
```
 inline-styles.js allows an option of setting a string to check in rel and inlining that specific css link element. 

```html
<link rel="critical" href="styles/critical.css">
```

**Comment by bezoerb** [comment]
@brianmontana just updated [`inline-critical`](https://github.com/bezoerb/inline-critical) to ignore link tags which are already wrapped by `noscript`. Do you want to check if this solves your problem?
Btw, what is your workflow with critical? It looks like you are using the `inline` method which is marked as deprecated. (See https://github.com/addyosmani/critical/blob/master/index.js#L101)

**Comment by brianmontana** [comment]
Oops fixed it, works perfectly now! Thanks Ben!
