### ISSUE TITLE
Ignore is not working

### ISSUE THREAD

**Issue by JZL003** [addyosmani/critical#88]
Following your demo of ignore, I found it made no difference what I did. It turns out the default install of critical in npm does not even include `clean-css`. I tried cloning the present git repository to no avail. The reason I want it is I have a few font families that critical is, oddly, changing the path to. It loads correctly  in the non-inline css but the critical inline-css goes wrong. 

Is there anything I can do?

Thanks

**Comment by bezoerb** [comment]
Try to install master from npm `npm install git+https://github.com/addyosmani/critical.git` as this feature hasn't been shipped yet.
If this doesn't work out for you it would be helpful if you could provide your critical config and the part of your css which should be ignored

**Comment by JZL003** [comment]
That still didn't work, 
I tried 

    // critical = require("/home/jonah/Dropbox/Public/MDJCL/yeoman/node_modules/critical/lib/core.js");
    // critical = require("/home/jonah/Dropbox/Public/MDJCL/yeoman/node_modules/oldCritical/index.js");
    critical = require("critical")
    critical.generate({
        // Inline the generated critical-path CSS
        // - true generates HTML
        // - false generates CSS
        inline: true,
        // Your base directory
        base: 'dist/',
        // HTML source
        // HTML source file
        src: 'index.html',
        // Target for final HTML output.
        // use some css file when the inline option is not set
        dest: 'index-critical.html',
        // // Minify critical-path CSS when inlining
        // minify: true,
        // // Extract inlined styles from referenced stylesheets
        // extract: true,
        // Prefix for asset directory
        // ignore css rules
        ignore: ['font-face']
    });

and in gulp

    gulp.task('critical', ['copystyles'], function(cb) {
        const critical = require('critical')
        critical.generateInline({
            inline: true,
            base: 'dist/',
            src: 'index.html',
            // htmlTarget: 'index.html',
            dest: 'index-critical.html',
            minify: true,
            width: 1300,
            height: 900,
             ignore: ['@font-face', /url\(/,/SIFONN_BASIC/g, 'font', /font/, /font/g, /@font-face/g]
        }, cb.bind(cb));
    });

both of which did not work. 
The css is simply

    @font-face {
        font-family:'testt';
        src:url(../fonts/SIFONN_BASIC.otf) format("opentype");
    }
 and, oddly, every time I call the `testt` font, it tries to reload the font
What actually is in the inline css is
`@font-face{font-family:testt;src:url(/fonts/SIFONN_BASIC.otf) format("opentype")}`

**Comment by JZL003** [comment]
It works now. I do not know what changed but the code is either 

    gulp.task('critical', ['copystyles'], function(cb) {
        
        return gulp.src('dist/*.html')
            .pipe(require('critical').stream({
        // Inline the generated critical-path CSS
        // - true generates HTML
        // - false generates CSS
        inline: true,
        
    
        // Your base directory
        base: 'dist/',
    
        // HTML source
    
        // HTML source file
        // src: 'index.html',
    
        // Target for final HTML output.
        // use some css file when the inline option is not set
        // dest: 'index-critical.html',
    
        // // Minify critical-path CSS when inlining
        minify: true,
    
        // // Extract inlined styles from referenced stylesheets
        extract: true,
    
        // Prefix for asset directory
    
        // ignore css rules
        ignore: ['@font-face']
    }))        .pipe(gulp.dest('dist'));

    // critical = require("/home/jonah/Dropbox/Public/MDJCL/yeoman/node_modules/critical/lib/core.js");
    // critical = require("/home/jonah/Dropbox/Public/MDJCL/yeoman/node_modules/oldCritical/index.js");
    critical = require("critical")
    critical.generate({
        // Inline the generated critical-path CSS
        // - true generates HTML
        // - false generates CSS
        inline: true,
        // Your base directory
        base: 'dist/',
        // HTML source
        // HTML source file
        src: 'index.html',
        // Target for final HTML output.
        // use some css file when the inline option is not set
        dest: 'index-critical.html',
        // // Minify critical-path CSS when inlining
        minify: true,
        // // Extract inlined styles from referenced stylesheets
        extract: true,
        // Prefix for asset directory
        // ignore css rules
        ignore: ['@font-face']
    });

**Comment by bezoerb** [comment]
^^
Thanks for using `critical`
