### ISSUE TITLE
inline: true generates CSS, not HTML

### ISSUE THREAD

**Issue by raphaelgoetter** [addyosmani/critical#89]
Hello,

I'm using critical with Gulp : 

```javascript

// Requires
var gulp = require('gulp');

// Include plugins
var critical = require('critical');

// Generate & Inline Critical-path CSS
gulp.task('critical', function() {
	critical.generate({
		base: './',
		inline: true,
		src: 'index.html',
		dest: 'index-critical.html',
		width: 320,
		height: 480,
		minify: true,
		//extract: true
	});
});

````

When task is complete, the generates `index-critical.html` will be (whole file)  : 

```html
body,h1{height:400px}body{display:block;order:1;background:beige;font-size:2em}h1{background:#6b8e23}
```

The critical CSS is good, but `inline: true` or `inline: false` generate the same result : CSS instead of HTML.

Where's the problem ?

**Comment by bezoerb** [comment]
Try to install master from npm `npm install git+https://github.com/addyosmani/critical.git` as this version hasn't been shipped yet. 
The docs for the latest version on npm an be found [here](https://github.com/addyosmani/critical/tree/v0.5.7)

when using master you can simply write your gulp task like this:
```javascript
var critical = require('critical').stream;

gulp.task('critical', function () {
    return gulp.src('index.html')
        .pipe(critical({base: './', inline: true, width: 320, height: 480, minify: true}))
        .pipe(gulp.dest('dist'));
});
```

**Comment by raphaelgoetter** [comment]
Thanks for the advice.

Tried 3 times to install, but freezes each time :/

**Comment by bezoerb** [comment]
@raphaelgoetter we finally released critical 0.6.0
Want to give it another try?
`rm -Rf node_modules/critical && npm install critical`

**Comment by raphaelgoetter** [comment]
Hello @bezoerb , thank you for the update, it works !

BTW, in the compiled HTML file,  why is the script loaded in head part ? Doesn't it block rendering ?

**Comment by bezoerb** [comment]
See: https://github.com/filamentgroup/loadCSS#usage

**Comment by raphaelgoetter** [comment]
Thanks :)

**Comment by addyosmani** [comment]
:+1:
