### ISSUE TITLE
Possible to run off URL

### ISSUE THREAD

**Issue by jonorherrington** [addyosmani/critical#90]
Hello -

First off, thank you so much for creating this. It is awesome! Quick question for you. I have used similar tasks like that of Filament Groups CriticalCSS where they allow for you to insert a URL to run the task against. This comes in handy especially when you are working with a bunch of partials to create your pages.

My question is, is there a work around like this? Can you grab an actual page or an array of src files instead of just one file?

I hope this makes sense.

Thanks!

**Comment by bezoerb** [comment]
@jonorherrington currently it's not possible to use critical with an url but i'm sure we could add this feature in one of the next releases. See #19. 
Using a bunch of partials also isn't possible as we need the full html page to compute the critical path css. How should we detect the above-the-fold content if we just have some partials and don't know how they will be sticked together?

**Comment by jonorherrington** [comment]
Good point about the partials. I was thinking off the cuff when I wrote that down. 

Thanks for the quick feedback. I look forward to seeing this feature added in an upcoming release.

**Comment by bezoerb** [comment]
@jonorherrington remote resources are now supported in `master`. 
Want to give it a try to see if it fits your needs?
