### ISSUE TITLE
Possible to manage PHP includes ?

### ISSUE THREAD

**Issue by raphaelgoetter** [addyosmani/critical#91]
Hello,

I'm using PHP templates with includes ans I'm wondering if Critical could manage this.

Ex. 

index.php : 
```
<head>
	<?php include 'head.php'; ?>
</head>
```

head.php : 
```
<link rel="stylesheet" href="assets/css/styles.css" media="all">
```

I know that PHP is a server language, but it could be possible to detect the included files ?

**Comment by bezoerb** [comment]
handling PHP is a bit out of scope for this project but you could use [php2html](https://github.com/bezoerb/php2html) to create the html files in the first place

**Comment by raphaelgoetter** [comment]
Could do the job, thanks.
