### ISSUE TITLE
Media Queries not applied ?

### ISSUE THREAD

**Issue by raphaelgoetter** [addyosmani/critical#93]
Hello,

(gulp-)Critical shouldn't add Media Queries rules when they are larger than the specified scope.

My dimensions config : 

```
.pipe(critical({
      base: prod,
      inline: true,
      width: 320,
      height: 480,
      minify: true
    }))
```

When inlined, some undesired Media Queries appear : 

```css
@media (min-device-width:768px) {...}
...
@media (min-width:766px) {...}
...
@media (min-width:1400px) {...}
```

Are there some options I forgot ?

**Comment by bezoerb** [comment]
I think this might be an issue in [`penthouse`](https://github.com/pocketjoso/penthouse)
@pocketjoso any thoughts on this?

**Comment by pocketjoso** [comment]
@bezoerb You're right, `Penthouse` so far doesn't parse media queries other than for the purpose of removing empty ones.

@raphaelgoetter Can you open an issue in [Penthouse](https://github.com/pocketjoso/penthouse/issues) and I'll try to get something in this weekend?

**Comment by pocketjoso** [comment]
Opened an issue: https://github.com/pocketjoso/penthouse/issues/67

**Comment by raphaelgoetter** [comment]
Sorry, i'm on holidays with very few connexion :/

**Comment by pocketjoso** [comment]
@raphaelgoetter No rush, it's not going to be resolved overly quickly on Penthouse's side anyway.

**Comment by bezoerb** [comment]
@pocketjoso any updates on Penthouse's side?

**Comment by pocketjoso** [comment]
I'll add this functionality to `Penthouse` now, will have a new release with a fix for it later today.

**Comment by pocketjoso** [comment]
Unmatched media queries are now removes as per [Penthouse@0.7.0](https://github.com/pocketjoso/penthouse/releases/tag/v0.7.0)

**Comment by bezoerb** [comment]
Just updated to penthouse 0.7.0
Thanks @pocketjoso
