### ISSUE TITLE
Add URL support and support for filetypes other than HTML

### ISSUE THREAD

**Issue by jmartsch** [addyosmani/critical#94]
Hi, it would be great if an option would be added where i can use a URL instead of a HTML-File because my files are served with a CMS.
criticalCSS from Filament Group has support for this, but does not do the inlining. This is bad for my build process.

After getting the critical CSS the inlining should work with every filetype, as I have to use .php or .inc files.
This could be an example:
```
critical.generate({
    inline: true,
    url: 'http://localhost/myproject/www',
    src: 'header.php',
    dest: 'header-critical.php',
    width: 1300,
    height: 900,
    minify: true
});

**Comment by bezoerb** [comment]
@jmartsch i'm sure we could add this feature in one of the next releases. See #19 and #90.
Until then you could use [`inline-critical`](https://github.com/bezoerb/inline-critical) for inlining.

**Comment by jmartsch** [comment]
Thank you for the quick reply and suggestion.

I am looking forward to the next version :)

**Comment by bezoerb** [comment]
@jmartsch just got another thought on your issue. Even with critical supporting urls i think it wouldn't be possible to inline the results to your `header-critical.php` as the inlining only works with html.
When using php it's easy to inline the generated critical css yourself by just using something linke this:
```html
<style><?php include 'critical.css'; ?></style>
<script>
   function loadCSS(a, b, c) { … }
   loadCSS('mystylesheet.css');
</script>
<noscript>
   ...
</noscript>
```

**Comment by jmartsch** [comment]
I thought of the same :) Thanks.

**Comment by bezoerb** [comment]
@jmartsch remote resources are now possible when you are using the `master` branch.
Want to give it a try?

**Comment by jmartsch** [comment]
@bezoerb Yes I want to try it, what is the parameter for the remote resource? Could not find it in the readme.

**Comment by jmartsch** [comment]
As I installed this via npm i am getting an old version (0.6.0). Just have to figure out, how to get master branch via npm.

**Comment by bezoerb** [comment]
@jmartsch for simple use cases it should just work when you use an url for the src parameter.
When you want to inline images, too you should also configure `assetPaths`

use `npm install --save-dev git+https://github.com/addyosmani/critical.git`

**Comment by bezoerb** [comment]
you can also try the cli with some urls:
e.g.
`node_modules/.bin/critical http://2015.jsconf.eu/ -m`

**Comment by jmartsch** [comment]
Running `node_modules/.bin/critical http://localhost/mysite/www -m` works.
But when I use gulp I get the following error:
Unhandled rejection Error: A valid source and base path are required.

Here is my gulp task
```coffee
gulp.task 'criticalCSS', ->
  critical.generate
    inline: false,
    src: 'http://getbootstrap.com/'
    minify: true
  return
```

**Comment by jmartsch** [comment]
Bump

**Comment by bezoerb** [comment]
No, sorry. Hope to have some free time in the next days to work on this.

**Comment by bezoerb** [comment]
@jmartsch i guess you missed the `base` option ;)
I added some default value as this is mostly relevant for image inlining and the extract option and has no real impact when neither of these are used.
You don't need `inline:false` as this is the default value.
Want to try again?

**Comment by jmartsch** [comment]
It just doesn´t work. I updated to latest version, then
ran my gulp task
```coffee
critical = require('critical');

gulp.task 'criticalCSS', ->
  return critical.generate
    src: 'http://www.heise.de'
	base: '/'
	dest: './critical.css'
```
Then the task runs forever. It generates a temporary .html and two .css files. But the contents are always coming from getbootstrap.com and not from the domain I entered in src. Am I doing something wrong?

**Comment by bezoerb** [comment]
That's weird. 
I tried to reproduce your error:
```
rm -Rf node_modules/critical && npm install --save-dev git+https://github.com/addyosmani/critical.git
```

```javascript
gulp.task('critical', function() {
    return critical.generate({
        src: 'http://www.heise.de',
        dest: '.tmp/critical.css',
        minify: true
    });
});
```

```bash
❯ gulp critical
[00:06:56] Using gulpfile ~/test/gulpfile.js
[00:06:56] Starting 'critical'...
[00:07:02] Finished 'critical' after 6.6 s
```
and got some critical css from heise.de
```css
.heisetopnavi #heisetopnavi_sub_container ...
```

**Comment by jmartsch** [comment]
Maybe this is a problem on Windows? I am using Windows 10 (Win 8.1 at time of first writing) and tried it with node 4.2.1 and 0.12.7, but none of them finishes. I tried using penthouse directly and it ran fine.
Although now after removing and reinstalling critical, the content gets pulled from heise.de, but using your code example also leaves the temp files, and the process does not finish. Seems like Phantomjs keeps running and doesn´t quit.

**Comment by bezoerb** [comment]
@jmartsch the issue is reproducible on windows. I've fixed this for external urls in master but the gulp still hangs when using local files.

**Comment by bezoerb** [comment]
@jmartsch this should be solved in master by now

**Comment by jmartsch** [comment]
@bezoerb It works now but it does take a long time for the task to finish although gulp says the task is finished.
```
PS C:\xampp\htdocs\jmd> gulp critical
[11:48:27] Requiring external module coffee-script/register
[11:48:43] Using gulpfile C:\xampp\htdocs\jmd\gulpfile.coffee
[11:48:43] Starting 'critical'...
[11:48:43] Finished 'critical' after 7.69 ms
```
After the message appears, the files are generated, but ending the process and deleting of the temporary files does take another 20-25 seconds after that in my case.

**Comment by bezoerb** [comment]
@jmartsch i'm investigating this at the moment. 
Looks like something's holding back the `process.exit`
```shell
[23:12:15] Finished 'critical' after 3.43 s
  critical:gc exit triggered +27s
  critical:gc cleanup triggered +1ms
  critical:gc cleanup done +1ms                                 
```

**Comment by bezoerb** [comment]
so i guess the time lag results from an uncleared timeout in [`penthouse`](https://github.com/pocketjoso/penthouse/blob/master/lib/index.js#L95)
When i manually patch penthouse to clear the timeout after phantomjs is done the 20-30s lag is gone

**Comment by bezoerb** [comment]
https://github.com/pocketjoso/penthouse/pull/98

**Comment by jmartsch** [comment]
@bezoerb Thanks for taking your time looking into this :)

**Comment by bezoerb** [comment]
Pull request accepted & penthouse bumped.
The delay is gone :)

**Comment by jmartsch** [comment]
You´re the best. Thanks for everything :)

**Comment by pajtai** [comment]
I get a timeout with the example in the thread, and for remote html pages with absolute link, I get enoent errors

e.g. `<link href="/vendor/fontawesome/css/font-awesome.min.css" rel="stylesheet">`

produces

`Unhandled rejection Error: ENOENT: no such file or directory, open 'vendor/fontawesome/css/font-awesome.min.css'
    at Error (native)`
