### ISSUE TITLE
Inventing Styles?

### ISSUE THREAD

**Issue by Snugug** [addyosmani/critical#96]
When I run Critical on [my blog](https://github.com/snugug/blog), Critical is adding a few styles that are not in my stylesheets normally, including `background-color: #9999cc` and `border-bottom: 1px inset black`.

More weird, actually, is it's adding a bunch of styling to raw tags and, except for my CSS reset, I don't style using raw tags, so I don't know where these styles are being found and pulled in from. Thoughts?

**Comment by bezoerb** [comment]
This problem sounds really weird.
Could you provide some more details about your critical configuration so we can dig in a bit?

**Comment by Snugug** [comment]
Here's my critical task:
https://github.com/Snugug/gulp-armadillo/blob/master/tasks/critical.js

**Comment by Snugug** [comment]
Okay, this was a weird one to track down, but everything's fine! There was a `XMLHttpRequest` somewhere that wasn't returning correctly and in Chrome that was writing something crazy stupid that included tag styling and that's where this was coming from.

**Comment by bezoerb** [comment]
;)
