### ISSUE TITLE
Make plugin work with "cdnified" HTML files.

### ISSUE THREAD

**Issue by tigranpetrossian** [addyosmani/critical#97]
The way my Gulp setup is structured, Critical runs after creating a build where the href to CSS looks like `http://cdn.example.com/css/styles.css` so obviously I end up with an empty `<style>` tag as a result. 

It would be great to make critical grab CSS from a local file by converting `href` to a relative reference. Please? :)

**Comment by bezoerb** [comment]
@tigranpetrossian could you try again with the `master` branch?
```
npm install git+https://github.com/addyosmani/critical.git
```

**Comment by tigranpetrossian** [comment]
@bezoerb Works as charm. Thank you!
